### ISSUE TITLE
Needs a better name other than pureconfig

### ISSUE THREAD

**Issue by seemethere** [pureconfig/pureconfig#1]
I feel like the name `pureconfig` won't take off but I do like the spec of the project.

Suggestions:
* `hrc` -> `human readable configs`
* `yacs` -> `Yet Another Configuration Spec`

I'd love to write a python parser for it as well, but definitely not with the name `pureconfig`

**Comment by lonesentinel19** [comment]
Maybe something to do with indentation, such as tabconfig? Or NBConfig (No Brackets Config). I don't know.

**Comment by pureconfig** [comment]
Thanks, pureconfig is definitely just a working name

**Comment by dansouza** [comment]
how about just `Fig` ?

**Comment by seemethere** [comment]
@dansouza I think `Fig` would make it not as easily searchable.

**Comment by dansouza** [comment]
Kinda collides with https://github.com/cheezy/fig_newton

**Comment by dansouza** [comment]
But Googling for "fig configuration" should return it because it returned that FigNewton, so search-ability wouldn't be an issue.

**Comment by jsejcksn** [comment]
@seemethere suggested `hrc` (which I like), but it is already in use for 3D model geometry files output by the legacy [Softimage](https://en.wikipedia.org/wiki/Autodesk_Softimage). Therefore, I suggest modifying that slightly by adding `f` to the end to yield:

`hrcf` = `human readable configuration format`

**Comment by dansouza** [comment]
The problem with hrcf IMO is that it is not speakable as a word. You can say JSON as "jay-son", you can say YAML as "yam" and XML is short and sweet and on the tip of the tongue because it is widely used. Saying "just create an eitch-ahr-cee-eff configuration file" sounds like a mouthful. IMO it needs to be a word that you can just say it without spelling each letter. That's why I suggested `Fig` (from "just create a fig file and ...").

**Comment by pureconfig** [comment]
I really like both "yacs" and "fig" so far, but I'll let this topic cook for a few days.

**Comment by dansouza** [comment]
Yeah I like "yacs" too!

**Comment by dansouza** [comment]
Plus with "yacs" you can have a nice [yack](https://lh5.googleusercontent.com/--qDJcsq1ZkU/TYbmjuCIb2I/AAAAAAAAAMM/SzKDVW61SSg/s1600/000cf1a48b7f0ae0c8ea08.jpg) as a logo (a good symbol for a strong tool for every job), better than a [fruit](http://www.ginskitchen.com/wp-content/uploads/2015/08/Fig-v3.jpg). LOL

**Comment by ludesign** [comment]
`yacs` is too close to `yacc` (https://en.wikipedia.org/wiki/Yacc) and `fig` is duplicated in `config` but can be used interchangeably, ex: `just create a fig file for it`.

**Comment by dansouza** [comment]
yacs and yacc are from different domains, so I think it's ok (google certainly doesn't confuse them, since searching for "yacs config" does not bring results about "yacc configuration").

as for `suck`, did you mean the `simplified universal configuration kit` ? lol

**Comment by ludesign** [comment]
I actually don't care much, so use whatever you want. 😹 

`simplified universal configuration kit` - haha, that's so much better, nice one.

**Comment by pureconfig** [comment]
It seems like just calling it "pure" is growing on some people. But, hey, a big rename later on is trivial as long as everything is kept in this repo (should ask the Rust guy to move his stuff here...)

**Comment by pureconfig** [comment]
Let's just go for pure.

**Comment by sjmduncan** [comment]
[This Scala library is also called pureconfig](https://github.com/melrief/pureconfig) and it's already higher up most search result list so maybe this should be re-opened
