### ISSUE TITLE
Add ConfigWriter for YAML module

### ISSUE THREAD

**Issue by daniel-dylag-openx** [pureconfig/pureconfig#1006]
In my organization, we're relying on pureconfig-yaml to read our configuration files. Recently we started to build some tools that are supposed to read some YAML configuration and generate another configuration in YAML for other component to consume. In order for that to be possible with pureconfig, we need to have a way to both read and write YAML configuration.

**Comment by daniel-dylag-openx** [comment]
I've found out a way to write out YAML config using some of SnakeYAML API directly.
```
    import org.yaml.snakeyaml.Yaml
    import pureconfig.generic.auto._
    import java.io.{File, PrintWriter}

    val configValue = ConfigWriter[MyObject].to(myObject)
    val valueUnwrapped = configValue.unwrapped()
    
    val yaml = new Yaml
    val writer = new PrintWriter(outputPath)
    
    yaml.dump(valueUnwrapped, writer)
```
I'm not sure if this is the right way, maybe it could be available as a method in YamlConfigSource object next to methods for reading. Anyway, that would be nice to have it documented.

**Comment by ruippeixotog** [comment]
Hi Daniel! Unfortunately, PureConfig can't help you with that - it is primarily a library to read and write HOCON (Lightbend Config) files, not YAML. `pureconfig-yaml` is a good way to achieve interop between YAML and HOCON, but it works at the `ConfigSource` level so the translation from YAML to HOCON is unidirectional and happens before `ConfigReader`/`ConfigWriter` instances even know about it. If the use case is reading and writing YAML only I'm sure there are better Scala libraries out there 🙂 

That said, your solution seems to be reliable. `unwrapped()`'s return types [are documented](https://github.com/lightbend/config/blob/main/config/src/main/java/com/typesafe/config/ConfigValue.java#L37-L45) and seem to match the ones [accepted by `yaml.dump`](https://bitbucket.org/asomov/snakeyaml/wiki/Documentation#markdown-header-dumping-yaml), so you should be fine.
