### ISSUE TITLE
Cats-effect 3 release

### ISSUE THREAD

**Issue by pjan** [pureconfig/pureconfig#1009]
Any idea when we could expect this to hit; last library for us to do complete the upgrade.

**Comment by ruippeixotog** [comment]
I'll release a new version this weekend. Sorry and thank you for waiting :)

**Comment by rubiconvvv** [comment]
We will wait. Thanks

**Comment by pjan** [comment]
@ruippeixotog please mate, never say "sorry" for doing something you do on a voluntary basis. We all very much appreciate the work everyone's putting into this. This was only about planning and expectation setting on my end - was going to put up a PR for CE3 changes, when to my delight I saw those were already done. 🙏

**Comment by ruippeixotog** [comment]
PureConfig v0.15.0 should now be in Sonatype.
