### ISSUE TITLE
Supports for cats data structures

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#101]
cats exposes some [interesting structures](https://github.com/typelevel/cats/tree/5a9717a4499265275bc5c3c6e4f2e3ac3d1e17f5/core/src/main/scala/cats/data) that can be converted from/to a configuration value. For instance, I use `NonEmptyList` often. We should create a module for pureconfig.

**Comment by ruippeixotog** [comment]
Is our objective with this module just providing `ConfigConvert` instances for `cats` data structures? Personally, the most important thing I expect from a cats module would be type class instances (such as `Monad` and `Contravariant`) for `ConfigReader`, `ConfigWriter` and possibly `ConfigConvert`. I don't know what you think about that, but I would leave this issue open until we had that :)

**Comment by derekmorr** [comment]
I think that's a separate PR.

**Comment by ruippeixotog** [comment]
I agree it's a separate PR, I only mentioned the issue.

I suggested leaving this open as "Supports for cats" is a pretty broad title, but if you want to open a new issue I'm fine with that.

**Comment by melrief** [comment]
This is for the data structures of cats. Stuff like th enon empty structures can be very helpful (at least for me)

**Comment by ruippeixotog** [comment]
Ok. Can we change the title of this issue to indicate this is "Support for cats data structures"? I'll open a new issue for including cats type classes. Do you agree that they should be provided in the `pureconfig-cats` module, too?

**Comment by derekmorr** [comment]
I've renamed this issue per the comment above. I think the `pureconfig-cats` module is a logical place to put cats type classes.
