### ISSUE TITLE
Move away from the monolithic README.md

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#102]

**Comment by ruippeixotog** [comment]
With our curent TOC, what do we want to move to the `core` module docs? There aren't includes in Markdown - that means some text will be a click away.

I was thinking of leaving the TOC as is and leave in the README all sections from "Why" to "Supported types" and from "Contribute" to "Special thanks". They provide the very basics for people to know what PureConfig is all about. All other sections can be accessed by the TOC, which links to other Markdown files.

@melrief, @jcazevedo, @leifwickland, do you agree?

**Comment by melrief** [comment]
I agree

**Comment by jcazevedo** [comment]
> @melrief, @jcazevedo, @leifwickland, do you agree?

Yes.

**Comment by leifwickland** [comment]
_shrug_ 
My preference in the long term is that we let `tut` or another tool generate our ToC. I'm not entirely sure how that'll work out with that structure. But that's a bridge we can cross later.
