### ISSUE TITLE
No Imports for pureconfig.generic.auto._

### ISSUE THREAD

**Issue by SarpongAbasimi** [pureconfig/pureconfig#1027]
In the pureConfig documentation there is an import for `import pureconfig.generic.auto._`

<img width="524" alt="Screenshot 2021-04-27 at 12 51 34" src="https://user-images.githubusercontent.com/37377831/116236734-51b8f000-a757-11eb-960d-bc81581399a4.png">

but the only thing I see in that path is `error`.

<img width="906" alt="Screenshot 2021-04-27 at 12 49 25" src="https://user-images.githubusercontent.com/37377831/116236532-14546280-a757-11eb-8836-3ea4b395c665.png">

<img width="347" alt="Screenshot 2021-04-27 at 12 52 56" src="https://user-images.githubusercontent.com/37377831/116236909-83ca5200-a757-11eb-8fd2-d5ba7a76f823.png">

Is this an issue that needs addressing?

**Comment by leifwickland** [comment]
@SarpongAbasimi, Thanks for using pureconfig.

From the screenshot above, it appears that you're depending on `pureconfig-generic-base`. I think you need to depend on `pureconfig-generic`, not `pureconfig-generic-base`. I see the `auto` namespace in the `pureconfig-generic` JAR, but not in the `pureconfig-generic-base` JAR. 

It appears that was also the case in versions prior to 0.15.0.

Please let me know if that helps.

**Comment by SarpongAbasimi** [comment]
Thans @leifwickland.
It appears that when I add `pure -config` as a dependency in the root of my application, it works fine.
But when I add it as a dependency for a submodule, that is when I get the problem.

**Comment by leifwickland** [comment]
@SarpongAbasimi, I tried to reproduce the problem you described in [this repo](https://github.com/leifwickland/pureconfig-submod-generic). I wasn't able to. Would you be willing to create a simple example that demonstrates the problem you're seeing?

**Comment by SarpongAbasimi** [comment]
@leifwickland 

so basically in my `build.sbt` I have this.
lazy val pureConfigVersion      = "0.15.0"

```
lazy val root = (project in file("."))
  .settings(
    name := "dummyProject",
    applicationSettings
  )
  .aggregate(
    persistenceService,
  )
```

persistence service is 

```
lazy val persistenceService = (project in file("modules/persistenceService"))
  .settings(
    moduleName := "persistenceService",
    libraryDependencies ++= Seq(
     "com.github.pureconfig" %% "pureconfig"                    % pureConfigVersion,
    ),
    applicationSettings
  )
```

inside the `Scala` directory in  `persistenceService` I have a directory called `config` which contains a file called `Dbconfig`

When I try to import 
`import pureconfig.generic.auto._` in `Dbconfig` that is when I get the issue of 
`No Imports for pureconfig.generic.auto._`

I hope this helps.
I have resolved this by importing `import pureconfig.generic.auto._` in the root of my project.
