### ISSUE TITLE
Upgrade http4s module from 0.21 to 0.23

### ISSUE THREAD

**Issue by Ali-Mahmood** [pureconfig/pureconfig#1086]
Not upgrading will prevent projects who use pure config from upgrading to http4s 0.23, example below:

`[error]         * org.http4s:http4s-core_2.13:0.23.0-RC1 (early-semver) is selected over 0.21.24
[error]             +- org.http4s:http4s-dsl_2.13:0.23.0-RC1 ()           (depends on 0.23.0-RC1)
[error]             +- org.http4s:http4s-server_2.13:0.23.0-RC1 ()        (depends on 0.23.0-RC1)
[error]             +- org.http4s:http4s-blaze-core_2.13:0.23.0-RC1 ()    (depends on 0.23.0-RC1)
[error]             +- org.http4s:http4s-client_2.13:0.23.0-RC1 ()        (depends on 0.23.0-RC1)
[error]             +- com.github.pureconfig:pureconfig-http4s_2.13:0.16.0 (depends on 0.21.24)
`

**Comment by ruippeixotog** [comment]
Hi! We'll likely wait for a stable version to be released before the module is upgraded. In the meantime, you can avoid that error by temporarily removing pureconfig-http4s from your dependencies. That module contains only an `Uri` converter, so it should be easy to replace.

**Comment by Ali-Mahmood** [comment]
Hi! I see, that sounds good. Ill do that for now, thank you!

**Comment by augi** [comment]
It would be nice to release also a version of pureconfig depending on http4s `0.22` in the meantime 🙏

**Comment by satorg** [comment]
@ruippeixotog just fyi: looks like this issue can be closed since the v0.23 is supported since pureconfig v0.17.0, isn't it?

**Comment by satorg** [comment]
> It would be nice to release also a version of pureconfig depending on http4s 0.22 in the meantime 🙏

Totally agree :) Would a PR with a new pureconfig-http4s-022 module be accepted if I go ahead and create it? Does not seem to be something tremendously difficult, but will make lives of some folks easier.

**Comment by ruippeixotog** [comment]
Hey @satorg, you're right, `pureconfig-http4s` is currently using v0.23, we can close this 👍 

The goal of releasing PureConfig depending on 0.22 was just a temporary workaround while we didn't have 0.21 IIUC, so there shouldn't be any need to create additional forks, right?

**Comment by satorg** [comment]
@ruippeixotog thank you for looking into it.

The thing is that there's quite a bit of projects around that still cannot that easy switch to Cats Effect 3 and hence get http4s v0.23. The only feasible option on such projects is Http4s v0.22.

On the other hand, there's a fork for Cats Effect 2 in the Pureconfig repository already – [cats-effect2](https://github.com/pureconfig/pureconfig/tree/master/modules/cats-effect2). Therefore _I think_ it would be very appreciated by folks on such projects if there was an opportunity to keep Pureconfig core up-to-date whilst using Cats Effect 2 and Http4s v0.22. Besides apparent benefits, it would simplify further transitions to Cats Effect 3/Http4s v0.23 as well (less dependencies to bump up at once).

**Comment by satorg** [comment]
Added a PR #1421 with a support for **http4s v0.22**, humbly hoping it makes some sense.

cc @ruippeixotog @augi
