### ISSUE TITLE
Avoid using Case class

### ISSUE THREAD

**Issue by mehuljain53** [pureconfig/pureconfig#1147]
Is there a way I could avoid using scala case class and use Java class? What changes will I have to make?

**Comment by ruippeixotog** [comment]
@mehuljain53 supporting types that are not supported out-of-the-box by PureConfig is documented in https://pureconfig.github.io/docs/supporting-new-types.html.

Please don't use GitHub issues for general support requests - our [Gitter](https://gitter.im/melrief/pureconfig) is a more appropriate channel. I'm going to close this for now, but if you feel that there's a specific feature missing in PureConfig feel free to create a new issue.
