### ISSUE TITLE
Add modules section to README

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#120]
Now that we are starting to have some modules for pureconfig, it would be nice to add to the main page all the supported libraries together with the name of the dependency to add to sbt.

**Comment by leifwickland** [comment]
@melrief Do you think this section would best go in the main README or in a separate doc it linked to?
My inclination is for putting it in the main README.

**Comment by melrief** [comment]
It really depends on how many modules we will have in the repo. I think we'll end up with many modules and that's why I would prefer to have a separate markdown file. I would just write a couple of lines in the main README poiting out that there is support for external libraries via modules with a link to the section file.
There is also a small part in the contributing section that should be done explaining how to submit a PR containing a module and how it will be published.

**Comment by leifwickland** [comment]
@melrief I figured we'd end up with a reasonably detailed README in each module and a relatively sparse index of the available modules in either the main README or a linked file from the main ToC.

Are you OK with that vision?

I'll let you (or someone else) handle the contributing section as I'm not sure what you want to say there.

**Comment by melrief** [comment]
I'm OK with that vision but some modules don't have a README

**Comment by leifwickland** [comment]
Yeah, sorry. I was going to use this as an excuse to add a README for those that don't have them.

**Comment by leifwickland** [comment]
Yeah, I should've mentioned I was going to use this as the opportunity to add a README for the rest of the modules.

**Comment by melrief** [comment]
Well if you add the missing README then it's perfect!

**Comment by leifwickland** [comment]
I suppose it'd also be useful to document integrations with pureconfig that aren't part of the repo, such as refined-pureconfig.

**Comment by melrief** [comment]
Probably but it will be difficult to keep track of external modules.
