### ISSUE TITLE
Is there no support for scala enums?

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [pureconfig/pureconfig#1210]
I can see there is support for java enums, enumeratum, and julienrf’s enum library, but what about scala enums?

The enums I'm talking about are the [2.x](https://www.scala-lang.org/api/2.13.3/scala/Enumeration.html) and [3.x](https://docs.scala-lang.org/scala3/reference/enums/enums.html) enums:

```
object WeekDay extends Enumeration {
  type WeekDay = Value
  val Mon, Tue, Wed, Thu, Fri, Sat, Sun = Value
}
```

```
enum Color:
  case Red, Green, Blue
```

**Comment by leifwickland** [comment]
@Daniel-Khodabakhsh,

There's no automatic derivation for Scala 2 enums, but there is [automatic derivation support for Scala 3 enums](https://pureconfig.github.io/docs/scala-3-derivation.html).

**Comment by Daniel-Khodabakhsh** [comment]
Thanks @leifwickland
No automatic derivation for Scala 2 enums eh? What is the manual way of doing it? I've tried searching for resources but couldn't find any example of Scala 2 enums with Pureconfig.

**Comment by leifwickland** [comment]
@Daniel-Khodabakhsh,

I'd do something like:

```
import scala.util.{Failure, Success}
object Color extends Enumeration {
  type Color = Value
  val Red, Green, Blue = Value
  implicit val reader: ConfigReader[Color.Color] = ConfigReader.fromNonEmptyStringTry {
    case "red"   => Success(Red)
    case "green" => Success(Green)
    case "blue"  => Success(Blue)
    case unknown => Failure(new Exception(s"Cannot create a Color from unknown value $unknown."))
  }

}

object CApp {
  case class Conf(color: Color.Color)
  object Conf {
    implicit val reader: ConfigReader[Conf] = pureconfig.generic.semiauto.deriveReader[Conf]
  }
  def main(args: Array[String]): Unit = println(pureconfig.ConfigSource.string("color: red").load[Conf])
}
```

That prints `Right(Conf(Red))`.

**Comment by Daniel-Khodabakhsh** [comment]
Thank you so much @leifwickland !
