### ISSUE TITLE
Fails to parse uppercase booleans

### ISSUE THREAD

**Issue by fmeeuw** [pureconfig/pureconfig#1286]
Since the upgrade to `0.17.1` it seems pureconfig fails to parse uppercase strings such as "FALSE" and "TRUE" as booleans.
In our setup we have a Config case class with a boolean value `enabled` and use this import `import pureconfig.generic.auto._`.
I got an runtime error when trying to parse the value "FALSE" as a boolean, the error was:

```pureconfig.error.ConfigReaderException: Cannot convert configuration to a Config. Failures are:
  at 'enabled':
    - (env variables) Expected type BOOLEAN. Found STRING instead.
    ```

**Comment by ruippeixotog** [comment]
Hi @fmeeuw! I have just tried reading an uppercase FALSE/TRUE string using v0.17.0 and it didn't work either:

```
❯ cat build.sbt
libraryDependencies += "com.github.pureconfig" %% "pureconfig" % "0.17.0"

❯ sbt console
scala> ConfigSource.string("b = FALSE").at("b").loadOrThrow[Boolean]
pureconfig.error.ConfigReaderException: Cannot convert configuration to a boolean. Failures are:
  at 'b':
    - (String: 1) Expected type BOOLEAN. Found STRING instead.

  at pureconfig.ConfigSource.loadOrThrow(ConfigSource.scala:81)
  at pureconfig.ConfigSource.loadOrThrow$(ConfigSource.scala:78)
  at pureconfig.ConfigSource$$anon$2.loadOrThrow(ConfigSource.scala:332)
  ... 31 elided
```

Can you point me out to an old PureConfig version that does this?

**Comment by fmeeuw** [comment]
Hi @ruippeixotog,

I am sorry, a miscalculation on my part, I was assuming wrongly it was working before with 0.17.0 , but I checked all versions of pureconfig and uppercase never worked. So I guess this is not really an issue, more a design choice. 
I guess we can close this.

**Comment by ruippeixotog** [comment]
In this case it's not even PureConfig's design choice, we're following [Typesafe Config's rules](https://github.com/lightbend/config/blob/main/config/src/main/java/com/typesafe/config/impl/DefaultTransformer.java#L42-L48) when it comes to converting config values to booleans, which itself follows the list of supported strings in the [HOCON spec](https://github.com/lightbend/config/blob/main/HOCON.md#automatic-type-conversions). PureConfig readers are often more powerful than Typesafe Config operations, but in this case I think it makes sense for us to stick with the HOCON spec. Nothing prevents you from writing your `ConfigReader` for this, of course 🙂
