### ISSUE TITLE
PureConfig fails to load coproducts when two entities have the same number of parameters

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#13]
Minimal example

``` scala
> sealed trait A
> case object B extends A
> case object C extends A
> pureconfig.loadConfig[A](Map("foo"->"A"), "foo")
res4: util.Try[A] = Success(B)
```

The problem is that PureConfig is ignoring the labels which are important for coproducts.

**Comment by TeraWilliam** [comment]
Need to define what the expected behaviour is. e.g. is the "A" case sensitive or not, and how do you handle camel-case names, e.g. "ReadOrWrite" == "readorwrite" or "read-or-write"

**Comment by melrief** [comment]
The case sensitive part and more generally the name format is a problem that I was going to address in future. My idea is to add the possibility to define a function `fieldFormat:: String => String` in `loadConfig` that the user could use to transform any kind of names to a proper defined name in PureConfig. For instance, the function could convert "ReadOrWrite" to "readorwrite", same for the String "read-or-write" and the format would be configurable and fully compatible with the current system. By default the function would be `identity` but a `lowercase` version would be available for import.

Another thing to define is if the name of the entity should always be there. PureConfig currently does the following

``` scala
> case class D(int: Int) extends A
> pureconfig.loadConfig[A](Map("foo.int" -> "1"), "foo")
res2: util.Try[A] = Success(D(1))
```

but maybe it would be better and more correct to have the name of the entity before the name of the fields in case of families

``` scala
> pureconfig.loadConfig[A](Map("foo.D.int" -> "1"), "foo")
res2: util.Try[A] = Success(D(1))
```

In this way, PureConfig would be able to support families with multiple objects and classes with the same fields and this problem would be immediately solved.

**Comment by TeraWilliam** [comment]
IMO case classes should be handled differently from "enums".

For an "enum" (eg sealed trait + case objects only) only the value decides the outcome.

Non-enum support would be great but I'd guess it's harder to define the problem and a solution and could be handled as a separate issue.
