### ISSUE TITLE
could not find implicit value for parameter conv

### ISSUE THREAD

**Issue by pishen** [pureconfig/pureconfig#14]
I'm using pureconfig with Scala 2.10.6, when running `sbt compile` everything works fine, but my Eclipse keep showing an error on the following line:

```
loadConfig[Conf.MIH](typesafeConfigToConfig(typesafeConf), "mih").get
```

The error is

```
could not find implicit value for parameter conv: pureconfig.ConfigConvert[mih.Conf.MIH]
```

My definition of `MIH` is

```
object Conf {
  case class MIH(s3: S3, redis: Redis)
  case class S3(workspaceBucket: String, workspacePath: String)
  case class Redis(url: String)
}
```

**Comment by melrief** [comment]
I'm not familiar with Eclipse for Scala but I know that IDEs can have problems with type classes. Sadly, I'm not sure how can I help you with the problem.

**Comment by pishen** [comment]
I got some clues on this thread
https://groups.google.com/forum/#!topic/scala-ide-user/gLJN1-8Fz-U
Adding `-Ymacro-expand:normal` can help, but only when using Scala 2.11. This is already promising for me. Thanks for the help!
