### ISSUE TITLE
Define ConfigConvert methods for Remaining JSON types

### ISSUE THREAD

**Issue by mslinn** [pureconfig/pureconfig#146]
Currently there are a number of `ConfigConvert` methods for `String`. A similar set of methods should be defined for the other JSON types. The most important types to address are `Number` and `Boolean`; for extra credit, also define methods for `Array`, `object` and `null`.

**Comment by ruippeixotog** [comment]
Hi @mslinn! I'd like to understand better what you mean with "ConfigConvert methods". You have `ConfigConvert` instances for all Scala-equivalent JSON types (`Int`, `Double`, `Boolean`, `List[A]`, `Map[K, V]`), so you can read from and write all JSON types to a config.

Or did you need a method to build a `ConfigConvert` from a number, just like `ConfigConvert.fromString`? Can you give me an example or use case so I can better understand the problem?

**Comment by melrief** [comment]
@mslinn I close this because we use our own converters to get `Number` and `Boolean` and they are much more powerful than the ones provided by typesafe config and have better error messages.

**Comment by mslinn** [comment]
Where are those converters? I found [modules](https://github.com/pureconfig/pureconfig/tree/master/modules) but none of them seem like what you are talking about.
