### ISSUE TITLE
Improve the error message when the FieldMapping is wrong

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#147]
The field mapping is a great feature of pureconfig but has the side-effect of making more difficult to understand certain problems. For people coming from pureconfig < `0.6.0`, the default mapping is CamelCase->CamelCase and the errors about keys not found make no sense. A solution could be that, given a certain set of keys not found, pureconfig could try to see if there are matching keys with other field mapping, e.g. `foo-bar` instead of `fooBar`. This isn't easy to implement because we need to be able to access to all the other possible field mapping and I'm not sure how this could be encoded. The main drawback of this is that the error message would take longer to be generated but I would say it's worth it.

**Comment by jcazevedo** [comment]
Fixed in #238.
