### ISSUE TITLE
Is it possible to define ConfigReader for "polymorphic" inputs?

### ISSUE THREAD

**Issue by erikerlandson** [pureconfig/pureconfig#1472]
I wish to define `ConfigReader[Rational]`, where a Rational might take any of the following forms:
- an integer value 
- a floating point value
- a structure `{ n: <int> d: <int> }`

So in a sense I want an "or" combinator `||`, that hypothetically might look like:

```scala
    given rationalReader: ConfigReader[Rational] =
        ConfigReader[Int] || ConfigReader[Double] || ConfigReader.forProduct2("n", "d")(Rational(_, _))
```

Or some idiomatic way of doing the same thing manually.

At the bottom, what is needed is a way to "speculatively" read from a ConfigCursor, where if it fails, it can try some other option starting from the same place, and keep trying until it succeeds or all possibilities are exhausted.

**Comment by erikerlandson** [comment]
What is the behavior of a `ConfigCursor` when it fails to read?  Is it *guaranteed* to re-set to its original state?  If so, then it should be fairly simple to iteratively try reading via different `ConfigReader`s until one succeeds.

**Comment by ruippeixotog** [comment]
@erikerlandson, `ConfigReader`s are purely functional, and so are cursors - they don't modify configs or have any notion of internal state, so there's nothing to "reset".

Iterating through many options is precisely what you need and you have a combinator [`orElse`](https://github.com/pureconfig/pureconfig/blob/master/core/src/main/scala/pureconfig/ConfigReader.scala#L96-L105) that does precisely what you described with `||`, so there shouldn't be any need to work with cursors in this case.

**Comment by erikerlandson** [comment]
Ah, you are right, this works!
```scala
    given ctx_RationalReader: ConfigReader[Rational] =
        ConfigReader[BigInt].map(Rational(_, 1)) `orElse`
        ConfigReader[Double].map(Rational(_)) `orElse`
        ConfigReader.forProduct2("n", "d") { (n: BigInt, d: BigInt) =>
            Rational(n, d)
        }
```
