### ISSUE TITLE
Unresolved placeholders cause thrown exception

### ISSUE THREAD

**Issue by megri** [pureconfig/pureconfig#148]
`loadConfig` doesn't catch this in the `ConfigReaderFailure` but instead throws it directly.

**Comment by melrief** [comment]
Hey @megri, thanks for opening the issue. I guess we forgot to check `ConfigFactory.load`. After reading the [documentation](https://typesafehub.github.io/config/latest/api/com/typesafe/config/ConfigFactory.html#load-com.typesafe.config.Config-) I think I know why: there is no documentation about the exception that can be thrown by those methods and I was assuming it was safe to call. I should have known that a method that doesn't return either errors or the config was unsafe.

The good news is that it should be easy to fix. The only issue that I have is that I don't know which exceptions can we should catch. Maybe we can catch `NonFatal` and see how it goes.

**Comment by leifwickland** [comment]
I agree with catching NonFatal as you suggest, @melrief

**Comment by melrief** [comment]
I propose to create a failure only for this kind of error

**Comment by leifwickland** [comment]
Does "this type of error" mean the resolution failure or a catchall for
exceptions pureconfig didn't expect? I think we need the latter given that
the type signature seems to promise that non fatal errors will not escape.
I also like the idea of a specific error for that resolution failure.

**Comment by melrief** [comment]
I was talking about confining the exceptions thrown by `ConfigFactory.load` inside a failure class that is reserved just for that method. In my mind, that's not a `CannotConvert` failure but a `CannotLoadConfig` (or something like that).

**Comment by megri** [comment]
I think the exceptions thrown are the ones found in the ConfigLoader class. The strictest/cleanest path would be to map those to an ADT

**Comment by leifwickland** [comment]
I totally agree that it's a positive to map known errors to the failure ADT. However, I think we probably should go a step beyond that and catch unknown errors too, dropping them in an appropriately vaguely named member of the ADT.

**Comment by melrief** [comment]
@megri I'll fix this for the next release, thanks for reporting it.

**Comment by megri** [comment]
Thanks for fixing it :)
