### ISSUE TITLE
add .editorconfig

### ISSUE THREAD

**Issue by stsatlantis** [pureconfig/pureconfig#149]
Add a .editorconfig file to the root folder to keep the code style unified.

**Comment by jcazevedo** [comment]
I'm not very familiar with `.editorconfig`, but I tend to prefer solutions more tied to the build system, such as Scalariform (which we currently use). What kind of features does `.editorconfig` provide that we can't cover with Scalariform?

**Comment by stsatlantis** [comment]
@jcazevedo You are right. No need for that.
