### ISSUE TITLE
Tricky case object names

### ISSUE THREAD

**Issue by nrktkt** [pureconfig/pureconfig#1512]
Say I had some 
```scala
sealed trait Enums
case object `Chaos 4.20` extends Enums
case class MyClass(enum: Enums)
```
how would the value of the `enum` field need to look in the config file in order to parse correctly?

**Comment by ruippeixotog** [comment]
The [default field mapping](https://github.com/pureconfig/pureconfig/blob/4681fa13b5277047661c0232f276b5d5bc200110/modules/generic-base/src/main/scala/pureconfig/generic/CoproductHint.scala#L97-L99), which expects classes to be pascal case, would expect a type of "chaos -4.20" in the config for your object:

```scala
scala> import pureconfig.generic._
import pureconfig.generic._

scala> FieldCoproductHint.defaultMapping("Chaos 4.20")
res1: String = chaos- 4.20
```

Relying on the default mapping when the classes don't follow pascal case convention is not recommended - you should assume its behavior to be undefined in that case. Instead, you should provide your own implicit `FieldCoproductHint[Enums]` with a custom implementation of `fieldValue`.
