### ISSUE TITLE
Proposal: switch to Typelevel Scala compiler

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#155]
I didn't have time to try the new typevel scala compiler but it should be more optimized for compiling pureconfig. I've decided to open this issue after @leifwickland mentioned it to investigate potential performance gain and to see if we all agree in switching. Some links

- [Faster compilation of inductive implicits](https://github.com/typelevel/scala/blob/typelevel-readme/notes/2.12.1.md#faster-compilation-of-inductive-implicits-pull5649-milessabin)
- [projects switching and how to switch](https://github.com/typelevel/scala/issues/135)

**Comment by milessabin** [comment]
Just to clarify ... https://github.com/typelevel/scala/issues/135 isn't about _switching_ to Typelevel Scala, it's about _enabling_ a painless switch, but onfly if desired. Using `CrossVersion.patch` and `scalaOrganization.value` does no harm and in no way forces you to use Typelevel Scala.

**Comment by sh0hei** [comment]
implemented in https://github.com/melrief/pureconfig/pull/158

**Comment by melrief** [comment]
Thanks @sh0hei !
