### ISSUE TITLE
Map unique keys

### ISSUE THREAD

**Issue by optical002** [pureconfig/pureconfig#1578]
Is there a way to force object reading, to emit a reading error, when trying to read duplicate keys.

I have this data structure `case class Elements(map: Map[String, String])`

When reading something like this:
`map {
  1 = a,
  1 = b
}`

I would have:
map [
  "1", "b"
]

But instead I want this to be an error case, when reading a config, because maybe someone added with the same key an element and now previous one is getting overridden or it is not visible at all, since the original is now overriding the new one.

Is there a way to enforce this for `ConfigReader` or somehow else?

Current workaround is, use `ConfigReader[Vector[(K, V)]]` emap to `ConfigReader[Map[K, V]]`, and when vector contains duplicate K values, then throw an error, but downside to this is configs look more messy, and it's harder to understand.
`map [ [1, a], [1, b] ]`

**Comment by leifwickland** [comment]
Unfortunately, there's not a way to do this. The resolution of the config
files to a "map of maps"-like memory structure is performed by
typesafe-config. It doesn't have an option to indicate failure in these
cases.

**Comment by ruippeixotog** [comment]
In addition to what @leifwickland mentioned, the behavior in the presence of duplicate keys is specified in the [HOCON spec](https://github.com/lightbend/config/blob/main/HOCON.md#duplicate-keys-and-object-merging), which PureConfig follows closely as we rely on Lightbend's library. We don't have plans to change this.
