### ISSUE TITLE
Ambiguous implicit values if defining StringConvert

### ISSUE THREAD

**Issue by coltfred** [pureconfig/pureconfig#16]
If you define a StringConvert for a class which can automatically have a ConfigConvert generated you get an `ambiguous implicit values` error. This is valuable if you're defining simple "value classes" that wrap `String` or `Int`.

For instance adding this test to `PureConfSuite` will demonstrate the error:

```
  case class ConfWithFoo(foo: Foo)

  it should "be able to use a local StringConvert without getting an ImplicitResolutionFailure error" in {
    implicit val custom: StringConvert[Foo] = StringConvert.fromUnsafe(s => Foo(s.toInt), _.i.toString)
    saveAndLoadIsIdentity(ConfWithFoo(Foo(100)))
  }
```

The reported error is:

```
[error] /home/cfrederickson/src/github/pureconfig/src/test/scala/pureconfig/PureconfSuite.scala:238: ambiguous implicit values:
[error]  both method primitiveFieldConvert in object FieldConvert of type [T](implicit strConvert: shapeless.Lazy[pureconfig.StringConvert[T]])pureconfig.FieldConvert[T]
[error]  and method configFieldConvert in object FieldConvert of type [T](implicit confConvert: shapeless.Lazy[pureconfig.ConfigConvert[T]])pureconfig.FieldConvert[T]
[error]  match expected type pureconfig.FieldConvert[PureconfSuite.this.Foo]
[error]   it should "be able to use a local StringConvert without getting an ImplicitResolutionFailure error" in {
```

We can fix this by giving the `StringConvert` a higher implicit priority.

**Comment by coltfred** [comment]
Opened PR as #17.

**Comment by skeet70** [comment]
Just wanted to note that I ran into this same problem trying to write a config that included a password field that hides the value in a single variable (toString on the class just prints PASSWORD). I was too lazy to come up with a solution.

**Comment by melrief** [comment]
@coltfred PR has been merged and 0.1.8 has been released. I had two other reports this week but I had no time to work on it. @coltfred I added you to the list of contributors of the project if you don't mind. Thanks a lot.

**Comment by coltfred** [comment]
Thanks a bunch for the quick turn around. I'll verify the release works and bump the version then close this issue.

**Comment by melrief** [comment]
Version 0.1.8 has been published and it's in maven.

**Comment by coltfred** [comment]
Works great!
