### ISSUE TITLE
Consider reusing loadConfig for loadConfigOrThrow

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#162]
As pointed out by @leifwickland, `loadConfigOrThrow` should use `loadConfig` to avoid code duplication but there are some small issues preventing this. We should investigate the possibility of reusing code.

**Comment by jcazevedo** [comment]
As pointed out in [#161](https://github.com/melrief/pureconfig/pull/161#discussion_r105565741), this looks like an error on my part. We should be able to reuse `loadConfig` on the `loadConfigOrThrow` methods and we should always attempt to create a `ConfigValueLocation` for `improveFailures` when we have access to a `Config` we're trying to derive from.
