### ISSUE TITLE
sealed trait with families and enums

### ISSUE THREAD

**Issue by yanns** [pureconfig/pureconfig#1623]
I was trying to define a config reader for the following sealed trait:
```
sealed trait AuthenticationConfig
case object Disabled extends AuthenticationConfig
final case class Basic(username: String, password: String) extends AuthenticationConfig
final case class ApiKey(apiKey: String) extends AuthenticationConfig
```

It seems that I can create a `ConfigReader[AuthenticationConfig]` if I'm using `case class` or `case object` but not with a mix of both.

**Comment by leifwickland** [comment]
Yann,

If your ADT includes a `case class` and `case object` you'll need to create
a `FieldCoproductHint` as described on this page
<https://pureconfig.github.io/docs/overriding-behavior-for-sealed-families.html>
or allow it to be automatically created by full-auto. That means by default
your config reader would look for `type` to specify which member of the ADT
is being loaded. For example, your config from above might look like:

{
  auth-conf1 = { type = basic, username=jim, password=secret }
  auth-conf2 = { type = disabled }
  // etc
}

Does that help?

**Comment by leifwickland** [comment]
Yann,

If your ADT includes a `case class` and `case object` you'll need to create
a `FieldCoproductHint` as described on [this page](https://pureconfig.github.io/docs/overriding-behavior-for-sealed-families.html)
or allow it to be automatically created by full-auto. That means by default
your config reader would look for `type` to specify which member of the ADT
is being loaded. For example, your config from above might look like:

```
{
  auth-conf1 = { type = basic, username=jim, password=secret }
  auth-conf2 = { type = disabled }
  // etc
}
```

Does that help?

**Comment by yanns** [comment]
Thanks, I was already using a `FieldCoproductHint`.
I've found that I need to add `import pureconfig.generic.auto._`.
This works:
```
  import pureconfig._
  import pureconfig.generic.FieldCoproductHint
  import pureconfig.generic.auto._
  import pureconfig.generic.semiauto._
  implicit val authenticationConfHint: FieldCoproductHint[AuthenticationConfig] =
    new FieldCoproductHint[AuthenticationConfig]("mode")
  implicit val config: ConfigReader[AuthenticationConfig] = deriveReader[AuthenticationConfig]
```

Thanks for the help!
