### ISSUE TITLE
Usage question: Loading into case class without derive in Scala 3

### ISSUE THREAD

**Issue by nemoo** [pureconfig/pureconfig#1648]
This is a usage question.
I do not want to modify the original case class with derive, so I am trying to get pureconfig to work in Scala 3 just like in the documentation of the main README like this: 
```

//> using dep com.github.pureconfig::pureconfig-core:0.17.6
//> using resourceDir ./resources

import pureconfig._
import pureconfig.generic.derivation.default._


case class Port(number: Int) extends AnyVal

sealed trait AuthMethod
case class Login(username: String, password: String) extends AuthMethod
case class Token(token: String) extends AuthMethod
case class PrivateKey(pkFile: java.io.File) extends AuthMethod

case class ServiceConf(
  host: String,
  port: Port,
  useHttps: Boolean,
  authMethods: List[AuthMethod]
)


@main 
def main = 
    val res = ConfigSource.default.load[ServiceConf]
    println(res)

```

That produces this error: 
```
[error] No given instance of type pureconfig.ConfigReader[ServiceConf] was found for parameter reader of method load in trait ConfigSource.
[error] I found:
[error]
[error]     pureconfig.ConfigReader.exportedReader[ServiceConf](
[error]       /* missing */summon[pureconfig.Exported[pureconfig.ConfigReader[ServiceConf]]]
```
What am I doing wrong?

**Comment by grzegorz-bielski** [comment]
Hello @nemoo!

There are two issues here.

First, you need to actually trigger the derivation for `ServiceConf` and `AuthMethod`. There is no auto derivation in Scala 3.
With the derivation from `pureconfig-core` it could be done as:

```scala
case class ServiceConf(
  host: String,
  port: Port,
  useHttps: Boolean,
  authMethods: List[AuthMethod]
) derives ConfigReader
```
or
```scala
given ConfigReader[ServiceConf] = ConfigReader.derived[ServiceConf]
```
You should do the same for `AuthMethod`.

Second problem is that currently PureConfig doesn't support value class derivation in Scala 3, but you can define your own instance like this:
```scala
given ConfigReader[Port] = ConfigReader.fromStringTry(str => scala.util.Try(str.toInt)).map(Port.apply)
```

**Comment by rladstaetter** [comment]
Thanks  @grzegorz-bielski for this, and also your work and time you are investing in this great library recently.

I'm trying to use pureconfig in my project with scala3, but unfortunately I didn't yet find out how to create ConfigWriters. Can you provide an example for those classes mentioned above as well? 

I would be happy to create them manually without derivation, but I'm lost and unsure what is the way to go.

**Comment by grzegorz-bielski** [comment]
@rladstaetter Thanks!

As you know, the derivation for Scala 3 `ConfigWriter`s is [not yet merged](https://github.com/pureconfig/pureconfig/pull/1653).

In the meantime you can create your own writers manually through combination of factory methods on `ConfigWriter` and `ConfigValueFactory` like this:
```scala
import pureconfig.*
import com.typesafe.config.{ConfigValue, ConfigValueFactory}
import scala.jdk.CollectionConverters.*

case class Foo(bar: String, baz: Int)

given fooWriter: ConfigWriter[Foo] = ConfigWriter.fromFunction: foo => 
  ConfigValueFactory.fromMap(
    Map(
      "bar" -> foo.bar,
      "baz" -> foo.baz
    ).asJava
  )

println(
  fooWriter.to(Foo(bar = "bar", baz = 1)).render()
)
```

**Comment by nemoo** [comment]
@grzegorz-bielski thanks a lot, that works fine! Will definitely check back in on pureconfig once full scala 3 support has landed. 

Some impressions: I found the documentation hard to digest for newcomers, especially to get started quickly. As an inspiration: I find lihaoyi documentations like this one https://github.com/com-lihaoyi/requests-scala great because they offer ready to use relevant use case examples right on the main README.
