### ISSUE TITLE
How can I use camel case for scala3?

### ISSUE THREAD

**Issue by Elvis5566** [pureconfig/pureconfig#1679]
I currently only have a dependency to pureconfig-core for scala3, and cannot access ProductHint.
Can we have a way to configure camal case via pureconfig-core?

Thanks

**Comment by Elvis5566** [comment]
I figured I should use
`"com.github.pureconfig" %% "pureconfig-generic-scala3" % "0.17.7"`

**Comment by chenjianjx** [comment]
Just for people who needs to know how exactly to do it: 
```scala
import pureconfig.generic.*
import pureconfig.generic.semiauto.*
import pureconfig.*

...

given [T]: ProductHint[T] = ProductHint(ConfigFieldMapping(CamelCase, CamelCase))
given ConfigReader[MyConf] = deriveReader

...
```

And the following line is used to help people find this page through google: 

```
How can I use camel case for scala3?  
```
(the title of this issue says cam**a**l)
