### ISSUE TITLE
allowUnknownKeys=false as default

### ISSUE THREAD

**Issue by gabrieljones** [pureconfig/pureconfig#1695]
How do I make allowUnknownKeys=false the default?
I'd like to just declare it once instead of sprinkling it throughout the object graph.

**Comment by ruippeixotog** [comment]
Hi @gabrieljones, the easiest solution is to create an object containing an implicit def for your new hint:

```scala
object MyDefaults {
  implicit def productHint[A]: ProductHint[A] = ProductHint(allowUnknownKeys = false)
}
```

And import it wherever you use PureConfig. I'm afraid you can't avoid having to import it.

**Comment by gabrieljones** [comment]
For anyone arriving from the future, be sure to 
```
import MyDefaults._
```

Simply importing `MyDefaults` without the underscore will not work.
