### ISSUE TITLE
Kebab naming for case classes with numbers in names

### ISSUE THREAD

**Issue by tashoyan** [pureconfig/pureconfig#1746]
When a case class has a number in its name, then Pureconfig expects strange keys in the configuration file.

Example 1: case class `S3`. Pureconfig expects a key `s-3` instead of `s3`.

Example 2: case class `M2m`. Pureconfig expects a key `m-2m` instead of `m2m`.

This is not what could be expected intuitively. I did not find a way to easily customise this behaviour.

**Comment by leifwickland** [comment]
@tashoyan While annoying, this is expected behavior. Here's an older example of how to work around it.
https://github.com/pureconfig/pureconfig/issues/313
