### ISSUE TITLE
pureconfig account

### ISSUE THREAD

**Issue by ghost** [pureconfig/pureconfig#187]
It has come to my attention that your project existed before our own pureconfig (github.com/pureconfig/pureconfig)

Please let me know if this is causing you problems and I'll work out a solution.

**Comment by melrief** [comment]
Thanks for contacting us! Our plan was to move pureconfig from being a personal project to pureconfig/pureconfig and we were surprised when we saw that the organization name was already taken. That's when we discovered your project. We have considered changing the name of our project but pureconfig is used on a daily basis and changing the name at this point is not an option.

Do you think there is the possibility for us to get the account pureconfig? It would help our project a lot.

**Comment by ghost** [comment]
@melrief pureconfig is available. Hurry up before someone else takes it (if so, contact GitHub immediately with a link to this comment, and I'm sure they'll help)

There's a few links from npm, etc, to pureconfig, but I'll ask everyone to fix their links.

Good luck :)

**Comment by melrief** [comment]
Done, thanks!

**Comment by derekmorr** [comment]
Since we moved the repo, we should merge #189 to update metadata for the project.
