### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by dansouza** [pureconfig/pureconfig#2]
Looks pretty good!

My two cents:

1) make the commas optional (or remove them completely) from lists like these, since indentation should be enough to tell different items apart (and you don't risk repeating the "forgotten comma" issue of JSON)
```
servers = 
[
    app-1
        host = 1.2.3.4
        port = 8443
        datadir = ./data
    ,
    app-2 => servers.app-1
       host = 1.2.3.5
    ,
    dbserver
       host = 1.2.3.6
       port = 9931
]
```

2) include statements should support globs so one can do something like `%include conf.d/*.conf`

**Comment by pureconfig** [comment]
I agree with both points. Thanks!

**Comment by shelbyd** [comment]
Closing since we agree on the first suggestion, and the second suggesting is being discussed in a separate issue, #14.
