### ISSUE TITLE
string parameter for start of config path

### ISSUE THREAD

**Issue by fommil** [pureconfig/pureconfig#2]
I don't always want to model the entire config, just some subtree of it (typically my app's bits), can you please add a `String` parameter like ficus to set the root?

**Comment by melrief** [comment]
Done with 0d95340. You can see the new [loadConfig](https://github.com/melrief/pureconfig/blob/master/src/main/scala/pureconfig/package.scala#L37) with the namespace parameter. There is also a [new test](https://github.com/melrief/pureconfig/blob/master/src/test/scala/pureconfig/PureconfSuite.scala#L64) that shows this functionality.

Let me know what do you think and then, if it satisfies you, we can close this.

p.s. I will publish the artifacts as soon as you tell me this is ok :-)

**Comment by fommil** [comment]
if you've implemented, then good to close :-D I'll raise a bug if it doesn't work the way I expect. Thanks for the fast responses! It opens it up for me to try this out on my work projects on Tuesday.

**Comment by melrief** [comment]
FYI version 0.1.2 with this changes published to maven.
