### ISSUE TITLE
Custom key name

### ISSUE THREAD

**Issue by david-bouyssie** [pureconfig/pureconfig#204]
If I understood correctly what is described din the field-mappings page (https://github.com/pureconfig/pureconfig/blob/master/docs/override-behaviour-for-case-classes.md#field-mappings), pureconfig allows to define a mapping between a key naming convention and another one for Scala fields.

However what it if keys are named with a mixed naming convention ?
I think it could be nice to annotate case class fields to provide a specific key name like:
```scala
case class Dummy(
  @TypeSafeConfigKey("bla_bla") blaBla: Foo,
  @TypeSafeConfigKey("yo-yo") yoYo: Bar
)
```

Thanks!

**Comment by jcazevedo** [comment]
I don't like annotating domain classes with (de)serialization information as I think it pollutes the model with unrelated logic.

It is possible to do what you want by defining a custom `ProductHint` for the desired types:

```scala
case class Dummy(blaBla: Int, yoYo: Int)

class CustomProductHint[T](mappings: Map[String, String]) extends ProductHint[T] {
  private val default = ProductHint.default[T]
  def configKey(fieldName: String) = mappings.getOrElse(fieldName, default.configKey(fieldName))
  def useDefaultArgs = default.useDefaultArgs
  def allowUnknownKeys = default.allowUnknownKeys
}

implicit val ph = new CustomProductHint[Dummy](Map("blaBla" -> "bla_bla", "yoYo" -> "yo-yo"))

Dummy(1, 2).toConfig
// returns SimpleConfigObject({"bla_bla":1,"yo-yo":2})
```

Nonetheless, I think we can consider adding helpers to create a `ProductHint` from a map of field names to typesafe config keys, as it is a common use case.

**Comment by david-bouyssie** [comment]
Very nice and unobtrusive solution!

Thanks ;-)

**Comment by melrief** [comment]
@jcazevedo the idea of adding helpers is not bad at all, it could be used for special cases where the user needs to control field mapping. Do we want to create an issue for this?

**Comment by ruippeixotog** [comment]
I have just opened #256 and I'm going to take care of it in the next days :)
