### ISSUE TITLE
Support java.time.Duration

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#210]

**Comment by rberenguel** [comment]
Quick question before I try to dig deeper (which probably will not be today), this should be part of the core (might make sense) or a separate module (could also make sense actually)?

**Comment by melrief** [comment]
Of the core. `java.time` is fully supported in core except for this class.

**Comment by derekmorr** [comment]
This was addressed by #217.

**Comment by AceHack** [comment]
What is the syntax in the config?

**Comment by leifwickland** [comment]
@AceHack,
The [`ConfigReader` for Java's `Duration`](https://github.com/pureconfig/pureconfig/blob/577910f117ffdbc51c6000eea043eade203d7f0c/core/src/main/scala/pureconfig/BasicReaders.scala#L113) calls [Duration.parse](
https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-), which is what defines the syntax.

**Comment by leifwickland** [comment]
@AceHack, 

That fact is probably not documented nicely anywhere. Do you have any suggestions for where it should've been documented based on where you looked for it?

Thanks.
