### ISSUE TITLE
pureconfig file extension

### ISSUE THREAD

**Issue by kootenpv** [pureconfig/pureconfig#22]
I'm wondering what is the proposed file extension for pureconfig files? I think it would be powerful to communicate we're dealing with pureconfig by using a specific extension.

- .pconf 
- .pure
- .pc
- .puco

Maybe we could vote? I think `.pconf` would be the clearest.

**Comment by pureconfig** [comment]
I like *pconf*, but unfortunately it clashes with https://www.npmjs.com/package/pconf

Personally, I prefer .pure and we already have a few tests called that. It also names the format directly.

**Comment by pureconfig** [comment]
.pure it is
