### ISSUE TITLE
UTF-8 encoding

### ISSUE THREAD

**Issue by pureconfig** [pureconfig/pureconfig#23]
The spec now makes it clear that pure file are utf8 (thus also accepting ASCII)

We need to define a couple of things regarding Unicode:

* What do we consider a whitespace? I guess https://en.wikipedia.org/wiki/Whitespace_character#Unicode makes that pretty clear. That said, a prototype parser should be fine accepting the usual space+\n\r\t\f\v
* Do we accept non-ASCII characters in keys? I'm dubious, since it will become harder to consume a property file in different languages (not all languages makes it easy to specify utf8 literals)

**Comment by Phlosioneer** [comment]
Keys are defined by the application. The application will only define utf8 keys if it can easily work with them, so I think this is a non-issue.

**Comment by pureconfig** [comment]
@Phlosioneer I agree. My thinking was this: There may be cases where Pure files may be read by external systems (esp true when someone inevitably uses Pure as a serialization target), but after some  thinking, I'm in the screw-runtimes-who-cannot-read-utf8 camp.

**Comment by Phlosioneer** [comment]
Also consider that disallowing utf8 in key names excludes many languages from writing localized key names. This isn't really an issue when programming, but for the average user I'm sure they would expect to be able to use their normal keyboard.

**Comment by pureconfig** [comment]
@Phlosioneer Yes, I've concluded that utf8 keys should be allowed.
