### ISSUE TITLE
Support QuantityRange in squants module

### ISSUE THREAD

**Issue by derekmorr** [pureconfig/pureconfig#234]
Squants has a custom `Range` implementation for units, [QuantityRange](https://oss.sonatype.org/service/local/repositories/releases/archive/org/typelevel/squants_2.11/1.2.0/squants_2.11-1.2.0-javadoc.jar/!/index.html#squants.QuantityRange). It would be nice to support this (I personally have a need for it in a work project).

I'm thinking that we can parse a two-element list from HOCON into a QuantityRange. E.g.:
```
{ sizes: [ "10 gib", "500 gib" ] }
```

into: `QuantityRange(10.gib, 500.gib)`

What do people this of this approach?

**Comment by leifwickland** [comment]
@derekmorr,
I would naively expect that you'd handle this by writing a config like:
```
{ sizes: { lower: "10 gib", upper: "500 gib" } }
```
Are you considering the list just for conciseness?

If you represented it with `lower` and `upper` would PureConfig just work it out or would it need something additional to help assure it that that `ConfigConvert` existed for `QuantityRange`'s `[A]`?

Sorry if my questions are painfully naive.

**Comment by derekmorr** [comment]
You're right. For some reason I was thinking `QuantityRange` wasn't a case class. I'll close this.

**Comment by derekmorr** [comment]
Hmm, I spoke too soon. Looks like pureconfig is trying to parse the strings as ints:

```scala
scala> import squants.QuantityRange
import squants.QuantityRange

scala> import squants.information.Information
import squants.information.Information

scala> case class Config(range: QuantityRange[Information])
defined class Config

scala> import pureconfig.module.squants._
import pureconfig.module.squants._

scala> import com.typesafe.config.ConfigFactory.parseString
import com.typesafe.config.ConfigFactory.parseString

scala> import pureconfig.syntax._
import pureconfig.syntax._

scala> val c = parseString("""{ range: { lower: "10 GiB", upper: "500 GiB" } }""")
c: com.typesafe.config.Config = Config(SimpleConfigObject({"range":{"lower":"10 GiB","upper":"500 GiB"}}))

scala> c.to[Config]
res1: Either[pureconfig.error.ConfigReaderFailures,Config] = Left(ConfigReaderFailures(CannotConvert(upper,Int,To convert an object to a collection, its keys must be read as Int but key upper has valueQuoted("500 GiB") which cannot converted. Error: java.lang.NumberFormatException: For input string: "upper",None,Some(range.upper)),List(CannotConvert(lower,Int,To convert an object to a collection, its keys must be read as Int but key lower has valueQuoted("10 GiB") which cannot converted. Error: java.lang.NumberFormatException: For input string: "lower",None,Some(range.lower)))))
```

**Comment by jcazevedo** [comment]
@derekmorr: I've just tried your example with the `master` branch, and it seems to work as expected:

```scala
scala> val c = parseString("""{ range: { lower: "10 GiB", upper: "500 GiB" } }""")
c: com.typesafe.config.Config = Config(SimpleConfigObject({"range":{"lower":"10 GiB","upper":"500 GiB"}}))

scala> c.to[Config]
res0: Either[pureconfig.error.ConfigReaderFailures,Config] = Right(Config(QuantityRange(10.0 GiB,500.0 GiB)))
```

**Comment by jcazevedo** [comment]
The failure you're getting is only raised when we attempt to derive a traversable from a `ConfigObject`, in which case we assume the object must contain integer keys. I find it weird for that failure to be raised in that situation.

**Comment by derekmorr** [comment]
Ah, you're right. My apologies. I had some in-progress changes that caused the failure. I guess I haven't' had enough coffee today. Sorry for the spurious bug. I'll close this again.
