### ISSUE TITLE
CamelCase is converted to lowercase with hiphen

### ISSUE THREAD

**Issue by pawanlamba** [pureconfig/pureconfig#239]
In the example mentioned on website If I change one of the variables as camelCase its not supported.
Versions:
Scala : 2.11.9
PureConfig: 0.7.0

sealed trait MyAdt
case class AdtA(a: String) extends MyAdt
case class AdtB(b: Int) extends MyAdt
case class Port(value: Int) extends AnyVal
case class MyClass(
  boolean: Boolean,
  port: Port,
  adtTrue: MyAdt,
  list: List[Double],
  map: Map[String, String],
  option: Option[String])

val conf = parseString("""{ 
  "boolean": true,
  "port": 8080, 
  "adtTrue": { 
    "type": "adtb", 
    "b": 1 
  }, 
  "list": ["1", "20.0"], 
  "map": { "key": "value" } 
}""")

loadConfigOrThrow[MyClass](conf)
Error:
pureconfig.error.ConfigReaderException: Cannot convert configuration to a MyClass. Failures are:
  at '**adt-true**':
    - Key not found.
  at 'port':
    - Expected type OBJECT. Found NUMBER instead.

**Comment by leifwickland** [comment]
@pawanlamba17 
Thanks for giving PureConfig a try.

It appears to me that the behavior you're seeing is what's to be expected.

By default PureConfig uses `kebab-case` for fields in the config. That behavior is [documented here](https://github.com/pureconfig/pureconfig/blob/master/docs/override-behaviour-for-case-classes.md#field-mappings). 

If you'd like to use `camelCase` in your config instead, then you'd a line like the following before you load the config.
```
implicit def hint[T] = ProductHint[T](ConfigFieldMapping(CamelCase, CamelCase))
```

Does this answer your question?

Thanks,

Leif

**Comment by vsuharnikov** [comment]
@leifwickland I tried to migrate a few days ago and gave up. We have a huge configuration and we have been using `pureconfig` since `0.3.3`. Thus, to migrate I have to write hints for each of 50+ classes if I understood right.

If that is true, is there a way to make a default naming configurable? For example, by using [system properties](https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html) or by tweaking a default configuration in `application.conf` (like an Akka's configuration) or something else? I could try create a PR for it or prepare a proposal.

**Comment by leifwickland** [comment]
@vsuharnikov 
Adding the following line before you call `loadConfig` should change the default mapping for all types.
```
implicit def hint[T] = ProductHint[T](ConfigFieldMapping(CamelCase, CamelCase))
```

Is that not the behavior you're seeing?

**Comment by ruippeixotog** [comment]
I'll just add that alternatively, you can create that `hint` in one Scala `object` and just import it in the files in which you load configs.

**Comment by vsuharnikov** [comment]
@leifwickland @ruippeixotog It's obvious, I do not know why I did not understand it earlier. So i feel very stupid :D

Thank you guys for this great library!

**Comment by leifwickland** [comment]
@vsuharnikov I'm glad it worked out. Thanks for using PureConfig.

**Comment by dr-lab** [comment]
Put into a scala package class seems works for all within that package and not need to change 50+class.
implicit def hint[T] = ProductHint[T](ConfigFieldMapping(CamelCase, CamelCase))
configLoader.load(..)
