### ISSUE TITLE
Pureconfig & spark & maven (shade plugin)

### ISSUE THREAD

**Issue by jukiewiczm** [pureconfig/pureconfig#267]
Hello,
I am trying to use pureconfig together with spark (spark submit). Basically, my question is described here https://stackoverflow.com/questions/44658970/spark-with-pureconfig-proper-maven-shade-plugin-configuration 
I can see there's a nice section in your README on how to handle this with sbt. Would you be so kind and provide guidance on how to handle this with maven? I'm having trouble working this out.

Many thanks

**Comment by leifwickland** [comment]
@jukiewiczm Thanks for using PureConfig. 

I believe you could create a private copy of shapeless in a maven project using either [JarJar Maven](https://sonatype.github.io/jarjar-maven-plugin/) or the [class relocation feature of Maven Shade](https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html). 

Please let me know how it goes. 

Thanks,

Leif

**Comment by jukiewiczm** [comment]
@leifwickland thank you for the answer
The relocation package is what I've been actually trying to use, but unfortunately I wasn't able to get it to work. The simple relocation of the shapeless does not seem to help unfortunately.

Edit: What I am actually failing to do is probably changing the dependency name in the pureconfig library itself. It seems I don't know how to specify sbt's `inLibrary` option equivalent in maven.

**Comment by jukiewiczm** [comment]
I solved my own issue, it turned out I was using shade plugin improperly (used wrong package pattern).
Check https://stackoverflow.com/a/44670856/2807379 to see how it works.
Thanks for the help and thanks for creating PureConfig!
