### ISSUE TITLE
Use ConfigList by default when reading and writing Scala tuples

### ISSUE THREAD

**Issue by jcazevedo** [pureconfig/pureconfig#274]
Scala tuples currently get serialized as `ConfigObject`s with keys `_1`, `_2`, etc. Even though I think we should still support reading from this format, I think it's more natural for tuples to be serialized as lists (and consequently `ConfigReader`s for tuples should be able to read from lists).

**Comment by leifwickland** [comment]
I think this sounds like a good idea.

**Comment by ruippeixotog** [comment]
I also agree. As a user, the most natural representation of a tuple in a config for me would be an array...

**Comment by melrief** [comment]
I think it's a good idea too, just keep in mind this is a breaking change.
