### ISSUE TITLE
release tags missing

### ISSUE THREAD

**Issue by francisdb** [pureconfig/pureconfig#285]
https://github.com/pureconfig/pureconfig/tags

they stop at 0.6.0 but the changelog talks about 0.7.2

**Comment by ruippeixotog** [comment]
Hi @francisdb. The tags all exist, but they are at the end of that list: https://github.com/pureconfig/pureconfig/tags?after=v0.1.2. We retroactively tagged old versions recently, and I think GitHub doesn't allow us to order them alphabetically...

**Comment by francisdb** [comment]
I see, should fix itself with the next release then.

**Comment by jcazevedo** [comment]
I'm not sure if we want to do it, but it's possible to alter the date of the tags to match the date of the commit they're associated with.

**Comment by ruippeixotog** [comment]
I didn't know tags had an associated date in git, I thought it was only a GitHub thing. If that's possible I think it would be nice to do it :)

**Comment by jcazevedo** [comment]
I've updated the tags' dates to match the associated commit date, so the GitHub ordering should be fixed now.

**Comment by francisdb** [comment]
👌
