### ISSUE TITLE
Release 0.8

### ISSUE THREAD

**Issue by derekmorr** [pureconfig/pureconfig#286]
There have been a significant number of changes since 0.7.2 in May 2017. These include #282, #275, #264, #262 which change default behavior and restructure internals. We should release a new version of PureConfig and increment the version number to indicate that we're breaking compatibility.

**Comment by timothyklim** [comment]
@jcazevedo @ruippeixotog Is there any plans to release?

**Comment by melrief** [comment]
I've created a milestone for [`0.8.0`](https://github.com/pureconfig/pureconfig/milestone/6). @TimothyKlim there is still some work that we would like to do before the next release. Version `0.8.0` will probably be released in one or two weeks.

**Comment by timothyklim** [comment]
Thanks!
