### ISSUE TITLE
add link to javadoc in readme

### ISSUE THREAD

**Issue by derekmorr** [pureconfig/pureconfig#290]
If we publish scaladoc jar files, we can link to them on javadoc.io as an easy way to get the docs online.

From their readme:

> Simply add a link to javadoc.io/doc/{org}/{artifact} to your project's page to provide an always up-to-date link to your project's javadoc.
> New releases will be automatically picked up within 24 hours.
> Supports Java/Scala/Groovy/other projects.
> You can also add links to specific releases of your project: javadoc.io/doc/{org}/{artifact}/{version}

**Comment by ruippeixotog** [comment]
Looking at http://central.maven.org/maven2/com/github/melrief/pureconfig_2.12/0.7.0, it seems that we already publishing javadoc JARs, isn't it? I believe it is also SBT's default.
