### ISSUE TITLE
Can we mention pureconfig in cats' README? 

### ISSUE THREAD

**Issue by kailuowang** [pureconfig/pureconfig#298]
in the list of cats ecosystem projects.

**Comment by ruippeixotog** [comment]
Hi @kailuowang, I'm totally ok with it.

I believe @melrief, @leifwickland, @jcazevedo and @derekmorr won't have a problem with it either, but let's wait for a response from them.

**Comment by leifwickland** [comment]
Fine by me. It's a bit odd as PureConfig attempts to support Cats, rather than consume Cats for the purpose of using its features. It's a pedantic difference that only I'll ever notice probably.

**Comment by jcazevedo** [comment]
I'm also ok with it.

**Comment by melrief** [comment]
I'm ok with it

**Comment by melrief** [comment]
@derekmorr what do you think about it?

**Comment by derekmorr** [comment]
That's fine with me.

**Comment by melrief** [comment]
@kailuowang then the answer is yes :). I'll close this.
