### ISSUE TITLE
Clarify escaping characters

### ISSUE THREAD

**Issue by jsejcksn** [pureconfig/pureconfig#3]
_For example:_ What if I want to use a quoted string as my value? Do I need to put it inside the other kind of quotes? Will I use backslashes?

**Comment by pureconfig** [comment]
> Will I use backslashes?

Probably, thinking about these details now.

**Comment by pureconfig** [comment]
Let's go for backslash to escape. We should also use this to allow leading whitespaces, exactly like Java property files allow:

    something = \ \ \ \ this line, when read by the parser, will have four leading spaces

    quoted = \"This string will actually have quotes\"

I've updated the README

**Comment by jsejcksn** [comment]
So, just to clarify:

```
something = "    \"this line, when read by the parser, will also have four leading spaces, then a sentence inside quotes?\""
```

and

```
anotherThing = The only way to get an actual backslash is to precede it by a backslash, like so: //?
```

If true, you should add the bit about backslashes in the README, too.

**Comment by pureconfig** [comment]
@jsejcksn Exactly, I'll update the README
