### ISSUE TITLE
Support for Scala 2.10 is not correctly documented

### ISSUE THREAD

**Issue by zsolt-donca** [pureconfig/pureconfig#30]
By looking at [pureconfig's releases for Scala 2.10 on maven central](http://mvnrepository.com/artifact/com.github.melrief/pureconfig_2.10), it seems that `0.1.9` was the last release for Scala 2.10. In contrast, for Scala 2.11, the versions `0.2.0` and `0.2.1` [were also released](http://mvnrepository.com/artifact/com.github.melrief/pureconfig_2.11).

However, pureconfig's main documentation gives the impression that the latest `0.2.1` release is also supported for `2.11`, and, even has an non-working example:

```
libraryDependencies ++= Seq(
  "com.github.melrief" %% "pureconfig" % "0.2.2",
compilerPlugin("org.scalamacros" % "paradise" % "2.0.1" cross CrossVersion.full)
)
```

This made me wonder for about a minute on why can't my dependencies be resolved (I am bound to Scala 2.11 because of a dependency to the Spark 1.6 line).

Either the documentation needs to be fixed, or the `0.2.x` line needs to be released for Scala 2.10.

**Comment by melrief** [comment]
My mistake, I forgot to publish the artifact for Scala 2.10. I published `0.2.2` right now and it will be available in the next minutes.
