### ISSUE TITLE
Other configuration format?

### ISSUE THREAD

**Issue by tredoe** [pureconfig/pureconfig#30]
Why other configuration format? Does TOML is not enough?

**Comment by Phlosioneer** [comment]
Couple options here.

1) Fix your grammar so that we can understand what you're saying.
2) Explain why you think TOML is better.
3) Explain why the main purpose of pure config (human readability) is better done in another format.

If you don't do one of the above, I'm just going to close this as off-topic.

**Comment by tredoe** [comment]
> 1. Fix your grammar so that we can understand what you're saying.
My native language is not English.

> 2. Explain why you think TOML is better.
Explain why you think Pure config is going to be better.

> 3. Explain why the main purpose of pure config (human readability) is better done in another format.
Explain why the human readability is going to be better done in Pure. config

**Comment by Phlosioneer** [comment]
>My native language is not English.

My apologies, then.

> Explain why you think Pure config is going to be better.
>Explain why the human readability is going to be better done in Pure config.

That's what the readme does. If you don't like pure config, you can move on. You don't have to pay attention to this repo.

**Comment by tredoe** [comment]
> Explain why you think Pure config is going to be better.
> Explain why the human readability is going to be better done in Pure config.
>> That's what the readme does. 

The Readme says:
> Pure is a specification for a configuration file format. Its goal is to suck less than other configuration file formats.

So, the Readme does not explain none of the questions above, besides that to say "to suck less than other configuration file formats" does not looks a technical explication.

**Comment by tredoe** [comment]
By the way, good luck with the project but especially with the community.

**Comment by Phlosioneer** [comment]
> To learn about why Pure exists, see https://github.com/pureconfig/pureconfig/wiki/Rationale

There's a long, detailed page about the motivation of pure. Its focus is on ease of use by non-technical users, to make tech support easier and to make user customization of settings easier. It's also possibly useful as a basis for a game, to make modding the game via config files much easier for the average player.
