### ISSUE TITLE
disable automatic derivation

### ISSUE THREAD

**Issue by fommil** [pureconfig/pureconfig#304]
My team prefers semi-auto derivation as per https://github.com/fommil/stalactite

It would be great if you followed the pattern for derivation laid out in https://github.com/milessabin/export-hook to

1. avoid lots of corner cases you may not have considered
2. allow users to opt-in to full generic derivation

thanks for a great library!

**Comment by nigredo-tori** [comment]
I agree, somewhat. Automatic derivation makes the field names etc. part of the API, which is not ideal. My team uses the explicit approach in similar cases (JSON codecs, etc.) - any encoding should be performed by an explicitly specified codec, and missing codec should cause a compilation error. Thus we need an option to disable automatic derivation entirely.

One way to achieve that (which is what `circe` project does) would be to remove `DerivedReaders`/`DerivedWriters` from `ConfigReader`/`ConfigWriter` objects, and make them accessible through an explicit import of some package object. We can even move those to a separate module, getting rid of the `shapeless` dependency in `core`. This would make this library a lot more flexible, at the cost of adding an import to the existing code.

**Comment by fommil** [comment]
I'm no longer interested in scala.
