### ISSUE TITLE
Introduce ScalaCheck for tests

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#31]
Current tests for `pureconfig` instances should be tested using ScalaCheck and random values.

**Comment by p16i** [comment]
@melrief Could you please explain a bit more what you plan to do?

**Comment by melrief** [comment]
In the [current tests suite](https://github.com/melrief/pureconfig/blob/master/src/test/scala/pureconfig/PureconfSuite.scala) we create some custom "config" classes, such as [`FlatConfig`](https://github.com/melrief/pureconfig/blob/bb66e1e06783c2b3418162e76abbbe0409ed5820/src/test/scala/pureconfig/PureconfSuite.scala#L54), as example of configuration classes. To test that `pureconfig` works, we create an instance of those classes with some values, like `FlatConfig(false, 1d, 2f, 3, 4l, "5", Option("6"))`, and then we check if writing to file and reading from file is [equal to the identity](https://github.com/melrief/pureconfig/blob/bb66e1e06783c2b3418162e76abbbe0409ed5820/src/test/scala/pureconfig/PureconfSuite.scala#L62). Those tests are very simplistic in the sense that they test only one value.
The idea of this issue is to create `Arbitrary` instances for those classes and then test random values instead of only one value. Basically we would like to have the test:

``` scala
"pureconfig" should s"be able to save and load ${classOf[FlatConfig]}" in {
  withTempFile { configFile =>
    val expectedConfig = FlatConfig(false, 1d, 2f, 3, 4l, "5", Option("6"))
    saveConfigAsPropertyFile(expectedConfig, configFile, overrideOutputPath = true)
    val config = loadConfig[FlatConfig](configFile)

    config should be(Success(expectedConfig))
  }
}
```

rewritten as

``` scala
"pureconfig" should s"be able to save and load ${classOf[FlatConfig]}" in forAll {
  (expectedConfig: FlatConfig) =>
    withTempFile { configFile =>
      saveConfigAsPropertyFile(expectedConfig, configFile, overrideOutputPath = true)
      val config = loadConfig[FlatConfig](configFile)

      config should be(Success(expectedConfig))
    }
}
```

which would test more values and edge cases and give us some confidence in our codecs implementations.

Note that most of the tests can be rewritten with a ScalaCheck style, not only the one writing to file. For instance, one could test if encoding to and decoding from `ConfigValue` a type `T` is equivalent to the identity function.

As final note, there are already libraries (based on shapeless of course) that create `Arbitrary` instances for classes such as [scalacheck-shapeless](https://github.com/alexarchambault/scalacheck-shapeless) which could help.

Let me know if this helps.

**Comment by p16i** [comment]
yep, it does. I can take a look at this issue and will ask you again if I face any issue.

**Comment by p16i** [comment]
@melrief I just refactored testing FlatConfig to property-based. For other tests, I'm not sure whether we should refactor them all or  just do it for important ones.

What do you think?

**Comment by melrief** [comment]
@heytitle thanks for the patch, I've used scalachecks for some other tests about `java.time`. I'll close this and open new ones about existing tests not yet under scalacheck.
