### ISSUE TITLE
Mark Field As Sensitive

### ISSUE THREAD

**Issue by vratnagiri** [pureconfig/pureconfig#310]
Would it be possible to add a feature whereby a property could be marked sensitive (in the case class definition) so that it will never be printed out if someone were to do something like:

    val configWithPassword =  loadConfigOrThrow[SyncConfig]("namespace")
    logger.info(s"Using configuration :\n${configWithPassword.toString}")

Thank you!

**Comment by leifwickland** [comment]
I don't think that there's any way that PureConfig can help you with that because the `toString` behavior is based on the class you write to receive config from PureConfig.

In my code at $work, I have a similar problem where I want to accept the password for a database, but never want it to be printed. I created a class like this:

```
/**
 * Designed specifically to prevent scala's magic from printing passwords to the logs.
 */
final case class Password(value: String) extends AnyVal {
  override def toString: String = "PASSWORD"
}

object Password {
  final implicit val PasswordConfigConvert: ConfigConvert[Password] = ConfigConvert.fromString[Password](Password(_)) // I believe you'd call `ConfigReader.fromString` in the current version of PureConfig instead.
}
```

There might be a cleverer approach, but this is what I've done in the past.

**Comment by vratnagiri** [comment]
Thanks! I'll use that approach.

**Comment by ruippeixotog** [comment]
@leifwickland clever solution, it's a really easy way to override `toString` just for one field!

I'll just add that on recent pureconfig versions the custom `ConfigConvert` is not needed, as long as the case class extends `AnyVal`:

```
scala> import pureconfig.syntax._
import pureconfig.syntax._

scala> final case class Password(value: String) extends AnyVal {
     |   override def toString: String = "PASSWORD"
     | }
defined class Password

scala> Password("12345678").toConfig
res0: com.typesafe.config.ConfigValue = Quoted("12345678")
```

**Comment by derekmorr** [comment]
I wonder if we should update the docs with this use case.

**Comment by leifwickland** [comment]
@derekmorr I sent https://github.com/pureconfig/pureconfig/pull/311 to add a FAQ for this.
