### ISSUE TITLE
Handling options when key exists but has no values

### ISSUE THREAD

**Issue by cornerman** [pureconfig/pureconfig#312]
My use case is to have an optional value in my config:
```
case class EmailConfig(username: String, password: String)
case class Config(email: Option[EmailConfig])
```

With a corresponding application.conf:
```
test {
    email {
        username = ${?SMTP_USER}
        password = ${?SMTP_PASS}
    }
}
```

If the environment variables are defined, everything is great. But if they are not defined, then I get `KeyNotFound`-errors when loading the config:
```
loadConfigOrThrow[Conf]("test")

Caused by: pureconfig.error.ConfigReaderException: Cannot convert configuration to a wust.backend.config.Config. Failures are:
   at 'test.email.address':
     - (file:/tmp/sbttmpfs/sbt_17838ec7/scala-2.12/classes/application.conf:2) Key not found.
   at 'test.email.password':
     - (file:/tmp/sbttmpfs/sbt_17838ec7/scala-2.12/classes/application.conf:2) Key not found.
```

So, the optional evaluates to `None` iff there is no key defined for `email`. I would have expected an empty ConfigObject to behave the same. If there is no key defined within `email`, it should just evaluate to None. Maybe, if only one of them is missing, it should still fail.

I thought, it might help to follow the instuctions [here](https://github.com/pureconfig/pureconfig/blob/master/docs/handling-missing-keys.md), but this did not help me. The only workaround I could come up with, was this:
```
  implicit def optionConfigReader[T](implicit reader: Derivation[ConfigReader[T]]): ConfigReader[Option[T]] =
    new ConfigReader[Option[T]] {
      override def from(config: ConfigValue) = config.to[T] match {
        case Right(config) => Right(Some(config))
        case Left(err) if err.toList.forall {
          case _ :KeyNotFound => true
          case _ => false
        } => Right(None)
        case Left(err) => Left(err)
      }
    }
```

Is there a more elegant way to do this? Do you think, it makes sense to support this use-case or did I overlook something?

**Comment by ruippeixotog** [comment]
Semantically, I think that an empty config object is different from a non-existing or null value. In particular, in types such as `Option[Map[String, A]]` or any `Option[CaseClass]` where all fields of `CaseClass` are optional, an empty config object would be an ambiguous value.

IMO a custom reader for `Option[EmailConfig]`, as you wrote, is the right approach. If you want you can define it as simply as:

```scala
val emailConfigReader = ConfigReader[EmailConfig].contramapConfig {
  case co: ConfigObject if co.isEmpty => null
  case cv => cv
}

customOptionReader[EmailConfig].from(ConfigFactory.parseString("{}").root)
// Either[pureconfig.error.ConfigReaderFailures,Option[EmailConfig]] = Right(None)
```

This maps the config before it reaches the default option reader (given by `ConfigReader[EmailConfig]`) by transforming empty config objects into `null` (as undefined configs are represented).

**Comment by cornerman** [comment]
Thank you for the fast response! I agree with your argument about empty configs in general. Your solution works for me; so I am going to close this one.

**Comment by folex** [comment]
I faced the same problem, and the solution above resulted in a bunch of NPE. So, for anyone searching for solution, here it is:

### For a specific case class

```scala
import com.typesafe.config.{ConfigFactory, ConfigObject}
import pureconfig._
import generic.auto._

case class A(name: String)
case class B(a: Option[A])

val config = ConfigFactory.parseString("{\"a\":{}}")

implicit val reader = ConfigReader.fromCursor[Option[A]] { cv =>
  cv.value match {
    case co: ConfigObject if co.isEmpty => Right(None)
    case _ => ConfigReader[A].from(cv).map(Some(_))
  }
}

loadConfig[B](config)
```

### For all `Option[T]`
```scala
import com.typesafe.config.{ConfigFactory, ConfigObject}
import pureconfig._
import generic.auto._

implicit def reader[T: ConfigReader] = ConfigReader.fromCursor[Option[T]] { cv =>
  cv.value match {
    case co: ConfigObject if co.isEmpty => Right(None)
    case _ => ConfigReader[T].from(cv).map(Some(_))
  }
}
```

Thanks to @ya-goodfella for these pieces of code.

**Comment by aditanase** [comment]
Here's another variant that combines the above solutions and avoids NPEs:

```scala
def reader[T: ConfigReader]: ConfigReader[Option[T]] =
  ConfigReader[Option[T]].contramapConfig {
    case co: ConfigObject if co.isEmpty => ConfigValueFactory.fromAnyRef(null)
    case cv => cv
  }

implicit val emailConfigReader: ConfigReader[Option[EmailConfig]] = reader[EmailConfig]
```
