### ISSUE TITLE
Kebab case parser expects `s-3` for property `s3`

### ISSUE THREAD

**Issue by jlandahl** [pureconfig/pureconfig#313]
When parsing configuration for a case class with a property called `s3`, the default kebab case parser expects the corresponding key in the config file to be `s-3`. This is quite unexpected and forced me to switch to camel case in order to get the desired behavior. The error generated is `KeyNotFound(s-3,None,Set(s3))`.

**Comment by ruippeixotog** [comment]
I believe that the choice of how to deal with numbers in classes was pretty much arbitrary. While in terms such as `S3` the number is a suffix, in other terms such as `3D` (as in `3DPoint` or `Object3D`) it makes more sense otherwise. As such, I think that there will always be the need to add exceptions to such conventions.

While we can think of changing the current parser (I am myself a victim of having too many classes with "S3" in their name), it's very easy to add exceptions to a general naming convention:

```scala
import com.typesafe.config._
import pureconfig._
import pureconfig.syntax._

case class Conf(s3Bucket: String)

implicit val confHint = ProductHint[Conf](
  ConfigFieldMapping(CamelCase, KebabCase).withOverrides("s3Bucket" -> "s3-bucket"))

ConfigFactory.parseString("s3-bucket = mybucket").to[Conf]
// res0: Either[pureconfig.error.ConfigReaderFailures,Conf] = Right(Conf(mybucket))
```

**Comment by hekaldama** [comment]
I see your example, but since I am new, I am still struggling figuring out how to solve the `s3` case in the original comment. Does anyone have any pointers?

**Comment by leifwickland** [comment]
@hekaldama, 

Here's a more detailed example. Please let me know whether this helps.
```
case class Conf(s3: String, s3Bucket: String, s3Url: String, justNormal: String)

implicit val confHint = ProductHint[Conf](
  ConfigFieldMapping(CamelCase, KebabCase).withOverrides(
    "s3Bucket" -> "s3-bucket",
    "s3" -> "s3",
    "s3Url" -> "s3-url"))

ConfigFactory.parseString(
  """s3-bucket = mybucket
    |s3 = aws
    |s3-url = "http://amazon.com"
    |just-normal = NORML""".stripMargin)
  .to[Conf]
// res0: Right(Conf(aws,mybucket,http://amazon.com,NORML))
```

**Comment by hekaldama** [comment]
Helped me arrive at the solution as my `s3` was nested like `aws.s3`. I ended up with something like:
```scala
object withHint {
  implicit val confHint = ProductHint[AwsConfig](
    ConfigFieldMapping(CamelCase, KebabCase).withOverrides("s3" -> "s3"))

  case class AwsConfig(accessKey: Option[String],
                       secretKey: Option[String],
                       s3: Option[S3Config])
}
case class Conf(aws: withHint.AwsConfig)
```
