### ISSUE TITLE
ConfigReadFailures with a certain way of using application.conf

### ISSUE THREAD

**Issue by joesan** [pureconfig/pureconfig#327]
I have an application.conf that looks like this:

```
environment = "default"

# Spark related configuration
# ~~~~~
spark {
  master = "local[*]"
  deployMode = "client"
  driverHost = "localhost"
  driverPort = "9001"
  logLevel = "ERROR"
}
```

So as it can be seen that my application.conf is not a nested structure and I have different sub sections completely un nested. Would pure config be able to load such files? I already tried this and I get failure messages. None of the fields from the application.conf are being read!

So my understanding is that the pur config expects a file like this:

```
app {
  environment = "default"
  spark {
    master = "local[*]"
    deployMode = "client"
    driverHost = "localhost"
    driverPort = "9001"
    logLevel = "ERROR"
  }
}
```

I don't know if that works, will give it a try!

**Comment by jcazevedo** [comment]
> So as it can be seen that my application.conf is not a nested structure and I have different sub sections completely un nested. Would pure config be able to load such files?

It should be able to load such files. I just tried loading your configuration file using the following, and it worked:

```scala
import pureconfig._

implicit def productHint[T]: ProductHint[T] = ProductHint(ConfigFieldMapping(CamelCase, CamelCase))

case class SparkConf(master: String, deployMode: String, driverHost: String, driverPort: String, logLevel: String)
case class Conf(environment: String, spark: SparkConf)

pureconfig.loadConfig[Conf]
// returns Right(Conf(default,SparkConf(local[*],client,localhost,9001,ERROR)))
```

Note that I had to put a different implicit `ProductHint` in scope, since your field mappings differ from the default (see [this section](https://github.com/pureconfig/pureconfig/blob/master/docs/override-behaviour-for-case-classes.md#field-mappings) of the documentation for more information about it).

**Comment by joesan** [comment]
I will give it a try and let you know! But thanks for the help!

**Comment by ruippeixotog** [comment]
@joesan I'll close this now since it's been some months since the issue was opened. Let me know if you still need help setting up PureConfig!
