### ISSUE TITLE
Site: Broken link on `Supported types` section of the docs

### ISSUE THREAD

**Issue by tarossi** [pureconfig/pureconfig#328]
The link to _Configurable converters_ is wrong: it's https://pureconfig.github.io/docs/docs/configurable-converters.html (404) and should be https://pureconfig.github.io/docs/configurable-converters.html.

**Comment by melrief** [comment]
Right, it's a relative path that starts from `docs` and that's why it ended up being `docs/docs`. I'll fix it now, thanks @tarossi!
