### ISSUE TITLE
-Xmacro-settings:materialize-derivations failing to provide improved error message

### ISSUE THREAD

**Issue by leifwickland** [pureconfig/pureconfig#330]
@ruippeixotog When the better error messages work, they're awesome. In the following case, they don't seem to work. 

I set up a [project](https://github.com/leifwickland/pureconfig-debugging-implicits) to demonstrate.

Am I doing it wrong?

**Comment by ruippeixotog** [comment]
Hi Leif! There doesn't seem to be anything wrong with your setup; this is probably a bug with the derivation macro. I'll take a deeper look at it today or tomorrow.

**Comment by leifwickland** [comment]
Thanks a bunch, Rui!
