### ISSUE TITLE
Allow configuring the word delimiters to be used in implicitly derived ConfigConverts

### ISSUE THREAD

**Issue by jcazevedo** [pureconfig/pureconfig#34]
It would be nice if `pureconfig` would allow customizing the word delimiters for the `ConfigConverts` it derives implicitly. 

This would allow, for example, to have a class with fields defined in camel case:

``` scala
case class Conf(standardTimeout: Duration, numberOfNodes: Int)
```

and the corresponding config using hyphen-separated strings:

```
{ 
  standard-timeout = 5s
  number-of-nodes = 10
}
```

I have a working implementation of this in [this branch](https://github.com/jcazevedo/pureconfig/tree/word-delimiters), but it depends on #28. 

I approached it by requiring an implicit in scope for deriving products that defines how words are delimited. There's a default implicit available that doesn't do anything to the provided fields, but users can provide a different (with higher priority) one to customize the behavior.

For example, if we have the following class:

``` scala
case class Conf(standardTimeout: Duration, numberOfNodes: Int)
val conf = Conf(5.seconds, 10)
```

The default behaviour would be:

``` scala
println(conf.toConfig)
// SimpleConfigObject({"numberOfNodes":10,"standardTimeout":"5s"})
```

But declaring a different way to delimit words would yield:

``` scala
implicit val delim = new WordDelimiterConverter[Conf](CamelCaseWordDelimiter, HyphenWordDelimiter)
println(conf.toConfig)
// SimpleConfigObject({"number-of-nodes":10,"standard-timeout":"5s"})
```

**Comment by melrief** [comment]
The more the library is used the more people ask me if it is configurable which makes me think this issue is an important one.

I personally don't like implicits options and I think that  passing the options to use to `loadConfig` could be easier to read compared to the implicit options. For instance

``` scala
val configLoaderOptions = ConfigLoaderOptions(CamelCaseWordDelimiter, HyphenWordDelimiter)
pureconfig.loadConfig[Conf](configLoaderOptions)
```

**Comment by jcazevedo** [comment]
> I personally don't like implicits options and I think that passing the options to use to loadConfig could be easier to read compared to the implicit options.

OK. The `loadConfig` method should still support being called without options, using a default value (in this case, not doing anything special regarding word delimiters), right? 

I'll prepare a PR during the weekend and we can discuss further details there.

**Comment by jcazevedo** [comment]
I think we can close this now that #39 is merged in.
