### ISSUE TITLE
Support Typesafe size suffixes (e.g. MB, kB, etc...)

### ISSUE THREAD

**Issue by steve-scx** [pureconfig/pureconfig#342]
e.g. https://github.com/lightbend/config/blob/master/HOCON.md#size-in-bytes-format

**Comment by ruippeixotog** [comment]
Hi @oddio! Have you seen [pureconfig-squants](https://github.com/pureconfig/pureconfig/tree/master/modules/squants)? It's a plugin module for [Squants](https://github.com/typelevel/squants), a Scala Typesafe API for quantities of pretty much everything (including information units such as bytes). It seems to cover the use case suggested by the HOCON spec (which IMO, is a bit too opinionated for a general config format).

**Comment by leifwickland** [comment]
Specifically, you'd use the [`Information` type in Squants](https://github.com/typelevel/squants/blob/master/shared/src/main/scala/squants/information/Information.scala#L21) 

If we supported those suffixes generally, I think they'd allowed for any numeric type. That could lead to weirdly nonsensical configuration like:
```
salary: 35 kb
```
which would be valid and mean `35000`.

**Comment by steve-scx** [comment]
Perfect, thanks for the tip!

**Comment by queimadus** [comment]
Support for the typesafe memory size format has been added in https://github.com/pureconfig/pureconfig/pull/775.

```scala
import com.typesafe.config.ConfigMemorySize

case class Foo(size: ConfigMemorySize)
```

```conf
size = 2g
```

The numeric value in bytes can then be obtained via `foo.size.toBytes`.
