### ISSUE TITLE
Add support for cats-effect

### ISSUE THREAD

**Issue by keirlawson** [pureconfig/pureconfig#343]
I'm trying to use pureconfig in combination with cats-effect's IO however as it stands the code to do this is a little faffsome, here is what it looks like in my codebase: 

```scala
  def loadSettings(path: Path): IO[MyConfigCaseClass] = {
    val load: IO[Either[Throwable, MyConfigCaseClass]] = IO {
      val config = loadConfig[MyConfigCaseClass](path)
      config.left.map(x => new RuntimeException("Should actually convert ConfigReaderFailures into exception here"))
    }
    load.flatMap(IO.fromEither)
  }
```

Would it be possible to add support for cats-effect, such that we could have a loadconfig that returns an IO of the config class? This would simplify usage with cats-effect, which it seems to me might be a fairly common use case given pureconfig seems to be the preferred config library within the cats ecosystem.

**Comment by leifwickland** [comment]
While I can't speak for all the authors, I'd certainly be willing to entertain a PR creating a `cats-effect` module analogous to the existing [`cats`](https://github.com/pureconfig/pureconfig/tree/master/modules/cats) module.

Directions for creating a new module are [here](https://github.com/pureconfig/pureconfig#contribute):

**Comment by keirlawson** [comment]
Ok, will have a bash
