### ISSUE TITLE
load config from Source or similar to increase testability

### ISSUE THREAD

**Issue by keirlawson** [pureconfig/pureconfig#345]
Right now the `loadConfig` methods provided by pureconfig are oriented around `java.nio.Path`s when a non-default location is required.  However for those wishing to unit test their configuration code without having said tests go to the filesystem, this presents a problem as `Path` is not readily mocked. To this end I would propose adding another variant of `loadConfig` that takes something less tightly bound to the filesystem itself. Options include fs2 streams which would be nice however I suspect pureconfig does not want to introduce a dependency on fs2? Otherwise, `scala.io.Source` seems like a good candidate.

If this idea is deemed useful happy to provide a PR.

**Comment by ruippeixotog** [comment]
Hi @keirlawson! As you might have seen, `loadConfig(path: Path)` does little more than loading a `com.typesafe.config.Config` from a file and then passing it to PureConfig for reading. The most "canonical" method we have for loading a config is `loadConfig(conf: com.typesafe.config.Config)`, which delegates to the user the part of loading the config itself.

If you take a look at Typesafe's `ConfigFactory`, you see methods for every use case:
- `parseString` for creating a `Config` from a string;
- `parseFile` for creating a `Config` from a file;
- `parseResources` for creating a `Config` from JAR resources;
- `parseReader` for reading from an arbitrary input stream.

Isn't this enough for unit tests?

**Comment by keirlawson** [comment]
Yep, the `parseString` approach is the one I am currently taking. It feels a little inelegant though, both having to use a transative dependency (typesafe config) who's API is only partially abrastracted over, and also in generating and passing around the `com.typesafe.config.Config` object which is purely an itermiadiary.  I think adding an additional convience method, such as `loadConfig(source: Source)` would render the API easier to use in my case, just as `loadConfig(path: Path)` does when one in not concerned about unit testing.

**Comment by ruippeixotog** [comment]
I'm ok with adding an overloaded `loadConfig(source: Source)` to our API, if the other authors agree. The most elegant bridge wouldn't be through a `String` IMO, but from a Java `Reader` (there's `Source#reader()` and `ConfigFactory.fromReader`).

Please bear in mind that, while there's an [open issue](https://github.com/pureconfig/pureconfig/issues/87) to make PureConfig independent from the backend API, that's not at all the case right now. Typesafe Config is not a simple transitive dependency: our API intentionally does not abstract over it and `com.typesafe.config.Config` is not purely an intermediary, but our core model of a config. On the upcoming version there will be a greater distance from concrete backends with the implementation of `ConfigCursor`s, but if you are using the current version (0.8.0) and you need to add support for a custom type, you'll still have to deal with instances of `ConfigValue`. As such, I wouldn't personally feel like I was breaking some abstraction layer by creating a `Config` manually.

**Comment by keirlawson** [comment]
In terms of possible implementation, I worry that `Reader` has pretty low level concepts associated with it that doesn't make for very elegant mapping from of `Source`, such as the public `lock` field for synchronization. Whilst I suspect a working mapping would be achievable, it might end up feeling more hacky that just using Source's `.mkString`

**Comment by melrief** [comment]
I would prefer to not add new overloads to the main API as it is already difficult to maintain, in particular due to the fact that each overload must have multiple "flavors". I agree with @ruippeixotog about using the "canonical" method for custom inputs and `ConfigFactory` provides enough ways to load a configuration, e.g. `parseReader`.

**Comment by keirlawson** [comment]
Ok, will close issue.
