### ISSUE TITLE
Make FirstSuccessCoproductHint NoValidCoproductChoiceFound error user friendly

### ISSUE THREAD

**Issue by yarulan** [pureconfig/pureconfig#356]
```scala
sealed trait Shape
case class Circle(radius: Int) extends Shape
case class Square(side: Int) extends Shape
implicit val hint = new FirstSuccessCoproductHint[Shape]
println(pureconfig.loadConfig[Shape](ConfigFactory.parseString("")))
```
The error says `ConvertFailure(NoValidCoproductChoiceFound(SimpleConfigObject({})),None,)` which doesn't explain much. It would be better if it contained all possible choices, like
```
missing radius
  or
missing side
```

**Comment by ruippeixotog** [comment]
Hi @yarulan! Improving the default error messages for coproducts is a good idea, not only with `FirstSuccessCoproductHint` but also with other hints. Unfortunately, right now it's not trivial to obtain the information you mentioned when the error is created, but a small refactoring to allow that would be nice.
