### ISSUE TITLE
loadConfig For GenericType

### ISSUE THREAD

**Issue by ghost** [pureconfig/pureconfig#358]
I am trying  to write a config  parser  which parser the configs and loads into Type T , but It fails with below error.  I think I have to create a ConfigReader , but I am nor sure how to create one for Generic Type

```
trait ConfigParser[+T<: Configuration] {
  implicit def hint[T] = ProductHint[T](ConfigFieldMapping(CamelCase, CamelCase))

  def load(configFile: String):T ={
    loadConfigOrThrow[T](ConfigFactory.load(configFile))
  }

```

```
case class SomeCaseClass(val enable:Boolean)
 
trait Configuration{
  def somecaseClass: SomeCaseClass
}
case class Foo(val somecaseClass: SomeCaseClass) extends  Configuration

case class Bar(val somecaseClass: SomeCaseClass) extends  Configuration
```

Error 
```
Error:(33, 25) not enough arguments for method loadConfigOrThrow: (implicit evidence$5: scala.reflect.ClassTag[T], implicit reader: pureconfig.Derivation[pureconfig.ConfigReader[T]])T.
Unspecified value parameters evidence$5, reader.
    loadConfigOrThrow[T](load())
```

Please let me know if its feasible or some other solution I could use to create a generic utility

**Comment by ruippeixotog** [comment]
Hi @kotiajit! The easiest way to get your code working, in my view, is to just pass the two required implicits for `T` - a `ClassTag[T]` and a `ConfigReader[T]` - as parameters in your `ConfigParser` trait. If you are able to turn it into an `abstract class`, that should read:

```scala
abstract class ConfigParser[+T <: Configuration: ClassTag: ConfigReader] {
  // (...)
}
```

**Comment by ghost** [comment]
@ruippeixotog  this works thanks

**Comment by MoustafaAMahmoud** [comment]
Hi @ruippeixotog ,

I have the same issue in my code and it getting the same error
```
import pureconfig._
import pureconfig.generic.auto._
 def parseEnvConfig[T](someConfString:String): T = {
            ConfigSource.string(someConfString).load[T].right.get
  }
```

But I am not sure How can I fix this.

**Comment by jcazevedo** [comment]
@moustafaalaa: You seem to be missing a `ConfigReader` as an implicit parameter to your `parseEnvConfig` function. Adding it should suffice:

```scala
def parseEnvConfig[T: ConfigReader](someConfString: String): T = {
  ConfigSource.string(someConfString).load[T].right.get
}
```

**Comment by MoustafaAMahmoud** [comment]
@jcazevedo  Thanks It worked :)
