### ISSUE TITLE
Fail deriving ConfigReader in projects with custom Predef

### ISSUE THREAD

**Issue by ktonga** [pureconfig/pureconfig#382]
I'm attaching a minimal sbt project using custom predef called `std`, if you run `sbt compile` build will fail with implicit resolution error. If you remove `import std._` from `config.scala` and remove `"-Yno-imports" and "-Yno-predef"` from `build.sbt` the project compiles

[pureconfig-custom-predef.zip](https://github.com/pureconfig/pureconfig/files/1937464/pureconfig-custom-predef.zip)

**Comment by ruippeixotog** [comment]
Hi @ktonga! This seems to be an issue with the `Derivation` macro we use to [provide better "implicit not found" messages](https://pureconfig.github.io/docs/faq.html#how-do-i-debug-implicit-not-found-errors). When I add the flag `-Xmacro-settings:materialize-derivations` to `scalacOptions` the code starts compiling correctly with the custom predef, which is rather strange.

I'll take a look at this once I can, but as a temporary workaround you shouldn't find any problem with enabling the derivation feature using the scalac flag above.

**Comment by ktonga** [comment]
Awesome! thanks a lot @ruippeixotog I can confirm it is working now using the provided workaround and whenever I miss a reader the error message is super helpful
