### ISSUE TITLE
Move `ConfigReaderFailures` pretty printing logic away from `ConfigReaderException`

### ISSUE THREAD

**Issue by JD557** [pureconfig/pureconfig#385]
Here's my problem: I want to load a config in a safe way (without throwing exceptions) and log the errors in a pretty error messages.

Right now, it appears that the two best ways to do this are:
* Use `loadConfig[Config](config, "field")` and write my own `ConfigReaderFailures` pretty printer;
* Use `Try(loadConfigOrThrow[Config](config, "field"))` and log the exception message;

I think that the pretty printing logic could be moved to the `ConfigReaderFailures`.

It might also be nice to add a `Show` implementation to the cats module (or maybe not, not sure if this is out of the scope of that module).

**Comment by ruippeixotog** [comment]
Looks good to me - users should be able to generate pretty error messages without having to create an exception for that. I'm not sure if `ConfigReaderFailures` is the best place for that, but I wouldn't mind having it there (on one hand, it's nice to have `ConfigReaderFailures` agnostic of any string representation; on the other hand, `FailureReason`s already have string descriptions, so the models are already tied to a concrete string representation).

A `Show` instance in pureconfig-cats with this logic would be perfectly adequate.

**Comment by leifwickland** [comment]
I and other folks at work have run into this problem. I too would love a solution.

Because we're stuck with scalaz, I'd like to request that the formatting logic isn't _only_ in a cats `Show` instance.

**Comment by ruippeixotog** [comment]
@leifwickland not really related to this issue, but out of curiosity: since you're using scalaz and surely many more people are stuck with it, wouldn't a scalaz module with `ConfigConvert` instances for data structures and scalaz instances for `ConfigReader`/`ConfigWriter` be a nice thing to have?
