### ISSUE TITLE
cats-effect module should have a `loadConfigF` taking a Config

### ISSUE THREAD

**Issue by kubukoz** [pureconfig/pureconfig#388]
Sometimes you want to parse an already fetched Typesafe Config object. Currently I'm doing it with  `Sync[F].delay(pureconfig.loadConfigOrThrow[AppConfig](config))`, but I believe there could be an overload of `loadConfigF` that would internally use `configToF` to achieve that effect without throwing an exception just to catch it.

I'll be happy to submit a PR with this overload, if the issue makes sense :)

**Comment by leifwickland** [comment]
@kubukoz, That seems plausible to me. Give it a shot!

**Comment by ruippeixotog** [comment]
Closed by #389.
