### ISSUE TITLE
Some combinations of case classes + fields lead to compilation StackOverflow

### ISSUE THREAD

**Issue by ezhulkov** [pureconfig/pureconfig#390]
Extremely weird and strange behaviour. 

Very artificial yet simple example of pureconfig usage is uploaded to sandbox repo here 
https://github.com/zeptolab/pureconfig-bug

We have very simple config case class which consist of 4 fields.

`case class Config(
    database: DatabaseConfig,
    amplitude: AmplitudeConfig,
    flurry: FlurryConfig,
    appsFlyer: AppsFlyerConfig
)`

Compilation of this class leads to StackOverflowException. Full stacktrace is stored here [https://github.com/zeptolab/pureconfig-bug/blob/master/compile.txt](https://github.com/zeptolab/pureconfig-bug/blob/master/compile.txt)

But even renaming of some fields or removing unused case classes (GdprConfig e.g.) eliminate this bug. Just can't wrap my head around it. 

As a workaround I'll try to refactor case classes but if you need any help or additional information - I'm happy to help you. Thanks in advance.

JDK version is 1.8.0_144
SBT version is 1.1.6
Scala 2.12.6
Bug persists on MacOS and Ubuntu 14.04.5

**Comment by ruippeixotog** [comment]
Hi @ezhulkov! I had no problems compiling the project you provided:

```
pureconfig-bug master ❯ sbt clean compile
[info] Loading settings from idea.sbt,plugins.sbt ...
[info] Loading global plugins from /Users/rui/.sbt/1.0/plugins
[info] Loading project definition from /Users/rui/Downloads/pureconfig-bug/project
[info] Loading settings from build.sbt ...
[info] Set current project to bug (in build file:/Users/rui/Downloads/pureconfig-bug/)
[info] Executing in batch mode. For better performance use sbt's shell
[success] Total time: 0 s, completed Jun 19, 2018 4:14:41 PM
[info] Compiling 1 Scala source to /Users/rui/Downloads/pureconfig-bug/target/scala-2.12/classes ...
[info] Done compiling.
[success] Total time: 11 s, completed Jun 19, 2018 4:14:52 PM
```

Another pureconfig user had a [problem just like yours](https://github.com/pureconfig/pureconfig/issues/318) before. The default SBT JVM settings are way too low in terms of resources for compiler-heavy libraries such as pureconfig. Can you try launching SBT with `SBT_OPTS="-Xms512m -Xmx1536m -Xss2m"` or using the [sbt-extras](https://github.com/paulp/sbt-extras) launcher script and check if the error persists?

**Comment by ezhulkov** [comment]
@ruippeixotog it helped! Thank you a lot

**Comment by xoanpardo** [comment]
Hi @ruippeixotog,

I'm having the same problem described here with the following test project: [https://github.com/xoanpardo/pureconfig-test](url)

The project compiles succesfully if any field is commented, for instance, in the ExperimentParameters case class (commenting fields in other classes also shows the same behaviour). I've tried with different values for -Xms -Xss and -XX:ThreadStackSize with the same result.

I'm compiling using Maven from Eclipse IDE on MacOS. Scala version is 2.12.8

Any idea? Thanks in advance

P.S. is this the right way to proceed or should I open a new issue?

**Comment by leifwickland** [comment]
@xoanpardo, feel free to open an issue just for visibility. The solution is going to require you to figure out how to tell maven to provide sbt with more memory. That's not an issue specific to pureconfig and as far as I know, no one on the team has expertise with maven, so you'll have to work out the details on your own.

**Comment by agadek** [comment]
Same issue here. I had to downgrade to from 10.2 to previously used 9.2. The issue occurs when `import pureconfig.generic.auto._` used.

**Comment by fkowal** [comment]
Hi
I am experiencing the same problem. On mac, scala 2.12.8, sbt 1.2.8, pureconfig 0.10.2, `import pureconfig.generic.auto._`

In my case commenting out `FiniteDuration` seems to fix the problem.
