### ISSUE TITLE
Cats: provide a Parallel instance for ConfigReader

### ISSUE THREAD

**Issue by nigredo-tori** [pureconfig/pureconfig#397]
`ConfigReader.zip` allows us to run two readers and get the errors from both. However the provided `MonadError[ConfigReader]` means that the `ConfigReaders` built with cats syntax (e.g. with `.mapN` combinator) will not run the second reader if the first one fails.

`cats` provides an idiomatic way to solve this. Given a newtype
```scala
final class ParConfigReader[A](val self: ConfigReader[A]) extends AnyVal
```
we can define a parallel `Applicative[ParConfigReader]` (non-implicit) and an obvious `Parallel[ConfigReader, ParConfigReader]`. This would give us combinators like `.parMapN` and `.parTraverse`, which can be used to build readers that would provide the full error list.

Otherwise, we can just make the parallel behavior the default, replacing the `MonadError` instance with an `ApplicativeError`. `cats.data.Validated` is one such type.

**Comment by ruippeixotog** [comment]
Hi @nigredo-tori! I am not a regular cats user, so I am not familiar with how these cases are handled. Do you have a preference for the first solution?

Are there other examples or some documentation of that idiomatic way of supporting `parMapN` and `parTraverse`? That would allow me to get a grasp of how it would work.

**Comment by nigredo-tori** [comment]
@ruippeixotog, here's the corresponding [section](https://typelevel.org/cats/typeclasses/parallel.html) in the `cats` manual. Further information can be found in the scaladoc for `Parallel` and `Validated`, and in the `cats` source code. `parMapN` (and its older brother `mapN`) is a syntax on tuples that is handled by the [boilerplate generator](https://github.com/typelevel/cats/blob/master/project/Boilerplate.scala).

The first solution is less intrusive (it won't break the existing code). However, since it makes sense to show all the errors by default, going the second way might be better in the long run. Personally I don't have a preference here.

**Comment by nigredo-tori** [comment]
Actually, the second solution (accumulating errors by default) would work better for me. I thought that in my case the difference between the two would amount to just switching between `.mapN` and `.parMapN`. However, we can also add a matching `InvariantSemigroupal[ConfigConvert]`, giving us `.imapN` syntax as well. Since there's no `parImapN`, I would like `imapN` to accumulate errors. And since it doesn't make sense to have a different behavior for `.mapN`, it should also do the same.
