### ISSUE TITLE
Provide proper OSGi metadata

### ISSUE THREAD

**Issue by lefou** [pureconfig/pureconfig#4]
To use this library in an OSGi environment, proper OSGi headers in the JAR manifest are needed. There is the sbi-osgi plugin (https://github.com/sbt/sbt-osgi) which can produce most of these headers automatically.

**Comment by melrief** [comment]
Will do in the next release, I hope tomorrow or in the weekend. Thanks.

**Comment by lefou** [comment]
Great. Yesterday, I created a fork with two branches: `java7` and `java7-osgi`. The latter contains OSGi settings but is based on the former, so, with regard to #5 I will not open a pull request. But feel free to cherry pick.
https://github.com/lefou/pureconfig/tree/java7-osgi

**Comment by melrief** [comment]
Cherrypicked the two commits about OSGi. Closing this.

**Comment by lefou** [comment]
Great. Thanks!
