### ISSUE TITLE
Save functions should allow overriding ConfigRenderOptions

### ISSUE THREAD

**Issue by nigredo-tori** [pureconfig/pureconfig#403]
I'm migrating an existing config system to pureconfig, and one of the steps for this is converting the existing legacy configs to the new format. The default `ConfigRenderOptions` are not what I need here - these include origin comments, which in my case are useless. However there doesn't seem to be a way to override these in pureconfig functions (e.g. those in the `cats-effect` and `fs2` modules).

**Comment by ruippeixotog** [comment]
I agree - all `saveConfigTo*` methods, both in PureConfig core and in its modules, should have an `options: ConfigRenderOptions = ConfigRenderOptions.defaults()` optional argument 👍
