### ISSUE TITLE
pureconfig-yaml to Central Maven Repo 

### ISSUE THREAD

**Issue by ghost** [pureconfig/pureconfig#409]
Thanks for adding the pureconfig-yaml  module , I was planning to try it out , Can you please publish the jar to Central Maven Repo

**Comment by ruippeixotog** [comment]
Hi @kotiajit, sorry for the delay in publishing this. We'll just wait until https://github.com/pureconfig/pureconfig/pull/408 gets merged and afterwards we intend to release a new version with the new modules :)

**Comment by ghost** [comment]
Cool, Will wait for it , Thanks

**Comment by ghost** [comment]
I see the new releases , thanks
