### ISSUE TITLE
Can you come up with something that will help me allow my bank to use this?

### ISSUE THREAD

**Issue by JohnReedLOL** [pureconfig/pureconfig#422]
Sorry to bother you,

I am working on a Scala project and I would like to be able to use some open source libraries. That being said, the bank I work at has a lot of red tape and they don't approve anything unless you convince them to do so. In about a month I'm going to do a demo of the open source libraries that I want them to put into their system. To help me get approval, could you write something explaining that they won't have any issues with copyright or patents and that this library is being actively maintained, is well documented, and has real world business value?

**Comment by leifwickland** [comment]
I believe commit and release histories show the library is actively maintained.

The [license](https://github.com/pureconfig/pureconfig/blob/master/LICENSE) file addresses that the project is available for free commercial use including any patents.

The typical business value derived by using pureconfig is that developers are more efficient, implementing the same functionality with fewer mistakes.

Good luck convincing your overlords, @JohnReedLOL. Please let us know how it goes.
