### ISSUE TITLE
PureConfig auto-derived ConfigReader for Tuples is unhelpful

### ISSUE THREAD

**Issue by rzeigler** [pureconfig/pureconfig#426]
I have a situation where I am tinkering around with exposing the ability to load a base config with client extensible additional properties.

My initial thought was to define a method such as 
```
def load[Ext: ConfigReader](url: URL): Either[ConfigReaderFailures, (Config, Ext)] = 
    loadConfig[(Config, Ext)](ConfigFactory.parseURL(url))
```

The resulting call fails with the somewhat unhelpful 
```
 - (file:.conf Key not found: '_1'.
 - (file:.conf Key not found: '_2'.
```

This seems like a fairly useless derivation when when what I really want is the union of the products rather than a product. Is this something that is feasible or is there another way of encoding what I'm trying to do?

**Comment by nigredo-tori** [comment]
I don't think there is a derivation for that, but you can do it manually using [`ConfigReader.zip`](https://github.com/pureconfig/pureconfig/blob/4e3895c5eaeef5c38e060f8b4eb36517057c562c/core/src/main/scala/pureconfig/ConfigReader.scala#L66-L73).

**Comment by leifwickland** [comment]
@rzeigler, It looks like `Config` and `Ext` are entirely independent and that you expect both to be sourced from the root of the configuration from the URL. @nigredo-tori's suggestion looks to be exactly right because it constructs a new reader in which each child is read from the root, rather than creating additional structure that must be present at the root, as you're seeing with the tupled approach.

**Comment by rzeigler** [comment]
Zip seems to do what I want so thanks!

To my other point though, should ConfigReader[A], ConfigReader[B] always imply ConfigReader[(A, B)]. When I didn't have to provide my own ConfigReader[(A, B)] I thought maybe it was doing something fancy like concatenating the HList internally. The actual behavior while it makes sense seems not terribly useful for a configuration file specifically in most cases.

**Comment by nigredo-tori** [comment]
To be honest, I don't see much use for the "concatenating" behavior. "Tuple as array" is more or less intuitive if you think of it in terms of `ConfigValue` and not `ConfigObject`. And, unlike "concatenating HList", it preserves the round-trip (that is, any tuple can be encoded, and the result can be correctly decoded - think `(Int, Int)`).

Also, the existing behavior matches the behavior in Circe, so it's a little less surprising.

**Comment by ruippeixotog** [comment]
@nigredo-tori explains the rationale pretty well. Tuple as a merge of types is a flawed (and incorrect from a theoretical standpoint) approach: there's ambiguity when you load a `(A, B)` pair where both `A` and `B` have a field with the same name and some types may not even be mergeable (e.g. `(A, String)` where `A` reads from an object).

Think of tuples as containers instead; a pair holds two values with possibly different types and can be loaded as an array from a config, like `[A, B]`. You'll find plenty of use cases where you want to load such a structure but for some reason don't want to define a new object - for example, you can load a list of histogram counters (a `List` of `(String, Int)` entries) encoding it in the config as `[[a, 1], [b, 3], [c, 2], ...]`.
