### ISSUE TITLE
Consider readers for e.g. java.time.LocalTime

### ISSUE THREAD

**Issue by kubukoz** [pureconfig/pureconfig#431]

**Comment by ruippeixotog** [comment]
There are multiple ways to write a `LocalTime` to a string, so we opted to provide them in the `configurable` package (see [here](https://github.com/pureconfig/pureconfig/blob/master/core/src/main/scala/pureconfig/configurable/package.scala#L33)). Please see also the documentation at https://pureconfig.github.io/docs/configurable-converters.html.

I'll close this, let me know if you find a problem with configurable converters :)

**Comment by kubukoz** [comment]
That looks nice, I didn't know about configurable :) thanks!

**Comment by leifwickland** [comment]
@kubukoz, is there a place that pureconfig should've documented the `configurable` time functionality so that you were more likely to find it?

**Comment by kubukoz** [comment]
To be fair, I only looked at the standard formats for dates found in the core module, maybe a comment there (https://github.com/pureconfig/pureconfig/blob/master/core/src/main/scala/pureconfig/BasicReaders.scala) leading to the `configurable` module would help? Btw. I greatly appreciate the interest in improvement!

**Comment by leifwickland** [comment]
@kubukoz I like that idea. Would be interested in sending a PR which adds a note in the comment block for `JavaTimeReaders` which suggests looking at `configurable` for support for other time types?
