### ISSUE TITLE
pureconfig pulls in dependencies to scala-compiler, scala-reflect

### ISSUE THREAD

**Issue by mberndt123** [pureconfig/pureconfig#433]
Hey,

I noticed today that when I add a dependency to pureconfig, I also get a transitive dependency to scala-compiler and scala-reflect. My understanding is that these are only needed at compile-time for the generic macros and not at run-time. Other libraries seem to solve this problem by depending on these in the `Provided` scope, see e. g. [circe](https://github.com/circe/circe/blob/f38f73cfecbe25b514fb45ef434d3c26693000b9/build.sbt#L210) or [shapeless](https://github.com/milessabin/shapeless/blob/1185bc22692bd5c085b158b732c931d1091c5c62/build.sbt#L244). I've tried making this change in the pureconfig generic module but failed for reasons I don't quite understand, maybe you can figure it out…

Anyway, scala-compiler and scala-reflect 2.12.7 together currently weigh 13.5MB, which is more than 20 times larger than pureconfig.

**Comment by jcazevedo** [comment]
Thanks for reporting this! I believe #434 should fix this issue.

**Comment by mberndt123** [comment]
cool, thanks for taking care of this
