### ISSUE TITLE
loadConfig fails to find implicit reader

### ISSUE THREAD

**Issue by msinton** [pureconfig/pureconfig#441]
This is on version 0.10.1. When I downgrade to 0.9.1 then it works.
```
Error:(17, 51) could not find implicit value for parameter reader: pureconfig.Derivation[pureconfig.ConfigReader[tvr.config.AppConfig]]
    val mongo = Mongo(loadConfigOrThrow[AppConfig]("tvr").mongoConfig)

Error:(17, 51) not enough arguments for method loadConfigOrThrow: (implicit evidence$2: scala.reflect.ClassTag[tvr.config.AppConfig], implicit reader: pureconfig.Derivation[pureconfig.ConfigReader[tvr.config.AppConfig]])tvr.config.AppConfig.
Unspecified value parameter reader.
    val mongo = Mongo(loadConfigOrThrow[AppConfig]("tvr").mongoConfig)
```

Config is simple:
```
final case class AppConfig(mongoConfig: MongoConfig)

final case class MongoConfig(credentials: MongoCredentials, hosts: List[String], port: String, replicaSetName: String)

final case class MongoCredentials(user: String, password: String, authDatabaseName: String)
```

**Comment by jcazevedo** [comment]
I'm not sure if that's the case, since I don't know which imports you're using, but the automatic derivation of readers and writers is disabled by default since 0.10.0. It is now necessary to import `pureconfig.generic.auto._` everywhere a config is loaded or written, or use semi-automatic or manual derivation. You can read more about it in the [documentation](https://pureconfig.github.io/docs/non-automatic-derivation.html).

**Comment by msinton** [comment]
O I see, I did not find that requirement very clear from your readme - and when adding that import intellij reports that it is unused.

**Comment by jcranky** [comment]
IntelliJ unfortunately is not very smart in this case - but if you keep the import, does it work? Could this issue be closed?

**Comment by msinton** [comment]
Yes that is correct. It is a pain point for my team but we will just use semi-auto instead.

**Comment by charmby** [comment]
error: could not find implicit value for parameter reader: pureconfig.Derivation[pureconfig.ConfigReader

**Comment by sfosdal** [comment]
> Yes that is correct. It is a pain point for my team but we will just use semi-auto instead.

We will be doing the same.

`pureconfig.generic.auto._` contains only macros, which yeah, IntelliJ messes up.

am glad semiauto is an option

**Comment by giuscri** [comment]
As suggested by @jcazevedo, you need to `import pureconfig.generic.auto._`.

That said, in my case the problem was I was trying to parse a configuration into a `class` and *not* a `case class`.
