### ISSUE TITLE
Use Environment Variables for properties of type Int (eg UserPortNumber) 

### ISSUE THREAD

**Issue by leozilla** [pureconfig/pureconfig#452]
I defined my config case classes like this:
```scala
case class RedisConfig(host:NonEmptyString, port:Option[UserPortNumber])
```

And I would like to use environment variable substitution in my config:
```
redis {
    host = ${REDIS_HOST}
    port = ${?REDIS_PORT}
}
``` 

The loading seems to work for the `host` field but fails for the `port` field with the following exception:
```
Exception in thread "main" pureconfig.error.ConfigReaderException: Cannot convert configuration to a app.betr.client.usersessionservice.AppConfig. Failures are:
  at 'app.betr.client.user-session-service.redis.port':
    - Expected type NUMBER. Found STRING instead.
 	at pureconfig.package$.getResultOrThrow(package.scala:139)
	at pureconfig.package$.loadConfigOrThrow(package.scala:207)
	at app.betr.client.usersessionservice.AppConfig$.init(AppConfig.scala:26)
	at app.betr.client.usersessionservice.UserSessionService$.main(UserSessionService.scala:20)
	at app.betr.client.usersessionservice.UserSessionService.main(UserSessionService.scala)
```

I possible workaround is ofc to change the type of `port` from `UserPortNumber` to `String` but this suboptimal. I would really like to work with the dedicated type.

Is there a way to be able to use environment variables here and also to use types like `Int` or `UserPortNumber` for the `port` field?

**Comment by leifwickland** [comment]
David,

I would expect what you describe to work.

The error message you're getting means that after the environmental
variables, config files, etc have been resolved into a typesafe `Config`,
pureconfig is finding something in `redis.port` that it can't convert to a
`Long` or `Double`. See
https://github.com/pureconfig/pureconfig/blob/master/core/src/main/scala/pureconfig/ConfigCursor.scala#L275
.

For the sake of debugging, I suggest you make the `port` field a `String`
and see what value is actually being loaded.

If that doesn't solve your issue, would you be willing to make a small
project to reproduce the problem?

Thanks,

Leif

**Comment by leozilla** [comment]
Sorry, you are right. It was a typo while setting the environment variable.
I will close this issue.
