### ISSUE TITLE
Using pureconfig in a generic type hierarchy

### ISSUE THREAD

**Issue by geoHeil** [pureconfig/pureconfig#453]
I want to use pureconfig in a generic type hierarchy. I.e. there is a base class which accepts a type parameter and then it should be able to parse the configuration.

For the old version of 0.9.2 this worked great with an additional implicit value of ConfigReader. This is no longer enough for the 0.10.x series where automatic case class support was disabled by default.

I could import the implicits into every child, but would certainly prefer to keep them in the base class.

https://stackoverflow.com/questions/54919635/pureconfig-no-manual-imports-of-pureconfig-generic-auto
Has some additional details.

**Comment by ruippeixotog** [comment]
Hi @geoHeil! Unfortunately, I can't see a workaround for your case. When you define `object MyOperation extends SparkBaseRunner[MyCaseClass]` there is no way for PureConfig to know how to derive this without importing `auto`, now that generic derivation is opt-in.

We usually recommend reading the whole config as a single operation and passing parts of it around to the program. When that happens, `auto._` only has to be imported at the top-level config loading step, which limits the exposure of the rest of the code to PureConfig. Given the domain of your problem, I guess that each subclass of `SparkBaseRunner` is a different `App` and there shouldn't be that many of them, right? If that's the case, I suppose that adding the import statement won't be that painful. Sorry I couldn't help you more than this.

**Comment by geoHeil** [comment]
Thanks. That is sad.

If I would define the class hierarchy a bit different - would you then see an option to not import it multiple times (once for each implementation of the base class)?
Indeed, the whole config is read as a single operation already. But there are multiple applications (each as a separate implementation of the base class).

**Comment by ruippeixotog** [comment]
Closing as it's very unlikely we'll change back to automatic generic derivation without imports. The solution requires restructuring the project around standard PureConfig practices.
