### ISSUE TITLE
Support Javascript

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#46]
We are using all scala libraries that support ScalaJS and `pureconfig` code should be compatible with ScalaJS so it's natural to create and publish the library also for ScalaJS.

**Comment by n4to4** [comment]
I was trying to look into this, but got some trouble. Does `typesafe config` support Scala.js?
I found [some people say not]( https://www.reddit.com/r/scala/comments/4eb0pc/typesafeconfig_on_javascript/). Or am I missing something?

**Comment by melrief** [comment]
My bad, I was sure it was because a developer told me so. I guess we need to speed up the abstraction from the backend then because I would like to start using pureconfig also in javascript. Closing for now, thanks @n4to4 for having a look.

**Comment by guersam** [comment]
FYI: There's https://github.com/akka-js/shocon which is written in pure scala and supports both jvm and js.
