### ISSUE TITLE
misleading example on the GIF

### ISSUE THREAD

**Issue by JiniousChoi** [pureconfig/pureconfig#463]
Following the exact instructions on the GIF doesn't take us to the end result but a few errors occurred.
https://camo.githubusercontent.com/cd550455fd9584214104b64071a02e443317a4d8/687474703a2f2f692e696d6775722e636f6d2f503673646130362e676966

Issue 1. Since the scalaVersion in the example is 2.12.1, I think the libraryDependencies needs to be fixed
as-is: libraryDependencies += "com.github.pureconfig" %% "pureconfig"
to-be: libraryDependencies += "com.github.pureconfig" %% "pureconfig" % "0.10.2"

Issue 2. According to this issue, https://github.com/pureconfig/pureconfig/issues/441#issuecomment-444106292, we need to always import ```pureconfig.generic.auto._``` before using this method `loadConfigOrTHrow` with ConfigReader implicitly.

With those two patches above I get the result all right.

**Comment by ruippeixotog** [comment]
Thanks for pointing this out, @JiniousChoi!

@melrief, can you create a new GIF with the imports up-to-date? Otherwise just let me know which program you used to record it and I'll find some time to do it later :)

**Comment by jcazevedo** [comment]
Have we considered removing the gif from the README? It's something that's hard to maintain and in my opinion adds little value when compared to some code that can be copied (which we have in the "Quick Start" section).

**Comment by ruippeixotog** [comment]
I agree, we should try to make everything as easy as possible to maintain 👍

**Comment by leifwickland** [comment]
I'm good with that.
