### ISSUE TITLE
Transform from different date formats to a single one depending of case class

### ISSUE THREAD

**Issue by pettercastro** [pureconfig/pureconfig#465]
By having a config like this
```
job: { date: "14:00" }
task: { date: "23-12-01 11:00", name: "Me" }
```
And assuming I have 2 case classes, and both use the same type for the `date` field, like:
```
case class Job(date: LocalDateTime)
case class Task(date: LocalDateTime, name: String)
```
Is there a way to define a different converter per each case class?
So that I can convert from the format "14:00" to today "2019-04-18 14:00:00" (LocalDateTime) just when loading from the config to the `Job` case class, but when loading from the config to the `Task` case class, apply another transformation to the string to convert it to a LocalDateTime too?

**Comment by ruippeixotog** [comment]
Interesting scenario! My solution would be to use semi-auto derivation and have a different `LocalDateTime` in scope in each of them. Something along the lines of:

```scala
import pureconfig.generic.semiauto._

implicit val jobReader = {
  // ConfigReader[LocalDateTime] for HH:MM
  implicit val localDateTimeReader = ???
  deriveReader[Job]
}

implicit val taskReader = {
  // ConfigReader[LocalDateTime] for YY-mm-dd HH:MM
  implicit val localDateTimeReader = ???
  deriveReader[Task]
}
```

Let me know if this approach worked for you.

**Comment by pettercastro** [comment]
it worked!... Thanks... Did not know about that derived reader
