### ISSUE TITLE
Error loading config

### ISSUE THREAD

**Issue by tampler** [pureconfig/pureconfig#471]
Hello

I"m trying to load a [simple](https://github.com/Clover-Group/front/blob/withdoobie/src/main/resources/application.conf) configuration to my auto generated http4s server v0.20.0

My load method is [this](https://github.com/Clover-Group/front/blob/11c010bc33dc5bb3ac362510a009af2e4435a14f/src/main/scala/config/package.scala#L19) 
And I load it like [this](https://github.com/Clover-Group/front/blob/11c010bc33dc5bb3ac362510a009af2e4435a14f/src/main/scala/Server.scala#L21)

And I constantly getting the error below:
```bash
info] Running tsp.Main 
[error] (run-main-1) pureconfig.error.ConfigReaderException: Cannot convert configuration to a config.package$Config. Failures are:
[error]   at the root:
[error]     - Key not found: 'application'.
[error] pureconfig.error.ConfigReaderException: Cannot convert configuration to a config.package$Config. Failures are:
[error]   at the root:
[error]     - Key not found: 'application'.
```
How do I fix that ? Thank you

**Comment by leifwickland** [comment]
@tampler,

 The [`loadConfigF(namespace: String)` method](https://github.com/pureconfig/pureconfig/blob/master/modules/cats-effect/src/main/scala/pureconfig/module/catseffect/package.scala#L45) you're calling takes the base namespace of the configurations. It looks like you'd rather call the overload that takes a path, [`loadConfigF(path: Path)`](https://github.com/pureconfig/pureconfig/blob/master/modules/cats-effect/src/main/scala/pureconfig/module/catseffect/package.scala#L58). 

Please let me know if that solves your problem.

**Comment by tampler** [comment]
@leifwickland Thanks, that worked.
Another issue is that I can't simply load my "application.conf" and need to provide the full path, which is horrible. Can I do better? See my [solution](https://github.com/Clover-Group/front/blob/f444c3e15bc9e5122e2cdfa6f890ef2f29cfd53f/src/main/scala/config/package.scala#L19)

**Comment by leifwickland** [comment]
Pureconfig is simply passing the path to typesafe-config. Using a path relative to the current directory should work.

**Comment by tampler** [comment]
Thanks, @leifwickland 
I made it work with the following:
```scala
val configFile  = Paths.get ("./src/main/resources/application.conf")
def load(path: Path = configFile): IO[Config] = loadConfigF[IO,Config](path)
```
However, I'm still not happy with my load. I need to launch the end-of-the-world, like [this](https://github.com/Clover-Group/front/blob/11c010bc33dc5bb3ac362510a009af2e4435a14f/src/main/scala/Server.scala#L21) to load it.
I saw a better solution here. It worked in HTTP4s 0.18.22 inside a fs2.Stream like [this](https://github.com/jaspervz/todo-http4s-doobie/blob/e28bfb2f7a55a9d16047398097c65a803d12982e/src/main/scala/Server.scala#L15). 
However, if I try to do the same trick in my HTTP4s v.0.20.0, I get the following:
```bash
[error] /home/bku/work/clover/front/src/main/scala/Server.scala:48:5: type mismatch;    │
[error]  found   : fs2.Stream[[x]Any,fs2.INothing]                                      │
[error]  required: fs2.Stream[F,Nothing]                                                │
[error]   }.drain                                                                       │
[error]     ^                                                                           │
[error] one error found 
```
How can I fix this ?

**Comment by leifwickland** [comment]
At that point you're beyond the realm of pureconfig. I suggest you talk to http4s or FS2 folks to find a solution to that problem.
