### ISSUE TITLE
Config reader per attribute per case class

### ISSUE THREAD

**Issue by pettercastro** [pureconfig/pureconfig#472]
I am loading my typesafe config with ENV VARs. Which means something like
```
  team: {
    id: ""
    id: ${TEAM_ID}

    process: false
    process: ${TEAM_PROCESS}

    emails: []
    emails: ${TEAM_EMAILS}

    urls: {}
    urls: ${TEAM_URLS}
  }
```
and I define the case class
```
Team(id: String, process: Boolean, emails: Seq[String], urls: Map[String, String])
```

However, as ENV VARs always arrive as `STRING` to the config, I would like to define a ConfigReader **per attribute per case class**, so that I can make the transformation from String to the Type needed. 
For instance, if it is the `process` attribute in the `Team` case class, then transform the string to Boolean. If is the `emails` attribute in the `Team` case class, then transform the string to a sequence of strings.
Is that possible?

**Comment by leifwickland** [comment]
@pettercastro,

I know of two typical ways people attack this problem:

1. Create `AnyVal` wrappers for all of the non-string types in your case classes and provide `ConfigReaders` to convert those.
2. Defined a private "raw" case class that receives the stringy values. Create a ConfigReader for that raw class and then `emap` that to the reader for case class you actually want to use in your program.

**Comment by pettercastro** [comment]
@leifwickland could u pls help me with a small snippet for option 1? because if I understand correctly, the configReaders are implemented by type (i.e String), and not per attribute, so if I define a ConfigReader for the String, it will try to apply the same transformation to all the attributes, as all of them come as String from the env vars

**Comment by leifwickland** [comment]
@pettercastro 

Here's a [sample repo](https://github.com/leifwickland/pureconfig-team-example/) that shows the two approaches.

All the code is in [Team.scala](https://github.com/leifwickland/pureconfig-team-example/blob/master/src/main/scala/Team.scala). `Team1` shows the `AnyVal` approach. `Team2` shows the "raw" approach.

Does that help?

**Comment by leifwickland** [comment]
I forgot to mention that I assumed you were using a custom format for your list and string (rather than the HOCON native format) because you're loading values from env vars. My examples will be a bit odd if that's not the case.

There are lots of other ways to accomplish the same thing. I probably should've pointed you to the [Supporting New Types](https://pureconfig.github.io/docs/supporting-new-types.html) page in the documentation.

**Comment by pettercastro** [comment]
@leifwickland yeah, that helped a lot! Thank you!
