### ISSUE TITLE
gradle stuck on old scala version can't compile

### ISSUE THREAD

**Issue by geoHeil** [pureconfig/pureconfig#480]
I use gradle to build my scala project. Unfortunately, after a recent refactor it is no longer able to compile it. 

I am running into https://github.com/pureconfig/pureconfig/issues/292 i.e. every second (sometimes random) build works.

Unfortunately, I can't easily upgrade gradle's scala compiler as this seems to use a fairly outdated edition of zinc (https://github.com/gradle/gradle/issues/2158, https://github.com/gradle/gradle/issues/2158https://github.com/gradle/gradle/issues/2158, https://github.com/gradle/gradle/pull/8485)

 ```
   configurations {
        all {
            if (it.name != "zinc") {
                resolutionStrategy {
                    force "org.scala-lang:scala-reflect:2.11.12"
                }
            }
        }
    }
```
doesn't help but also doesn't fix it. If I omit the  `            if (it.name != "zinc") {
` then zinc fails to start with NoMethodFound error.

Is there some way I can tell it to use a more recent version of the compiler?
```
configurations.zinc {
        resolutionStrategy.force "org.scala-lang:scala-library:2.10.7"
    }
```
and 
`        zinc 'com.typesafe.zinc:zinc:0.3.15'`

both failed. And traing to use a more recent version 1.x also failed.

**Comment by ruippeixotog** [comment]
Unfortunately I never built Scala projects with Gradle, so I can't help you. Since this issue is not related at all with PureConfig, it is probably a good idea to open an issue in one of those projects.
