### ISSUE TITLE
StackOverflowError with many nested classes

### ISSUE THREAD

**Issue by EugeneYushin** [pureconfig/pureconfig#481]
Parsing configs with relatively-deep hierarchies results in StackOverflowError using Scala 2.12.8.
```scala
// build.sbt
scalaVersion := "2.12.8"
"com.github.pureconfig" %% "pureconfig" % "0.11.0"

// Main.scala
import pureconfig._
import pureconfig.generic.auto._

object Main {
  def main(args: Array[String]): Unit = {
    val app = loadConfigOrThrow[AppConf]
    println(s"app = ${app}")
  }
}

case class AppConf(i: Int, a: A)
case class A(x: B)
case class B(x: C)
case class C(x: D)
case class D(x: E)
case class E(x: F)
case class F(x: G)
case class G(x: H)
case class H(x: Int)
```

Error message excerpts `sbt clean compile`:
```
[info] Compiling 1 Scala source to ...
[error] ## Exception when compiling 1 sources to ...
[error] null
[error] scala.collection.LinearSeqOptimized.contains(LinearSeqOptimized.scala:104)
[error] scala.collection.LinearSeqOptimized.contains$(LinearSeqOptimized.scala:102)
[error] scala.collection.immutable.List.contains(List.scala:89)
[error] scala.reflect.internal.tpe.TypeConstraints$TypeConstraint.addHiBound(TypeConstraints.scala:144)
...
[error] scala.reflect.macros.contexts.Typers.inferImplicitValue(Typers.scala:56)
...
[error] shapeless.LazyMacros$DerivationContext$State$.resolveInstance(lazy.scala:304)
...
[error] java.lang.reflect.Method.invoke(Method.java:498)
...
[error] pureconfig.derivation.MacroCompat.inferImplicitValueCompat(MacroCompat.scala:36)
[error] pureconfig.derivation.MacroCompat.inferImplicitValueCompat$(MacroCompat.scala:27)
[error] pureconfig.DerivationMacros.inferImplicitValueCompat(Derivation.scala:31)
[error] pureconfig.DerivationMacros.materializeDerivation(Derivation.scala:79)
...
[error] scala.tools.nsc.Global$$anon$4.inferImplicitFor(Global.scala:477)
[error]            
[error] java.lang.StackOverflowError
[error] 	at scala.collection.LinearSeqOptimized.contains(LinearSeqOptimized.scala:104)
[error] 	at scala.collection.LinearSeqOptimized.contains$(LinearSeqOptimized.scala:102)
[error] 	at scala.collection.immutable.List.contains(List.scala:89)
...
```

**Note**, the above example compiles well using Scala 2.11.

**Comment by jcazevedo** [comment]
PureConfig is a "compiler-heavy" library, and we've seen cases in the past where the default resources provided to the Scala compiler are not sufficient to derive readers for more complex structures (see #318, #390 and #391 for examples of this).

Can you try running sbt with `SBT_OPTS="-Xms512m -Xmx1536m -Xss2m"` to see if the error persists?

**Comment by EugeneYushin** [comment]
@jcazevedo thx, it works like a charm.
As there were 4 issues opened, it would might have sense to put a notice in docs about this behaviour?
I'm closing the issue

**Comment by OOPMan** [comment]
Hey guys, it would be really nice if the SBT settings were clearly documented and strongly recommended. 

I ran into this issue using a really simple configuration and had no clue what was going on beyond that it was somehow related to PureConfig.  Eventually I found the right keywords to search for in the issue tracker to get the solution but if I hadn't I would probably have ended up removing PureConfig :-(

**Comment by leifwickland** [comment]
@OOPMan Where do you think it ought to be documented so that folks would be likely to find it?

**Comment by OOPMan** [comment]
@leifwickland Honestly, if it were me I would stick this in bold letters at the top of the README so anyone browsing the repo would notice it quickly. I think putting it in the Quickstart section would be fine though.

When you have a library that requires additional JVM parameters to be set just for it to work with a really simple scenario (3 case classes, a total of 12 fields between them) then it should be clearly stated up front. 

I really like what PureConfig does, it's a no-brainer library but trying to use it and getting hit with a C++-esque compilation error is a bad user experience :-)

**Comment by ruippeixotog** [comment]
I guess the only reason this is not a more prevalent issue is that many people use https://github.com/paulp/sbt-extras to boot and manage sbt versions, and the script uses much saner JVM defaults.

@OOPMan I'm curious to see the case in particular where it failed for you. Can you share a minimal project with 3 case classes and 12 fields that fails to compile under the default settings?

**Comment by AceHack** [comment]
None of these have fixed the issue for me, it works fine in Scala 11, just blows up in scala 12

**Comment by AceHack** [comment]
I was building with gradle and finally got it to work with the following options
        scalaCompileOptions.forkOptions.jvmArgs = ['-Xss2m', '-XX:-UseGCOverheadLimit']

**Comment by gergelyfabian** [comment]
I experienced this with Bazel/rules_scala, and tracked it in https://github.com/bazelbuild/rules_scala/issues/1306 (StackOverFlow is not visible right away in the Bazel output).

Upgrading scalac memory settings fixes the problem also for Bazel.
What I found in addition is, that upgrading pureconfig from 0.14.0 (the version I tested), to anything higher (e.g. 0.15.0, 0.16.0 or 0.17.0) seems to fix the problem without increasing JVM memory.

**Comment by gergelyfabian** [comment]
For the record, if I make the nested case class structure twice as deep in the example, then upgrading pureconfig does not help (in my configuration), so only setting the memory works.

**Comment by lleugen** [comment]
> I guess the only reason this is not a more prevalent issue is that many people use https://github.com/paulp/sbt-extras to boot and manage sbt versions, and the script uses much saner JVM defaults.
> 
> @OOPMan I'm curious to see the case in particular where it failed for you. Can you share a minimal project with 3 case classes and 12 fields that fails to compile under the default settings?

```
case class ColumnEncryptionStrategy(strategyName: String, alphabet: Option[String], fields: List[String])
case class EncryptionTransformerParameters(
    inputViewName: String,
    outputViewName: String,
    decrypt: Option[Boolean],
    secretName: String,
    keyId: String,
    strategies: List[ColumnEncryptionStrategy]
)
case class DEncryptionTransformerInput(
    transformerType: String,
    params: EncryptionTransformerParameters
)
```

Trying to load this using the following code gives stackoverflow error
```
val encryptionTransformerInput = ConfigSource
      .fromConfig(config)
      .loadOrThrow[DEncryptionTransformerInput]
```
```
[error] java.lang.StackOverflowError
[error] scala.tools.nsc.typechecker.Contexts$Context.lookupSymbol(Contexts.scala:1047)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedIdent$2(Typers.scala:5192)
```

**Comment by lleugen** [comment]
> > I guess the only reason this is not a more prevalent issue is that many people use https://github.com/paulp/sbt-extras to boot and manage sbt versions, and the script uses much saner JVM defaults.
> > @OOPMan I'm curious to see the case in particular where it failed for you. Can you share a minimal project with 3 case classes and 12 fields that fails to compile under the default settings?
> 
> ```
> case class ColumnEncryptionStrategy(strategyName: String, alphabet: Option[String], fields: List[String])
> case class EncryptionTransformerParameters(
>     inputViewName: String,
>     outputViewName: String,
>     decrypt: Option[Boolean],
>     secretName: String,
>     keyId: String,
>     strategies: List[ColumnEncryptionStrategy]
> )
> case class DEncryptionTransformerInput(
>     transformerType: String,
>     params: EncryptionTransformerParameters
> )
> ```
> 
> Trying to load this using the following code gives stackoverflow error
> 
> ```
> val encryptionTransformerInput = ConfigSource
>       .fromConfig(config)
>       .loadOrThrow[DEncryptionTransformerInput]
> ```
> 
> ```
> [error] java.lang.StackOverflowError
> [error] scala.tools.nsc.typechecker.Contexts$Context.lookupSymbol(Contexts.scala:1047)
> [error] scala.tools.nsc.typechecker.Typers$Typer.typedIdent$2(Typers.scala:5192)
> ```

the error must be due to some settings, since
```
sbt -J-Xmx2G clean coverage 'testOnly *' coverageReport 
```
fails, but
```
sbt clean coverage 'testOnly *' coverageReport 
```
works fine, also changing the mx param has no effect, also running in a container doesn't have the same issue so it's some machine configuration voodoo
