### ISSUE TITLE
Support Scala 2.13

### ISSUE THREAD

**Issue by hugo-vrijswijk** [pureconfig/pureconfig#483]
Since Scala 2.13 is released recently it would be awesome if this library would cross compile to Scala 2.13 as well. 

Am willing to give it a go :)

**Comment by mslinn** [comment]
Pureconfig supported Scala 2.13-RC1 with the fix for #467. Now that 2.13.0 has been released, we are ready to publish our [updated course material for Scala 2.13](https://www.scalacourses.com/showCourse/45). Our only block is that Pureconfig has not yet been released for 2.13.0.

**Comment by ruippeixotog** [comment]
The master branch already has support for Scala 2.13. We'll do a PureConfig soon 👍

**Comment by ruippeixotog** [comment]
0.11.1 is now released with support for Scala 2.13: https://repo1.maven.org/maven2/com/github/pureconfig/pureconfig_2.13/0.11.1
