### ISSUE TITLE
Derivation is failing to resolve a custom ConfigConvert materializer

### ISSUE THREAD

**Issue by erikerlandson** [pureconfig/pureconfig#516]
Context: I'm working on an integration of [coulomb](https://github.com/erikerlandson/coulomb) with pureconfig.

I have a generator (see [this pull-req](https://github.com/erikerlandson/coulomb/pull/42)) for `ConfigConvert` that appears to work well in isolation (it will instantiate implicitly when using `to` and `from` on a coulomb `Quantity`). However, when I try to declare a configuration case class that has `Quantity` members, the corresponding reader will not resolve implicitly, _unless_ I explicitly declare ConfigConvert, in which case it will work.  Here's an example session, where you can see my first `loadConfig` fail, and then after I declare the two `ConfigConvert` values explicitly, it succeeds:

```scala
scala> import coulomb._, coulomb.si._, coulomb.time._, coulomb.info._, coulomb.typesafeconfig._, coulomb.parser._, com.typesafe.config._, coulomb.siprefix._, shapeless._, org.apache.avro._, org.apache.avro.generic._, org.apache.avro.file._, coulomb.avro._, coulomb.binprefix._, _root_.pureconfig._, _root_.pureconfig.generic.auto._, coulomb.pureconfig._

scala> implicit val qp = QuantityParser[Second :: Byte :: Hour :: Giga :: HNil]
qp: coulomb.parser.QuantityParser = coulomb.parser.QuantityParser@67b5409b

scala> case class QC(t: Quantity[Double, Second], m: Quantity[Double, Mega %* Byte])
defined class QC

scala> val conf = ConfigFactory.parseString("""{ "t": { "value": 1, "unit":"hour" }, "m": { "value": 1, "unit": "gigabyte" } }""") 
conf: com.typesafe.config.Config = Config(SimpleConfigObject({"m":{"unit":"gigabyte","value":1},"t":{"unit":"hour","value":1}}))

scala> val conf = ConfigFactory.parseString("""{ t: { value: 1, unit: "hour" }, m: { value: 1, unit: "gigabyte" } }""") 
conf: com.typesafe.config.Config = Config(SimpleConfigObject({"m":{"unit":"gigabyte","value":1},"t":{"unit":"hour","value":1}}))

scala> loadConfig[QC](conf)
                     ^
       error: Cannot find an implicit instance of pureconfig.ConfigReader[QC].
       If you are trying to read or write a case class or sealed trait consider using PureConfig's auto derivation by adding `import pureconfig.generic.auto._`

scala> implicit val ttt = implicitly[ConfigConvert[Quantity[Double, Second]]]
ttt: pureconfig.ConfigConvert[coulomb.Quantity[Double,coulomb.si.Second]] = coulomb.pureconfig.package$$anon$1@71f0008b

scala> implicit val ttt2 = implicitly[ConfigConvert[Quantity[Double, Mega %* Byte]]]
ttt2: pureconfig.ConfigConvert[coulomb.Quantity[Double,coulomb.siprefix.Mega %* coulomb.info.Byte]] = coulomb.pureconfig.package$$anon$1@721a582

scala> loadConfig[QC](conf)
res1: pureconfig.ConfigReader.Result[QC] = Right(QC(Quantity(3600.0),Quantity(1000.0)))
```

**Comment by erikerlandson** [comment]
Wondering if this is some subtle artifact of `inferImplicitValue` in the macros. I've had trouble with that before, and it was one reason I moved `coulomb` out of macros to pure implicits

**Comment by erikerlandson** [comment]
Out of curiosity, was this done in macros because of [this](https://stackoverflow.com/questions/49088319/a-diverging-implicit-expansion-in-scala-involving-chained-implicits)? (Which was [fixed](https://github.com/scala/scala/pull/6050) as of scala 2.13)

**Comment by ruippeixotog** [comment]
Hi @erikerlandson! Sorry for not having replied before. Unfortunately, it's not clear to me why it doesn't work at a first glance; if coulomb was using macros it would be possible that they were not compatible together, but with implicits only I was expecting everything to work.

We use a macro-powered wrapper to show nice debug messages when an implicit cannot be found (https://pureconfig.github.io/docs/faq.html#how-do-i-debug-implicit-not-found-errors). However, unless you explicitly activated the feature using `-Xmacro-settings:materialize-derivations`, the macros should be a very thin wrapper around the base type class.

**Comment by erikerlandson** [comment]
@ruippeixotog thanks!
For fun, I tried compiling it as part of the test build. I dropped the following into my source:
```scala
object pctest {
  import coulomb._, coulomb.si._, coulomb.time._, coulomb.info._, coulomb.typesafeconfig._, coulomb.parser._, com.typesafe.config._, coulomb.siprefix._, shapeless._, coulomb.binprefix._, _root_.pureconfig._, _root_.pureconfig.generic.auto._, coulomb.pureconfig._

  implicit val qp = QuantityParser[Second :: Byte :: Hour :: Giga :: HNil]

  case class QC(t: Quantity[Double, Second], m: Quantity[Double, Mega %* Byte])

  val conf = ConfigFactory.parseString("""{ "t": { "value": 1, "unit":"hour" }, "m": { "value": 1, "unit": "gigabyte" } }""") 

  val qc = loadConfig[QC](conf)  // Now I compile!
}
```
When I do it that way, it compiles fine!  That suggests it isn't a bug in pureconfig, but maybe the REPL's environment is not set up quite right to make the implicit tree resolve.

**Comment by ruippeixotog** [comment]
That's great to hear! The Scala REPL is indeed very flaky, I'm glad it works in a normal environment.
