### ISSUE TITLE
Failing UnexpectedValueForFieldCoproductHint

### ISSUE THREAD

**Issue by chopraarjun** [pureconfig/pureconfig#522]
The sample its self fails

import pureconfig.generic.auto._

sealed trait MyAdt {}

case class AdtA(a: String) extends MyAdt
case class AdtB(b: Int) extends MyAdt
final case class Port(value: Int) extends AnyVal
case class MyClass(
                    boolean: Boolean,
                    port: Port,
                    adt: MyAdt,
                    list: List[Double],
                    map: Map[String, String],
                    option: Option[String])

object Executor {
  def main(args: Array[String]): Unit = {
    println(pureconfig.loadConfig[MyClass])
  }
}

Left(ConfigReaderFailures(ConvertFailure(UnexpectedValueForFieldCoproductHint(Quoted("adtb")),Some(ConfigValueLocation(file:/home/kneuron/IdeaProjects/Aqua/target/scala-2.12/classes/application.conf,4)),adt.type),List()))

**Comment by ruippeixotog** [comment]
Hi @chopraarjun! You're right, the documentation is outdated. Since v0.11.0 the sample `application.conf` should have `type = "adt-b"`, as we changed the mapping from "convert to lowercase" to "convert to kebab-case". I'll fix this shortly.

**Comment by chopraarjun** [comment]
Thanks a lot.
