### ISSUE TITLE
RFC: Rethink config loading API

### ISSUE THREAD

**Issue by nigredo-tori** [pureconfig/pureconfig#531]
At the moment, the API for loading configs is lacking:
1. It has a lot of wrappers and overloads for different scenarios. This is exacerbated  by the fact that these are duplicated in the `catseffect` module.
1. It doesn't cover all the cases that `ConfigFactory` supports (loading from `URL`s, specifying classloaders, etc).
1. It is not very flexible. E.g. there is no way to load a config without the default `application.conf` and `reference.conf` fallbacks.
1. It is not very transparent. E.g. to find out that the `load*` function loads the `reference.conf` resource, I have to dig down until I find that it's based on a `ConfigFactory.load*` function, and then read the javadoc for that. This can be mitigated by properly documenting each function, but that is inconvenient due to point 1.

Most of this stems from the fact that we use the high-level `ConfigFactory.load*` functions.

I propose we add an API for building custom `Config` loading chains, backed by more composable `ConfigFactory.parse*` functions. Something like this:
```scala
// Some ADT - implementation pending
sealed ConfigSource

// `ConfigSource` should provide a combinator-style micro-DSL.
val source: ConfigSource = ConfigSource.file(myConfigFile)
  // reference.conf etc.. The classloader is optional.
  .withFallback(ConfigSource.defaultFallbacks(classloader = Some(myClassLoader)))
  .withNamespace("myApp")

// No more overloads - we only need a single wrapper.
val config = loadConfig[IO, MyConfig](source)

// Mixing custom files with custom resources - not possible with the current API.
val testSource = ConfigSource.file(myTestConfigFile)
  // Optional sources are explicit.
  .optional
  .withFallback(ConfigSource.resource("test-reference.conf", classloader = Some(myClassLoader)))
  .withFallback(ConfigSource.defaultFallbacks(classloader = Some(myClassLoader)))
  .withNamespace("myApp")
```

**Comment by ruippeixotog** [comment]
@nigredo-tori the idea sounds very good, thank you for the detailed proposal! The current explosion of loader methods is not ideal at at all and it's been a problem before. I'd also consider that we have a module currently loading configs from sources other than Typesafe Config (like pureconfig-yaml), and the new API should cater to that one too.

I'll give this some thought and I'll try to build something next week :)
