### ISSUE TITLE
Scala 2.13 pureconfig-cats-effect suppport

### ISSUE THREAD

**Issue by ioreskovic** [pureconfig/pureconfig#535]
I see that core pureconfig module has 2.13 support, but pureconfig-cats-effect is still on 2.12.
Any plans/eta on upgrading?

Thx!

**Comment by jcazevedo** [comment]
Besides `pureconfig-cats-effect`, I think we can start publishing some other modules for Scala 2.13. I'll take a look later today for what we can update.

**Comment by jcazevedo** [comment]
#537 starts building some modules for Scala 2.13. Unfortunately there are no stable cats and cats-effect versions for Scala 2.13 yet.

**Comment by azolotko** [comment]
cats-effect 2.0.0 has been released with Scala 2.13 support.

**Comment by jcazevedo** [comment]
#579 already adds support for Scala 2.13 in the `pureconfig-cats-effect` module. The only thing pending to close this issue is publishing the module. We'll try to do it soon.

**Comment by jcazevedo** [comment]
We've just published `pureconfig-cats-effect` (and `pureconfig-cats` and `pureconfig-circe` as well) for Scala 2.13: https://repo1.maven.org/maven2/com/github/pureconfig/pureconfig-cats-effect_2.13/0.12.1/.
