### ISSUE TITLE
Error when building native image for application with pureconfig

### ISSUE THREAD

**Issue by CucumisSativus** [pureconfig/pureconfig#539]
When I'm trying to build native image for scala application which contains pureconfig. I get the following waring 
```
warning: unknown locality of class Lexample/Hello$anon$exportedReader$macro$16$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lexample/Hello$anon$exportedReader$macro$16$1; which is not following the naming convention.
```
Which is shortly followed by the error:
```
[error] Parsing context:
[error] 	parsing example.Hello$anon$exportedReader$macro$16$1.inst$macro$1(Hello.scala:6)
[error] 	parsing example.Hello$.main(Hello.scala:6)
[error] 	parsing example.Hello.main(Hello.scala)
[error] 	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:147)
[error] 	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
[error] Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[error] Error: Image build request failed with exit status 1
[error] java.lang.RuntimeException: Failed to run native-image, exit status: 1
[error] 	at scala.sys.package$.error(package.scala:26)
[error] 	at com.typesafe.sbt.packager.graalvmnativeimage.GraalVMNativeImagePlugin$.$anonfun$projectSettings$3(GraalVMNativeImagePlugin.scala:52)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

I prepared minimal test case project, where I have the instruction how to reproduce the issue
https://github.com/CucumisSativus/pureconfig-nativeimage

Please let me know if I can assist you somehow with reproducing or fixing this issue.

Thanks in advance for handling it!

**Comment by jcazevedo** [comment]
Thanks for the minimal test case project! I was able to reproduce the issue using it. I haven't investigated a lot, but found [this guide](https://www.graalvm.org/docs/reference-manual/languages/scala/getting-started/#support-for-scala-macros) that indicates some extra steps to use macros in GraalVM.

**Comment by lbialy** [comment]
Not related to macros at all as they are expanded in scala compile time and native-image operates on `.class` files. Problem is basically limited to:
a) Scala 2.13 not compiling to native yet due to new implementation of Vector using `MethodHandles`
b) Scala being a language that doesn't rely on reflection and therefore working much better with `--initialize-at-build-time` native-image flag - without it you get cryptic errors coming from stdlib compilation to native.

**Comment by lbialy** [comment]
OTOH: this project compiles just fine to native binary with 
`graalVMNativeImageOptions ++= Seq("--initialize-at-build-time", "--no-fallback")`
and 
`ThisBuild / scalaVersion     := "2.12.9"`

Another interesting thing that one *has to take into account* when using library based on typesafe config is that you need a special native-image flag to include classpath resources in compiled native-image: `-H:IncludeResources=` - you should list all the `reference.conf` files here, probably in a json configuration file with body like this:

```
{
  "resources": [
    {
      "pattern": "reference.conf"
    },
    {
      "pattern": "application.conf"
    }
  ]
}
```

**Comment by CucumisSativus** [comment]
Thanks a lot for your help @lbialy.

 @jcazevedo im closing this issue since its not related to pureconfig. Sorry for the trouble I caused

**Comment by jcazevedo** [comment]
No trouble at all! Thanks for the help @lbialy!
