### ISSUE TITLE
compile dependent on scalacheck?

### ISSUE THREAD

**Issue by ngbinh** [pureconfig/pureconfig#54]
https://github.com/melrief/pureconfig/blob/master/build.sbt#L32-L33 makes pureconfig `compile` depends on scalacheck. Shouldn't it be only in `test`?

**Comment by leifwickland** [comment]
@ngbinh I agree. Sorry about that. I'll send a PR to fix it.

**Comment by leifwickland** [comment]
@ngbinh Does #55 look right to you?

**Comment by ngbinh** [comment]
perfect! Thanks
