### ISSUE TITLE
Why the `application.conf` in `scala-2.12/classes` and `scala-2.12/test-classes` will be merged in `sbt test`

### ISSUE THREAD

**Issue by UkonnRa** [pureconfig/pureconfig#555]
Say I have a project with two `application.conf`, one in `main/resources` and the other in `test/resources`. Now when I use `pureconfig.loadConfig[SomeConfig]` in the test classes to load test configs, I find the main configs in the `main/resources` will also be merged in the following codes from `com.typesafe.config.impl.Parseable`:
``` java
protected AbstractConfigObject rawParseValue(ConfigOrigin origin, ConfigParseOptions finalOptions){
...
Enumeration<URL> e = loader.getResources(resource);
...
while (e.hasMoreElements()) { 
  // Here both `application.conf` in `scala-2.12/classes` and `scala-2.12/test-classes` will be loaded and MERGED
 }
}
```

Because both `application.conf` in `scala-2.12/classes` and `scala-2.12/test-classes` are merged, some substitute values in `main/resources` will be also needed in the Config of test classes, which is not clean.

Any idea?

**Comment by jcazevedo** [comment]
That is the default behavior of [Typesafe Config](https://github.com/lightbend/config#standard-behavior). In this case, it is loading all `application.conf` files on the classpath, which includes both the `main/resources` and `test/resources`.

Unfortunately, it is not very easy to customize this. You can manually load the configuration files you want with `ConfigFactory.load`; combine them (in case you have multiple files) with `withFallback`; call `resolve()` on the resulting `Config` object to resolve the substitutions; and then supply that `Config` object to PureConfig's `loadConfig` method.

Fortunately, the next version of PureConfig will provide a new API that facilitates the creation of custom config loading "pipelines". You can take a look at it in PR #541.
