### ISSUE TITLE
Wrong value parsed when having a key that starts with the value of another key using hyphens

### ISSUE THREAD

**Issue by fmeeuw** [pureconfig/pureconfig#569]
When having both `foo-bar` and `foo` present in a case class, Pureconfig attempts to parse the value of `foo-bar` and assign it to `foo`. When they both have different types this results in a compile error, however when the types are the same, Pureconfig will assign the value of `foo-bar` to both `foo` and `foo-bar`. 

I noticed the same behaviour with ficus and also reported an issue there: https://github.com/iheartradio/ficus/issues/82. The issue seems to be somewhere in scala internals probably. Will try to have a look myself as well.

Example that does not compile with a type mismatch:
```
 scala.reflect.internal.Types$TypeError: type mismatch;
 found   : Long
 required: String
```

```
import com.typesafe.config.Config
import com.typesafe.config.ConfigFactory
import pureconfig._
import pureconfig.generic.auto._
import pureconfig.generic.ProductHint

implicit def hint[T] = ProductHint[T](ConfigFieldMapping(KebabCase, KebabCase))
case class TestSettings(val `foo-bar`: Long, `foo`: String)

val config = ConfigFactory.parseString("""{ foo-bar: 3, foo: "4" }""")
val settings = loadConfigOrThrow[TestSettings](config)
```

Example that doesn't fail, but assigns the value of `foo-bar` to `foo`. 
```
import com.typesafe.config.Config
import com.typesafe.config.ConfigFactory
import pureconfig._
import pureconfig.generic.auto._
import pureconfig.generic.ProductHint

implicit def hint[T] = ProductHint[T](ConfigFieldMapping(KebabCase, KebabCase))
case class TestSettings2(val `foo-bar`: String, `foo`: String)

val config = ConfigFactory.parseString("""{ foo-bar: "foo-bar", foo: "foo" }""")
val settings = loadConfigOrThrow[TestSettings2](config)
println(settings.`foo-bar`) // prints out foo-bar
println(settings.foo) // also prints out foo-bar!
```

**Comment by jcazevedo** [comment]
This is very weird.

As you indicate, this doesn't seem to be an issue with PureConfig and it looks like scala/bug#8831. You also get a `java.lang.ClassCastException` when using the `apply` method of `TestSettings`:

```scala
scala> case class TestSettings(`foo-bar`: Long, `foo`: String)
defined class TestSettings

scala> TestSettings(3, "4")
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
  ... 37 elided
```

**Comment by jcazevedo** [comment]
`TestSettings2` also exhibits the behavior you describe in its `apply` method:

```scala
scala> case class TestSettings2(`foo-bar`: String, `foo`: String)
defined class TestSettings2

scala> TestSettings2("foo-bar", "foo")
res0: TestSettings2 = TestSettings2(foo-bar,foo-bar)

scala> res0.`foo-bar`
res1: String = foo-bar

scala> res0.`foo`
res2: String = foo-bar
```

**Comment by fmeeuw** [comment]
It indeed seems to be the same issue as https://github.com/scala/bug/issues/8831.
Since it already exists for 4 years, I think I will work around the issue by not using backquotes in case classes anymore.

**Comment by jcazevedo** [comment]
Closing the issue, since this is scala/bug#8831.
