### ISSUE TITLE
Set the PureConfig version of the example project dynamically

### ISSUE THREAD

**Issue by ruippeixotog** [pureconfig/pureconfig#577]
The builds for our commits bumping to a stable version (automatic, issued by sbt-release) always fail because the example project cannot find the appropriate version. Example: 702250ca32bf9934f2f3e3e0cbd2ec6f2b684ccd, [Travis build](https://travis-ci.org/pureconfig/pureconfig/builds/584428026).

We should probably set the PureConfig version in the example project dynamically by reading `version.sbt`.

**Comment by jcazevedo** [comment]
Fixed in ce3b93b3b11299cb07f20b0030f14d5c7f1f5bbe.
