### ISSUE TITLE
YAML Support

### ISSUE THREAD

**Issue by rynbrd** [pureconfig/pureconfig#61]
It does JSON, could it also do YAML?

**Comment by jcazevedo** [comment]
PureConfig supports JSON because of Typesafe Config's compatibility with it. There is no direct support for loading configurations from YAML, but I stumbled upon this project named [Konf](https://github.com/advantageous/konf) that seems to allow creating `Config` objects from YAML documents. Once you get to that, you can use PureConfig directly.

**Comment by leifwickland** [comment]
It seems like a `pureconfig-yaml` which depended on Konf might be worth considering after #62 gets merged.

**Comment by melrief** [comment]
#62 is merged and I think we should consider adding support for other formats. For start, we could use a YAML library to convert a YAML configuration into a lightbend configuration and then use pureconfig as usual but in the long run we may want to consider an intermediate representation of a configuration to which we convert all the formats.

**Comment by melrief** [comment]
I opened #87 as starting point to support new backends. We will need sometime but we will be able to support yaml in future via backends.

**Comment by jgogstad** [comment]
Until pureconfig supports this out of the box, you can do the transformations yaml -> json -> hocon -> case-class -> hocon -> json -> yaml using json4s, moultingyaml and pureconfig. Here's a [gist](https://gist.github.com/jgogstad/f2833bd076268d6cf902973764b0a099).

**Comment by ruippeixotog** [comment]
Pending core support for different backends, this logic can definitely be packed into a pureconfig module.

**Comment by jgogstad** [comment]
Would be nice if the backend supported different casing configurations. With the gist above, you need to provide product hints for every type. This [SO](https://stackoverflow.com/questions/22771226/what-is-the-canonical-yaml-naming-style) lists different client usages.
