### ISSUE TITLE
Release pureconfig-http4s for Scala 2.13

### ISSUE THREAD

**Issue by fbunau** [pureconfig/pureconfig#628]
Hi,

pure config is great !
it seems that pureconfig-http4s is not released for Scala 2.13
https://mvnrepository.com/artifact/com.github.pureconfig/pureconfig-http4s

which creates problem with including it alongside other libraries released for 2.13

Please consider releasing it, thanks !

**Comment by jcazevedo** [comment]
We're still waiting for a stable http4s version for Scala 2.13. We don't usually release modules for non-stable library versions.

**Comment by fbunau** [comment]
Ah cool, that makes sense, it's true I was doing my code on 0.21.0-M5. I'll close this one. 
Thanks for the info didn't think of that aspect
