### ISSUE TITLE
'_' (underscore) support

### ISSUE THREAD

**Issue by Opalo** [pureconfig/pureconfig#631]
This is not actually an "issue" but rather a question: does pureconfig support using `_` instead of `-`? I can't find it in the docs.

Thanks for our great work!

**Comment by jcazevedo** [comment]
PureConfig supports using `_` for token separators as a naming convention in its `ConfigFieldMapping` called `SnakeCase`. You can take a look at the docs page about overriding the reading behavior for case classes (https://pureconfig.github.io/docs/overriding-behavior-for-case-classes.html#field-mappings) for more information about the available conventions and how to use and override them.

**Comment by Opalo** [comment]
Cool, thank you very much!
