### ISSUE TITLE
gradle 6.x scala - configReader not found

### ISSUE THREAD

**Issue by geoHeil** [pureconfig/pureconfig#644]
Previous versions of Gradle had issues with pureconfig due to the outdated compiler (https://github.com/pureconfig/pureconfig/issues/480). 

This has changed recently.
Gradle has upgraded their scala support: https://github.com/gradle/gradle/issues/2158 shows that for 6.x the new scala plugin is merged.

> Gradle 6.0 uses the latest Zinc incremental Scala compiler. The Zinc compiler saw major performance improvements in Zinc 1.0.

However, my build ist still failing for the updated Gradle: `could not find implicit value for parameter A: pureconfig.ConfigReader`.

In the old version, it worked (most of the time). Now it is consistantly failing.

Due to Apache Spark 2.2 I am still stuck on Scala 2.11.
So if I understand it corretly Scala 2.12 is used during compilation for Zinc - could this be causing any issues?
I am using version: 0.11.1 initially, but also when testing for 0.12.1 and migrating away from the deprectated method to `ConfigSource.default.load[T]` fails with the same problem.

It works fine for the IntelliJ compiler though.

**Comment by geoHeil** [comment]
I have created a minimal reproducible example here: https://github.com/geoHeil/pureconfig-debugging

**Comment by geoHeil** [comment]
When instead of using scala 2.11 (which I need to use due to spark) experiment with 2.12, still an error occurs during compilation of the reproducible example. However, this time it is gibberish and contains an unclear exception. But it is clear that something regarding macros and reflection is failing:

```
scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.$anonfun$resolveJavaReflectionRuntime$5(JavaReflectionRuntimes.scala:45)
```

**Comment by leifwickland** [comment]
@geoHeil I regret to inform you that I can't reproduce your problem.
```
/tmp/pureconfig-debugging$ ./gradlew clean compileScala

BUILD SUCCESSFUL in 17s
2 actionable tasks: 2 executed
```

Just for comparison I created a build.sbt and compiled your project too. It was also successful for both scala 2.11 and 2.12.

**Comment by geoHeil** [comment]
Strange. I just did a fresh git clone into an empty folder:

```bash
./gradlew clean compileScala
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileScala
[Error] /Users/geoheil/Downloads/pureconfig-debugging/src/main/scala/pconfigdebugging/Foo.scala:18: could not find implicit value for parameter A: pureconfig.ConfigReader[pconfigdebugging.other.bar.ExtremelyComplexConfig]
one error found

> Task :compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileScala'.
> Compilation failed
```

How could I make this issue reproducible for you?

Before Gradle 6 it was expected that gradles pureconfig build would fail from time to time depending on build order - whereas SBT would work fine as it already used the new zinc compiler.

**Comment by jcazevedo** [comment]
@geoHeil: I was able to reproduce the issue in my machine. 

PureConfig is a "compiler-heavy" library and it seems like the resources provided to the Scala compiler via the Scala Gradle plugin are not enough for your use case. I was able to compile your project using Gradle by increasing the thread stack size, adding the following to `build.gradle.kts`:

```kotlin
tasks.withType<ScalaCompile>().configureEach {
    scalaCompileOptions.forkOptions.apply {
        jvmArgs = listOf("-Xss2m")
    }
}
```

**Comment by geoHeil** [comment]
Very strange - after retrying it again this afternoon it compiles also for me.

**Comment by geoHeil** [comment]
Really awesome! Thanks @jcazevedo . Indeed I can now reliably confirm that both steps

1. Upgrading to the latest version of Gradle
2. increasing the compilation memory (as suggested by you)

are required
