### ISSUE TITLE
Can't expand env variable as List's

### ISSUE THREAD

**Issue by giuscri** [pureconfig/pureconfig#649]
Let's say I have a `reference.conf`
```
myConfig {
  ...
  blacklist=[]
  blacklist=${?BLACKLIST}
}
```
and a schema implemented as
```
case class MyConfig (
  ...
  blacklist: List[String]
)
```
To my knowledge, there's no way to define `$BLACKLIST` as an _array_ such that pureconfig will parse that as a `List[String]`

**Comment by leifwickland** [comment]
@giuscri,

I think you're saying that you want to define `$BLACKLIST` as an array in `bash`'s (or whatever shell's) environment. Is that correct?

Unfortunately, [bash don't put array vars in the environment](https://unix.stackexchange.com/a/393096). It's easy enough to write a small scala app that demonstrates that with `sys.env.foreach(println)` in the main.

The best suggestion I can offer is something like what that SO answer offers: join the array variable into a new flat variable separated by some character first. Then write a `ConfigReader ` that splits on that separator. 

```
  implicit val configReader: ConfigReader[Blacklist] =
    ConfigReader.fromNonEmptyString { s =>
      Right(Blacklist(s.split(",").toList.map(_.trim).filterNot(_.isEmpty)))
    }
```

I wish I had a better answer, but it seems like the limiting factor is the richness of the data model that's available to transmit env vars.
