### ISSUE TITLE
Add support for java.time data structures

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#65]
Add `ConfigConvert` instances for `LocalDate`, `DateTime`...

Most of them needs to be somehow configurable because the string format of a date is not fixed. We could let the user import a template of the instance and the configure it:

```scala
implicit val dateTimeInstance = makeDateTimeInstance(format)
```

**Comment by leifwickland** [comment]
I think this is a great idea. 

Do you think it'd be worth adding support for Joda structures in a separate library?

**Comment by melrief** [comment]
I think for structures in the standard libraries of Java and Scala we should provide support in core so that you need only one libraries to start using it. What do you think?

On a side note, we could support joda-time and that should go in a separate library and be published as `pureconfig-joda`.

**Comment by leifwickland** [comment]
@melrief Yes, I think it makes sense for core Java/Scala date/time types to be in the pureconfig core, in the same way that we support `Duration`/`FiniteDuration` today.
