### ISSUE TITLE
Add Semigroup[ConfigSource], Monoid[ConfigObjectSource]

### ISSUE THREAD

**Issue by nigredo-tori** [pureconfig/pureconfig#667]
We already have a `Semigroup` for `ConfigValue`, so we can just as well make a corresponding one for `ConfigSource`. Maybe even think upgrade one or both of these to `Monoid`, if `ConfigSource.empty` and/or the corresponding `ConfigValue` turn out to be an identity. And we can definitely make a `Monoid[ConfigObjectSource]`.

**Comment by ruippeixotog** [comment]
Hi! Unfortunately `ConfigValue` is not a monoid as the empty object is not an identity for `withFallback` in the presence of scalar values:

```scala
scala> def value(str: String) = ConfigFactory.parseString(s"x: $str").getValue("x")
value: (str: String)com.typesafe.config.ConfigValue

scala> value("3").withFallback(value("{}"))
res2: com.typesafe.config.ConfigValue = ConfigInt(3)

scala> value("{}").withFallback(value("3"))
res3: com.typesafe.config.ConfigValue = SimpleConfigObject({})
```

With `ConfigSource` we decided to forbid combining sources unless the source is guaranteed to be a config object, so we don't even have an associative operation for a plain `ConfigSource`. The flip side is that as you said we can create a `Monoid[ConfigObjectSource]`, as `ConfigSource.empty` should be an identity element.
