### ISSUE TITLE
No valid coproduct type choice found for configuration null for valid configurations since 0.3.3

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#67]
I still have to investigate this but apparently since 0.3.3 we have a regression in which the coproduct instance receives a `null` in input. I think the cause is the default field mapping. More info once I can create a small example of this bug.

EDIT: here an example:
```scala
scala> sealed abstract class TraceConfig
scala> final case class Trace(tracerHostname: String) extends TraceConfig
scala> final case object DoNotTrace extends TraceConfig
scala> final case class Conf(trace: TraceConfig)
scala> pureconfig.loadConfig[Conf](ConfigFactory.parseString("""{  }""")).get
pureconfig.ConfigConvert$NoValidCoproductChoiceFound: No valid coproduct type choice found for configuration null.
  at pureconfig.ConfigConvert$$anon$5.from(ConfigConvert.scala:160)
  at pureconfig.ConfigConvert$$anon$6.$anonfun$from$2(ConfigConvert.scala:173)
  at scala.util.Failure.orElse(Try.scala:220)
  at pureconfig.ConfigConvert$$anon$6.from(ConfigConvert.scala:173)
  at pureconfig.ConfigConvert$$anon$6.$anonfun$from$2(ConfigConvert.scala:173)
  at scala.util.Failure.orElse(Try.scala:220)
  at pureconfig.ConfigConvert$$anon$6.from(ConfigConvert.scala:173)
  at pureconfig.ConfigConvert$$anon$10.from(ConfigConvert.scala:276)
  at pureconfig.ConfigConvert$$anon$2.fromConfigObject(ConfigConvert.scala:126)
  at pureconfig.ConfigConvert$$anon$2.fromConfigObject(ConfigConvert.scala:120)
  at pureconfig.ConfigConvert$WrappedDefaultValueConfigConvert.fromWithDefault(ConfigConvert.scala:93)
  at pureconfig.ConfigConvert$WrappedDefaultValueConfigConvert.fromWithDefault$(ConfigConvert.scala:91)
  at pureconfig.ConfigConvert$$anon$2.fromWithDefault(ConfigConvert.scala:120)
  at pureconfig.ConfigConvert$$anon$9.from(ConfigConvert.scala:263)
  at pureconfig.package$.loadConfig(package.scala:75)
  ... 37 elided
```

Note that it's not the coproduct derivation the issue:

```scala
scala> pureconfig.loadConfig[TraceConfig](ConfigFactory.parseString("""{  }""")).get
res3: TraceConfig = DoNotTrace
```

EDIT2: I think the issue is `ConfigObject.get` and how we use it in [line 126](https://github.com/melrief/pureconfig/blob/master/core/src/main/scala/pureconfig/ConfigConvert.scala#L126): if the key is not found, [`get` returns null](https://github.com/typesafehub/config/blob/master/config/src/main/java/com/typesafe/config/ConfigObject.java#L95) and this propagates to the `ConfigConvert` responsible for the conversion.

EDIT3: the difference between loading directly a coproduct with `loadConf[TraceConfig]` and use a coproduct as field of a class is that in the first case we pass `.root()` to the `ConfigConvert[TraceConfig]`, which is a `SimpleConfigObject({})` while in the second case we pass `null` because of `.get()`

**Comment by melrief** [comment]
@jcazevedo @leifwickland I have a problem here: I know what the issue is but I'm not sure about the kind of semantic we want to give to pureconfig. The bug above is normal since we decided that derive something from `HNil` should always fail. This means that for an ADT above, the field with the name must be defined in the configuration with value `{}` else we throw the error. In other words, the following code returns a `Success` because `trace` is defined and its value is an empty object:

```scala
scala> pureconfig.loadConfig[Conf](ConfigFactory.parseString("""{ trace: {} }"""))
```

The question is the following: do we want coproduct to be optional, in the sense that if the key of the field is not defined and the coproduct has an `object` then we return success with the `object` or we agree that the key of the field must be defined in case of coproducts for pureconfig to work? I think the current behaviour is the correct one but I also think that a better error should be returned. For instance, `CannotConvertNullException` explaining the user that a coproduct can never be created out of a non-existent key. If you agree, I can try to make a patch for this.

**Comment by jcazevedo** [comment]
I think the key of the field should be defined in all fields that are not `Option` nor have a default argument in the constructor. We should always fail when trying to derive a coproduct from `null`, so that your first example would return:

```scala
Failure(pureconfig.error.KeyNotFoundException: Could not find the key trace)
```

**Comment by melrief** [comment]
I think we are done with this since `0.5.1`
