### ISSUE TITLE
Updating from PureConfig 0.7.0 to 0.12.1

### ISSUE THREAD

**Issue by mslinn** [pureconfig/pureconfig#671]
I used the [pure-config-test](https://github.com/mslinn/pure-config-test) project for issue #467; it used PureConfig 0.7.0.

Yesterday I encountered a few rough spots upgrading to PureConfig 0.12.1, so I made a branch in `pure-config-test` called `b0rked` and made the minimum changes to that project so that the issues would be easy to see. Please look for TODO and FIXME messages in `PureConfigFun.scala`:

 1. https://github.com/mslinn/pure-config-test/blob/b0rked/src/main/scala/PureConfigFun.scala#L45-L56
    ```scala
    // TODO This provides less information that the old style error handling, immediately below
    // Is there a better way to write this?
    Left(ConfigReaderFailures(ConvertFailure(WrongType(STRING, Set(OBJECT)), None, config.render)))
    
    // FYI, For PureConfig 0.7.0, this code was:
    //          fail(CannotConvert(
    //            value = config.render,
    //            toType = "Port",
    //            because = s"A port should be a number, but ${ config.valueType } was found",
    //            location = ConfigValueLocation(config),
    //            path = None
    //          ))  
    ```

 2. https://github.com/mslinn/pure-config-test/blob/b0rked/src/main/scala/PureConfigFun.scala#L83-L91
    ```scala
    // TODO how to rewrite this without invoking the deprecated loadConfig method?
    def load: Either[ConfigReaderFailures, PureConfigFun] = pureconfig.loadConfig[PureConfigFun](confPath, "ew")
    
    // TODO how to rewrite this without invoking the deprecated loadConfigOrThrow method?
    // FIXME this worked with PureConfig 0.7.0, but fails on 0.12.1 with:
    // [error] pureconfig.error.ConfigReaderException: Cannot convert configuration to a PureConfigFun. Failures are:
    //[error]   - Unable to read file file:/tmp/sbt_9da3b7/job-2/target/2d0db0fc/821842a3/pure-config-test_2.12-0.1.2.jar!/pure.conf (No such file or directory).
    def loadOrThrow: PureConfigFun = pureconfig.loadConfigOrThrow[PureConfigFun](confPath, "ew")
    ```

Thanks for your help!

**Comment by nigredo-tori** [comment]
Regarding the first point, I believe something llike this should work:
```scala
ConfigReaderFailures(
  ConvertFailure(
    CannotConvert(value = ???, toType = ???, because = ???),
    None, config.render
  )
)
```
or, better yet, if you're decoding from a cursor:
```scala
cur.failed(
  CannotConvert(value = ???, toType = ???, because = ???)
)
```
Regarding the second point, the deprecation message has a recipe for rewriting this. Something like this:
```scala
ConfigSource.default(
  ConfigSource.file(confPath).optional
).at("ew")
  .load[PureConfigFun]
```
The `.optional` isn't in that recipe, but, IIRC, the old version didn't require the file to exist. Replace `load` with `loadOrThrow` for the second example.

**Comment by ruippeixotog** [comment]
@mslinn it looks like you were able to finish the migration after the Q&A on Gitter. Do you still need any help, or can we close this issue?

**Comment by mslinn** [comment]
Thanks again!
