### ISSUE TITLE
Default ConfigFieldMapping should be (CamelCase, KebabCase)

### ISSUE THREAD

**Issue by ruippeixotog** [pureconfig/pureconfig#68]
The current default mapping between config keys and case class fields is camel case to camel case. However, in Typesafe config the _de facto_ standard is to use dashes between words (see examples in [Typesafe config](https://github.com/typesafehub/config#uses-of-substitutions), [akka](http://doc.akka.io/docs/akka/snapshot/general/configuration.html#Listing_of_the_Reference_Configuration), [spray](https://github.com/spray/spray/blob/master/spray-can/src/main/resources/reference.conf), [kamon](https://github.com/kamon-io/Kamon/blob/master/kamon-core/src/main/resources/reference.conf) and many more). As such, it seems more natural to me for the default to be `ConfigFieldMapping[T](CamelCase, KebabCase)`.

What is your opinion on this? Is there a reason for the current default? If you agree with that change I can do a quick pull request.

**Comment by jcazevedo** [comment]
I agree. Kebab case also seems a more natural default for configuration keys to me. @melrief & @leifwickland: what do you think?

**Comment by melrief** [comment]
Ok also on my side but it will be funny to explain to users of the library that are actively using it: from the next version, their configuration files won't load anymore without changes to either the code or the configuration. Not sure how to do this...

**Comment by ruippeixotog** [comment]
Unfortunately, I can't think of a way to do that without breaking compatibility with older versions... Moreover, there doesn't even seem to be a way to warn them on compile time, like libraries sometimes do with `@deprecated` and `@implicitNotFound` warnings.

I guess that if you decide to do this it will have to be a breaking change communicated through documentation only. Have you thought of writing a changelog so users can see migration notes, as well as a high-level overview of the changes?

**Comment by leifwickland** [comment]
My preference would be to leave the default as is. 
- No breaking change
- Easier to grok introductory demo on `someValue` in a config file maps to `someValue` in a `case class`
- I simply prefer the aesthetic of consistent camel case everywhere.

The good news is that either way is pretty trivial to adjust to, so I'm not going to fight over it.

**Comment by ruippeixotog** [comment]
If I could have everything in camel case it would be fine with me. However, together with my project's configs I need to have settings for Akka and all other third-party libraries that rely on Typesafe config, and those I can't change. I definitely want all the keys in my config to have the same style.

Not having that as default is not a show stopper, of course. But having used a different mapping everywhere for a while, it is surely error prone. I change the default mapping by importing an implicit `ConfigFieldMapping[T](CamelCase, KebabCase)` everywhere I parse configs. If I forget the import the code still compiles, but of course it leads to parsing errors in runtime. This is made worse by the fact that IDEs such as IntelliJ mark the import as unused, making operations such as "Optimize imports" unusable (after some investigation, I believe that it has to do with the usage of `Lazy` in the derived `ConfigConvert` instances - as it is a macro, IntelliJ does not continue to analyze the implicit chain). All of this is obviously not an issue with pureconfig - it only highlights the usefulness of a good default mapping :)

**Comment by melrief** [comment]
@leifwickland I usually am for not breaking the API with previous releases but being consistent with existing libraries could be important.

**Comment by jcazevedo** [comment]
If we are to change the default, one way to raise the awareness of it around users of the library (besides documenting the change in a changelog) is to state that in the `KeyNotFoundException` message during some future releases. The most common error users will see if they're not aware that the default mapping has changed will be `KeyNotFoundException`, so pointing there to the new default and also how to customize it will ease the transition.

**Comment by melrief** [comment]
That's a good idea

**Comment by leifwickland** [comment]
Congratulations and thanks to @ruippeixotog! 🎉
