### ISSUE TITLE
Misleading(/incorrect) error message when using cats data structures with auto derivation

### ISSUE THREAD

**Issue by YuvalItzchakov** [pureconfig/pureconfig#681]
```scala
import cats.data.NonEmptyList
import pureconfig.generic.auto._
import pureconfig.module.yaml.YamlConfigSource

object Foo {
  case class Bar(nel: NonEmptyList[String])
  def main(args: Array[String]): Unit = {
    val res = YamlConfigSource
      .string("""
                |nel:
                |  - a
                |  - b
                |  - c 
                |""".stripMargin)
      .load[Bar]

    println(res)
  }
}
```

Given the above example, when compile and ran, generates the following result:

`Left(ConfigReaderFailures(ConvertFailure(WrongType(LIST,Set(OBJECT)),None,nel),List()))`

Which mistakenly indicates there's some sort of structure problem with the case class. However when adding `import pureconfig.module.cats._`, it compiles and runs successfully:

`Right(Bar(NonEmptyList(a, b, c)))`

The error message is misleading. Compiling with `-Ymacro-debug-lite`, it is visible that when compiling without `pureconfig.module.cats._` it picks up the instance from the package:

```scala
<stable> <accessor> lazy val inst$macro$13: pureconfig.ConfigReader[cats.data.NonEmptyList[String]] = pureconfig.module.cats.`package`.nonEmptyListReader[String](pureconfig.this.ConfigReader.traversableReader[String, List](pureconfig.Derivation.Successful.apply[pureconfig.ConfigReader[String]](pureconfig.this.ConfigReader.stringConfigReader), pureconfig.this.FactoryCompat.fromCanBuildFrom[scala.collection.immutable.List.Coll, String, List[String]](immutable.this.List.canBuildFrom[String]))).asInstanceOf[pureconfig.ConfigReader[cats.data.NonEmptyList[String]]];
```

Without, it generates a case class encoder just like any other:

```scala
<stable> <accessor> lazy val inst$macro$13: pureconfig.ConfigReader[cats.data.NonEmptyList[String]] = pureconfig.this.ConfigReader.exportedReader[cats.data.NonEmptyList[String]]((new pureconfig.Exported[pureconfig.ConfigReader[cats.data.NonEmptyList[String]]]((shapeless.lazily.apply[pureconfig.generic.DerivedConfigReader[cats.data.NonEmptyList[String]]](shapeless.Lazy.apply[pureconfig.generic.DerivedConfigReader[cats.data.NonEmptyList[String]]](anon$exportedReader$macro$74.this.inst$macro$14)): pureconfig.ConfigReader[cats.data.NonEmptyList[String]])): pureconfig.Exported[pureconfig.ConfigReader[cats.data.NonEmptyList[String]]])).asInstanceOf[pureconfig.ConfigReader[cats.data.NonEmptyList[String]]];
```

Which makes sense of course, and makes this a tricky problem without specializing cases for `cats.data` in the macro generation.

**Comment by ruippeixotog** [comment]
Cats `NonEmptyList` is defined as `case class NonEmptyList[+A](head: A, tail: List[A])`. If you don't import `pureconfig.module.cats._`, PureConfig has no way of knowing `NonEmptyList` is some kind of collection, as it doesn't extend `Traversable` - it rightly treats it as a simple case class and expects configs to define an object by default. The cats module overrides this behavior and allows `NonEmptyList`s to be defined as lists in your config.

Generally, PureConfig never complains about problems with your case classes; it complains about your config at `load` time if it doesn't comply with the structure of your case classes. [`WrongType`](https://github.com/pureconfig/pureconfig/blob/master/core/src/main/scala/pureconfig/error/FailureReason.scala#L95-L103) is about a mismatch in config value types, as shown in the Scaladoc and in the result of calling `prettyPrint` on your `ConfigReaderFailures`.

**Comment by YuvalItzchakov** [comment]
Right, makes sense. Not sure if there's a way around this
