### ISSUE TITLE
Unable to override spark configurations from non-default files

### ISSUE THREAD

**Issue by LvffY** [pureconfig/pureconfig#711]
Hello,

First of all, thank you for this framework and all documentation provided with it ! :)

Unfortunately, I'm coming with a problem that I was unable to solve myself ... Here it is : In my projet, we use Spark with Scala. For the configurations of our pipelines we use your framework (in **0.12.2** version)

For now, we've only used default files that are **application.conf** and **reference.conf**. But now, we'd like to use some other files (for isolation purposes). But when we want to override the custom files, the method doesn't work anymore. 

I tried to minimize the code for all files quoted above, and was able to reproduce the error. Here is the code : 

### Default application 

- **application.conf** : 
```hocon
{
  appconf = "Hello From Application"
  appconf = ${?APPLICATION_CONF}
}
```

- Associated CC : 
```scala
case class MyApplication(appconf: String)
```

### Default reference

- **reference.conf** : 
```hocon
{
  refconf = "Hello From Reference"
  refconf = ${?REFERENCE_CONF}
}
```

- Associated CC : 
```scala
case class MyReference(refconf: String)
```

### Custom reference

- **/path/to/another/directory/reference.conf** : 
```hocon
{
  anotherrefconf = "Hello From Another Reference"
  anotherrefconf = ${?ANOTHER_REFERENCE_CONF}
}
```

- Associated CC : 
```scala
case class MyOtherReference(anotherrefconf: String)
```

### Custom file

- **/path/to/another/directory/other.conf** : 
```hocon
{
  otherconf = "Hello From Another Conf"
  otherconf = ${?ANOTHER_CONF}
}
```

- Associated CC : 
```scala
case class MyOtherConf(otherconf: String)
```

### Main

```scala
import pureconfig.ConfigSource

object MyApp extends App {

  import pureconfig.generic.auto._

  val appConf = ConfigSource.default.loadOrThrow[MyApplication]
  println(appConf)

  val refConf = ConfigSource.default.loadOrThrow[MyReference]
  println(refConf)

  val otherref = ConfigSource.resources("path/to/another/directory/reference.conf").loadOrThrow[MyOtherReference]
  println(otherref)

  val otherconf = ConfigSource.resources("path/to/another/directory/other.conf").loadOrThrow[MyOtherConf]
  println(otherconf)

}
```

### Reproduce

**N.B: ** The following `2>/dev/null` are just here to reduce verbosity of `spark-submit`commands

To reproduce the error you can : 

- Launch without any override : `spark-submit --class myApp yourJar.jar 2>/dev/null`. In this case, you should have an output like this : 
```console
MyApplication(Hello From Application)
MyReference(Hello From Reference)
MyOtherReference(Hello From Another Reference)
MyOtherConf(Hello From Another Conf)
```

- Launch with overrides : `spark-submit --class MyApp --conf spark.driver.extraJavaOptions="-DAPPLICATION_CONF='Hello From Outside of jar' -DREFERENCE_CONF='Hello From Outside of jar' -DANOTHER_REFERENCE_CONF='Hello From Outside of jar' -DANOTHER_CONF='Hello From Outside of jar'" yourJar.jar 2>/dev/null`. In this case, you should have an output like this : 
```console
MyApplication(Hello From Outside of jar)
MyReference(Hello From Outside of jar)
MyOtherReference(Hello From Another Reference)
MyOtherConf(Hello From Another Conf)
```

But, my expected is that I would have an output like this : 
```console
MyApplication(Hello From Outside of jar)
MyReference(Hello From Outside of jar)
MyOtherReference(Hello From Outside of jar)
MyOtherConf(Hello From Outside of jar)
```

**Comment by jcazevedo** [comment]
I suspect that by using `ConfigSource.resources` you're not picking up the system properties overrides. Can you try replacing `ConfigSource.resources("<path>")` by `ConfigSource.defaultOverrides.withFallback(ConfigSource.resources("<path>"))`?

**Comment by LvffY** [comment]
Thanks for your (very) quick answer ! 

According to your suggestion, my Scala class is : 
```scala
import pureconfig.ConfigSource

object MyApp extends App {

  import pureconfig.generic.auto._

  val appConf = ConfigSource.default.loadOrThrow[MyApplication]
  println(appConf)

  val refConf = ConfigSource.default.loadOrThrow[MyReference]
  println(refConf)

  val otherref = ConfigSource.defaultOverrides.withFallback(ConfigSource.resources("path/to/another/directory/reference.conf")).loadOrThrow[MyOtherReference]
  println(otherref)

  val otherconf = ConfigSource.defaultOverrides.withFallback(ConfigSource.resources("path/to/another/directory/other.conf")).loadOrThrow[MyOtherConf]
  println(otherconf)

}
```

And it worked ! 😄 

For now, I can live with this solution. But is there any chances that this could be fixed ? From my point of view, my initial code should work, right ?

**Comment by jcazevedo** [comment]
> For now, I can live with this solution. But is there any chances that this could be fixed ? From my point of view, my initial code should work, right ?

I think the current behavior is expected. `ConfigSource.resources` returns a config source with only the provided resource files. There are different sources for system properties (`ConfigSource.systemProperties`). Using them implicitly in `ConfigSource.resources` would break the abstraction.

However, note that the HOCON specification states that substitutions fallback to environment variables (https://github.com/lightbend/config#features-of-hocon), so you should be able to only use `ConfigSource.resources` if you provide the substitutions via environment variables instead of system properties.

**Comment by LvffY** [comment]
Thanks for all of this precisions :)

I have a solution that you say is the expected behavior (and possibly another way to make it work as I first tried) so I close the issue. 

Best regards
