### ISSUE TITLE
Proposal: add fallback to URL reader that uses getClass.getResource

### ISSUE THREAD

**Issue by ajaychandran** [pureconfig/pureconfig#717]
This would enable loading file `URL`s from the classpath.

I can submit a PR, if this is approved.

**Comment by ruippeixotog** [comment]
Hi @ajaychandran! I'm assuming you're talking about `ConfigSource.url`, right? `file://` URLs are already supported by that source, independently of where they come from. Can you provide me a (minimal) example where it doesn't do what you expect? Loading URLs is done by Typesafe Config and it just resorts to calling `url.openConnection().getInputStream()` for reading data, so AFAIK there's nothing to configure there.

If you mean `url` accepting things like `/path/to/my/resource.conf`, I don't think it's a good idea as 1) it's very unclear that this path should be rooted in the classpath and not anywhere else in the file system, 2) it's technically not a URL as it's missing the protocol. I'd just adapt client code to call `ConfigSource.resource` instead.

**Comment by ajaychandran** [comment]
I was referring to the latter. Particularly, loading URLs for resources in JAR files.
I guess I can handle this in client code.

Thanks for your consideration @ruippeixotog
