### ISSUE TITLE
How to use environment variable for username independantly of OS

### ISSUE THREAD

**Issue by LvffY** [pureconfig/pureconfig#728]
Hello,

I have a problem for you that I was unable to solve myself. 

In my test environment I need to use the environment variable for the username. Unfortunately, my IDE environment is on Windows and my CI environment is on Linux.

An example application.conf on windows would be like
```hocon
example {
  ...
  aVariableWithUserName = "foo"${USERNAME}"bar"
}
```

But to make it work on CI (i.e Linux), my confs needs to be changed as
```hocon
example {
  ...
  aVariableWithUserName = "foo"${USER}"bar"
}
```

Do you know any solution (or workaround) to this problem ? 

Thanks in advance !

**Comment by ruippeixotog** [comment]
Hi @LvffY! If you just want the username and don't care if it comes from an environment variable or somewhere else, you can use `${user.name}`, as `user.name` is a Java [system property](https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html).

If you really want to use environment variables, you can define an auxiliary config key with fallbacks:

```
myUsername = {?USERNAME}
myUsername = {?USER}

example {
  aVariableWithUserName = "foo"${myUsername}"bar"
}
```

I'm closing this issue as this is not a question about PureConfig, it's about [Typesafe Config features](https://github.com/lightbend/config#using-hocon-the-json-superset). Any further questions are better suited to Typesafe Config's repo. I hope the solutions work for you, though!
