### ISSUE TITLE
Need to re-release with new magnolia version 0.15.0+

### ISSUE THREAD

**Issue by neko-kai** [pureconfig/pureconfig#743]
After https://github.com/propensive/magnolia/pull/235 `pureconfig-magnolia` needs to be recompiled to take advantage of not having to depend on `scala-reflect` classes in runtime anymore

**Comment by ruippeixotog** [comment]
It seems that with 0.15.0 `exportedMagnolia` is not compiling anymore, since it references `scala.reflect` (#742). We need to fix this before being able to use 0.15.0.

**Comment by neko-kai** [comment]
@ruippeixotog Adding `libraryDependencies += "org.scala-lang" % "scala-reflect" % scalaVersion.value % Provided` to pureconfig-magnolia's build.sbt will fix it

**Comment by neko-kai** [comment]
https://github.com/pureconfig/pureconfig/pull/744

**Comment by jcazevedo** [comment]
PureConfig 0.13.0, including the change from #744, was just released.
