### ISSUE TITLE
missing support for typesafe config's getBytes

### ISSUE THREAD

**Issue by eyalfa** [pureconfig/pureconfig#769]
1. missing asBytes method on the cursor (delegating to `com.typesafe.config.Config#getBytes`)
2. missing `ConfigReader' instance for com.typesafe.config.ConfigMemorySize

please lmk if you're open for PR contribution.

**Comment by jcazevedo** [comment]
I was wondering if we should support `asBytes` or adapt the `as<NumericType>` methods to follow the [size in bytes format](https://github.com/lightbend/config/blob/master/HOCON.md#size-in-bytes-format) from HOCON. Even though the latter may be more convenient for implementations of `ConfigReader`s, the fact that single-character unit abbreviations map to powers of two (i.e. `1K` is 1024) can be confusing, so I think it should be preferable to have a separate `asBytes` implementation.

I believe we're open for PRs with these changes, yes.

**Comment by jcazevedo** [comment]
Closed by #775.
