### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by ruippeixotog** [pureconfig/pureconfig#77]
It's always good to have a log of what changed between releases. The commit tree sometimes works, but particularly for external users it makes sense to have a compact list enumerating what can users expect after an upgrade - which bugs were fixed, what improvements were made and what are the breaking changes. This last one is particularly important; if there is not a way to make things backwards compatible, it makes sense for users to have a place where they at least know what changed.

Although they are not libraries, I take as good examples the changelogs for [terraform](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md) and [marathon](https://github.com/mesosphere/marathon/blob/master/changelog.md). They are well organized and easily searchable. Based on those, I adopted a much more modest version [for one of my libraries](https://github.com/ruippeixotog/scala-scraper/blob/master/CHANGELOG.md).

What do you think of adding such a document? Adding it does not mean we shouldn't try to avoid breaking APIs, but it would give more information to users in case we decide to do it.

(@melrief @jcazevedo @leifwickland I'm opening these issues to get your general opinion, if you think it's a good idea I don't mind writing it :))

**Comment by leifwickland** [comment]
I love change logs. I just hate writing them. ;-)
I think it would be a terrific idea to at one, particularly to document the breaking changes we've been introducing.

**Comment by melrief** [comment]
I think changelogs are essential at this point. I like the changelog of @ruippeixotog example, I propose to follow that format. Now the main issue that I see is that we have a lot of legacy versions. Shall we collect info for the previous version or just start with the `0.5.1`?

**Comment by leifwickland** [comment]
I suggest we just hit the versions which introduced breaking changes in the last few months and move forward. I think that's a reasonable compromise of appearing to be responsible with versioning while not exerting too much undue effort.

**Comment by ruippeixotog** [comment]
Yeah, logging only breaking changes for old versions and starting to write all changes for future versions seems a nice compromise.

**Comment by melrief** [comment]
Now that we all agree, I guess we have to decide who takes care of adding the document. I propose myself for obvious reasons and I also propose that we should not release `0.5.1` without completing the changelog.

**Comment by ruippeixotog** [comment]
I can write the changes for this version and the last version probably. Versions older than that I'm not so sure of the changes.

**Comment by melrief** [comment]
If you want to create the changelog file for the last two releases, I can fill the remaining parts with another PR. The last two versions are the important one for the changelog anyway.
