### ISSUE TITLE
Mixing with environment variables

### ISSUE THREAD

**Issue by otobrglez** [pureconfig/pureconfig#788]
Hey guys!

I have a simple `application.conf` configuration file that has something similar to this in it

```
server {
  port = 3000
  port = ${?PORT}
}
```

This works perfectly fine and is - to my understanding compliant with [lightbend/config's - environment variable overrides](https://github.com/lightbend/config#optional-system-or-env-variable-overrides) guidelines. Now the problem becomes when I use `pureconfig` and case classes where the `port` is defined as `Int`.

```scala
case class ServerConfiguration(port: Int)
case class Configuration(server: ServerConfiguration)

object Configuration {
  def loadOrThrow: Configuration = ConfigSource.default.loadOrThrow[Configuration]
}
```

So my question is; what is the right approach in this case? One way would be to define the port as String - but that feels just wrong.

The exception that I get is the following: 

```
Exception in thread "main" pureconfig.error.ConfigReaderException: Cannot convert configuration to a Configuration. Failures are:
  at 'server.port':
    - Expected type NUMBER. Found STRING instead.
```

Thanks for your thoughts and effort! Cheers!

**Comment by jcazevedo** [comment]
Converting a string to a number is part of the [HOCON automatic type conversions](https://github.com/lightbend/config/blob/master/HOCON.md#automatic-type-conversions) which we try to follow, so you shouldn't be getting that exception unless `server.port` is a string that can't be parsed to a number according to the JSON rules.

**Comment by jcazevedo** [comment]
So that I can try to replicate the issue, which version of PureConfig are you using, and what value(s) of `PORT` trigger that exception?

**Comment by otobrglez** [comment]
All environment variables that get passed in (in this case `PORT=4000` for example) get passed as a `string`. However, as you can see in the `application.conf`; the port is a number - as it was previously set to 3000 in the file.

**Comment by otobrglez** [comment]
**I'm so sorry. I think that I've made a mistake.**

When configuring the "run" in IntelliJ IDEA I've configured several environment variables split by spaces, and that causes the PORT part to be passed as a string of jibberish.

You can probably close this issue. :)

**Comment by jcazevedo** [comment]
No worries. :)

Thanks!

**Comment by jcazevedo** [comment]
It'd probably be helpful to include the value tried to read from, together with the type, in the error message. We'll consider that as a future improvement.

**Comment by otobrglez** [comment]
Yes; that would definitely help to hunt down this mistake.
