### ISSUE TITLE
Support HOCON arrays

### ISSUE THREAD

**Issue by thirteen37** [pureconfig/pureconfig#8]
Using a config such as:

```
myconfig.mylist: [1, 2, 3]
```

and a case class such as:

```
case class myconfig(mylist: List[Int])
```

appears to be unsupported.

Instead, I have to use a syntax such as:

```
myconfig.mylist: "1,2,3"
```

**Comment by melrief** [comment]
In theory it should be supported, what error do you get?

**Comment by melrief** [comment]
I confirm there is a bug in the HOCON list handler, I'll fix it now. Wait for 0.1.5.

**Comment by melrief** [comment]
Ok, 0.1.5 released with the fix. I added [a test](https://github.com/melrief/pureconfig/blob/master/src/test/scala/pureconfig/PureconfSuite.scala#L57) that should handle this case. @thirteen37 let me know if it works.
