### ISSUE TITLE
Dotty / Scala 3 Support

### ISSUE THREAD

**Issue by bbstilson** [pureconfig/pureconfig#854]
I was chatting with some kind folks in the dotty gitter, and someone pointed out that because the derivation macros are based on Scala 2 macros, pureconfig can't be used with dotty/scala 3 until they're ported.

**Comment by jcazevedo** [comment]
Starting to add support for Scala 3 in PureConfig has been on my backlog for a while, but I haven't started working on it yet. I think I'll be able to have some time for it later this week. I won't get in the way of pull requests if someone wants to start tackling it in the meantime.

**Comment by jakubjanecek** [comment]
Hi, what is the progress on Scala 3 support. If I see it correctly the `master` is already build for Scala 3 but there is not official (SNAPSHOT) release. Could you please make some so that other projects depending on PureConfig can start preparing for Scala 3? Thank you.

**Comment by ruippeixotog** [comment]
Good call @jakubjanecek, I thought we already had a released version for Scala 3. I'll try to do a release this weekend.

**Comment by ruippeixotog** [comment]
`pureconfig-core` v0.14.1 [was released](https://mvnrepository.com/artifact/com.github.pureconfig/pureconfig-core) this weekend for Scala 3.0.0-RC1, you should be able to use it now. Sorry again for the delay.

**Comment by jakubjanecek** [comment]
Thanks but unfortunately `pureconfig-core` is not enough, I need the full `pureconfig` artifact as I am using the `semiauto` derivations in my project. Or is there other way around that?

**Comment by jcazevedo** [comment]
We're still working on adding support for automatic derivation of `ConfigReader` and `ConfigWriter` instances in Scala 3. In the meantime, only pureconfig-core is available, so you won't be able to use semiauto derivations. If you want to immediately start using the new PureConfig version in Scala 3, you can migrate your instance definitions to use the `ConfigReader.forProductN` and `ConfigWriter.forProductN` helpers.

**Comment by dyercode** [comment]
So since you closed this, what specific issue is there to follow for derivations/pureconfig proper? For those of us who were watching this issue expecting it.

**Comment by jcazevedo** [comment]
@dyercode: You can use #970 to keep track of that.

**Comment by bbstilson** [comment]
Thanks for your hard work @jcazevedo, @ruippeixotog
