### ISSUE TITLE
Split ConfigConverter into two parts: for reading and for writing

### ISSUE THREAD

**Issue by 13h3r** [pureconfig/pureconfig#92]
There are some cases where end-user just want to read config and do not need to write it. In such cases we do not need to force to implement writer part.

**Comment by melrief** [comment]
I agree with this issue and I think it's important to split `ConfigConvert`. Right now, pureconfig required both the encoding and the decoding to be defined but then it uses only one of the two in each part of the library. From a design point of view this is a mistake. Also I think it's normal and to be expected from some users to just define the reading part.

The main issue that we have to address is how to manage this core change. There are two issues to address: breaking the public API and breaking core:

1.  the API doesn't have to break for this issue to be implemented if we keep `ConfigConvert`: we can create a `ConfigEncoder` and a `ConfigDecoder` to convert to/from a configuration and then make `ConfigConvert` extend both. In this way existing code should still work. If we agree on keeping `ConfigConvert` then this is easy to do.
2. the main issue is that we need to change almost everything in the core part of pureconfig. We need to split [`ConfigConvert.scala`](https://github.com/melrief/pureconfig/blob/51021e7436ec55cc6991cdd07c284ee2daee60d9/core/src/main/scala/pureconfig/ConfigConvert.scala#L31) into two files, `ConfigEncoder.scala` and `ConfigDecoder.scala` and then split every functionality in `ConfigConvert.scala` into the encoding and decoding functionality. It's not difficult to do but it's a lot of code to change and we should do it when nobody is working on a PR. I propose to fix the PRs for the next release and then implement this as very last PR

@leifwickland @jcazevedo @ruippeixotog let me know what do you think of this, I would like to do it as soon as possible and @13h3r seems interested in pushing a PR. He is just waiting for our comments.

**Comment by ruippeixotog** [comment]
I agree with the split. I would even go so far as to say that `ConfigDecoder` is what most people will ever have to use. We can still provide a way to implicitly construct `ConfigConvert` from `ConfigReader` and `ConfigWriter` instances and keep compatibility with existing code (as well as convenience for code that both reads and writes configs).

I like your solution :) Anyone that has used [spray-json](https://github.com/spray/spray-json) (which have a model very similar to ours) and [spray-json-shapeless](https://github.com/fommil/spray-json-shapeless) extensively knows that maintaining separate hierarchies for reading and writing objects is the only way to compose correctly higher-order formats. Maintaining the reading and writing code separately is a downside to me as it's easier to change things in one side and forget the other, but we should be fine with that.

By the way, I think `ConfigReader` and `ConfigWriter` are more accurate names for what this library is doing. Encoding and decoding are commonly associated with converting to and from binary or non-human readable formats.

If we agree to go on with it, I don't mind taking care of that :)

**Comment by jcazevedo** [comment]
I agree with the split, and I also think we should keep `ConfigConvert` and a way to implicitly create it from a `ConfigReader`/`ConfigDecoder` and a `ConfigWriter`/`ConfigEncoder`.

**Comment by leifwickland** [comment]
I'm also in favor of the split.

**Comment by melrief** [comment]
@13h3r everybody agree and I would say it would be nice to have this for the next release. Do you want to work on this? 

@ruippeixotog I agree about `ConfigReader` and `ConfigWriter` being better than Encoder/Decoder, let's go for those.

**Comment by 13h3r** [comment]
@melrief Yes, I will take a try.
