### ISSUE TITLE
Make Converters composable

### ISSUE THREAD

**Issue by 13h3r** [pureconfig/pureconfig#93]

**Comment by melrief** [comment]
@13h3r this issue is about implementing methods like `map`, `flatMap`, etc on `ConfigConvert`, right? I may need some description before I can comment.

**Comment by 13h3r** [comment]
Yes, the idea is about reusing existing converters like configConverter and call map on it

**Comment by melrief** [comment]
I can think about at least `map` and `flatMap`, but we could have a look at circe decoders to see how they compose.

**Comment by leifwickland** [comment]
[`contramap`](https://github.com/argonaut-io/argonaut/blob/master/argonaut/shared/src/main/scala/argonaut/EncodeJson.scala#L26) or [`xmap`](https://github.com/tpolecat/doobie/blob/series/0.4.x/yax/core/src/main/scala/doobie/util/atom.scala#L35) is a similar idea that I've used from argonaut and doobie, respectively.
