### ISSUE TITLE
Support cats-effect 3.0 series and http4s 1.0 series in modules

### ISSUE THREAD

**Issue by arixmkii** [pureconfig/pureconfig#946]
`cats-effect` 3 has reached RC2 state. It would be nice to start building support for this new library. This will also involve bumping `http4s` to 1.0 series, which supports `cats-effect` 3.0 series.

Both modules are pretty compact, so, it should be relatively easy to implement. The only significant change will be to undeprecate methods w/o `Blocker` instances (because `Blocker` is gone), so, the API of cats-effect module will change in significantly breaking way.

But the problem is that it will be difficult to maintain versions for both series ce3/http4s1 and ce2/http4s0.21 withing the same tree and keep the current versioning scheme. May be it is worth to extract them to separate project/projects and apply reflect version differences there. But this will require some planning from project maintainers anyway.

**Comment by rubiconvvv** [comment]
++++ For this

**Comment by kubukoz** [comment]
CE 3.0 is out ;)

**Comment by arixmkii** [comment]
Also fs2 3.0 is out :) And Http4s 1.0.0-M builds are stabilizing. Don't know if sttp is ready for ce3, though. Too many modules in pureconfig :D 
Updated:
It seems from `sttp` only model is in use. So, no changes there.
FS2 and Http4s compiled just fine with version bumps, but ce will require some work.

**Comment by arixmkii** [comment]
Added PR. May be it will be of some use.

**Comment by rubiconvvv** [comment]
@arixmkii thanks
