### ISSUE TITLE
Generate README and other documentation via `tut` to ensure example code compiles

### ISSUE THREAD

**Issue by leifwickland** [pureconfig/pureconfig#96]
I propose that we migrate our README and any other applicable documentation to being generated by [`tut`](https://github.com/tpolecat/tut). I recently worked on another project which made the transition and it was overwhelmingly positive. (See https://github.com/rubicon-project/rubiz/commit/d16b4996094703a33f8cf385292ad852113ed3b7)

The major benefits of tut are:
- The compiler ensures that examples compile and
- The runtime ensures that sample outputs are correct, rather than being copy-pasted into a comment.

The downsides of using tut are:
- Contributors need to remember to edit `src/main/tut/README`, etc, instead of the normal file they'd expect.
- Separating the PR for a big change to the code from the PR to update the documentation is no long possible.

If you guys are on board with that idea I'll take a swing at migrating the README, when the docs in a quiescence period between PRs.

**Comment by ruippeixotog** [comment]
I believe #112 will put the README in a state where you can give `tut` a try. I never used it, but it looks very useful!

**Comment by derekmorr** [comment]
@leifwickland I recently converted squants' documentation to use tut. Happy to help on this if you'd like.

**Comment by leifwickland** [comment]
Derek,

Sure. Feel free. I failed to get started on this ticket over the weekend.
It's all green field. It'd be more a case of me helping you at that point.

On Mar 7, 2017 20:50, "Derek Morr" <notifications@github.com> wrote:

@leifwickland <https://github.com/leifwickland> I recently converted
squants' documentation to use tut. Happy to help on this if you'd like.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/melrief/pureconfig/issues/96#issuecomment-284939056>,
or mute the thread

**Comment by leifwickland** [comment]
@derekmorr Have you gotten started on the tut-ification? It looks like I'll have time this weekend.

**Comment by derekmorr** [comment]
I've started on it. I should have something up later this weekend.

**Comment by leifwickland** [comment]
Derek,

Cool. Thanks. I'm happy to stay out of the way if that's easier for you

**Comment by derekmorr** [comment]
Will definitely need feedback on things once it's up.
