### ISSUE TITLE
Support for enumeratum

### ISSUE THREAD

**Issue by aeons** [pureconfig/pureconfig#97]
I'm using [Enumeratum](https://github.com/lloydmeta/enumeratum) with pureconfig, and I wrote a ConfigConvert instance for enumeratum enums. Would there be interest in including it in pureconfig?

I couldn't figure out the correct place to put the implementation if that was the case, but this is the code:

```scala
import enumeratum.{Enum, EnumEntry}
import pureconfig.ConfigConvert

import scala.util.Try

trait EnumeratumConfigConvert {
  implicit def enumeratumConfigConvert[A <: EnumEntry](implicit enum: Enum[A]): ConfigConvert[A] =
    ConfigConvert.stringConvert[A](name => Try(enum.withName(name)), _.toString)
}
```

**Comment by melrief** [comment]
Ehi @aeons, thanks for the code! Some time ago we decided to go multi-project with the intent of supporting external libraries in modules. This is recent and tthere isn't any module yet (waiting for @leifwickland to create the one about `joda-time` :stuck_out_tongue:) so I can't show you an example, but I can tell you how to do it in case you are interested in including that code in pureconfig:

1. create a new module under `modules/<module_name>` where `<module_name>` can be `enumeratum` in this case
2. add the module to the main `build.sbt` and make it `dependsOn(core)`:

```scala
lazy val enumeratum = (project in file("enumeratum")).
  settings(settings).
  dependsOn(core)
```

3. create `modules/<module_name>/build.sbt` with the dependencies needed and a name starting with `pureconfig-`:

```scala
name := "pureconfig-enumeratum"

version := "0.1"

libraryDependencies += "com.beachape" %% "enumeratum" % "1.5.6"
```

4. create the source file containing the converter that you want to publish. The package should be `pureconfig.module.<module_name>`, e.g.:

```scala
package pureconfig.module

package object enumeratum {
  // your converters here
}
```

After this, we will review your code and then you can publish the artifact `pureconfig-enumeratum`.

For module contributions, my policy would be to keep modules small and to give ownership to the person creating them. Ownership means that the author would be responsible for PRs on the module, versions and for publishing the artifact. If the author prefers a more passive approach, then after merging the PR one author would keep the module up-to-date and publish the artifact.

**Comment by aeons** [comment]
Ok, I'll take a stab at it :)

**Comment by leifwickland** [comment]
@melrief My initial assumption had been that we'd version of the core pureconfig and any ancillary libraries together. If we place the version for ancillary libraries it'll be easy for them to diverge. It looks to me like doobie and cats follow the strategy of versioning all the pieces together. 

Could I convince you that we ought to only have one version number for all of the libraries?

(And duly noted that I'm way behind on delivering the joda library. I can only say that it's ski season. ;-) )

**Comment by melrief** [comment]
@leifwickland yes, maybe that's simpler to maintain and to use. I've just noticed how nice is to import and use circe when everything have the same circeVersion. Ok then, let's keep the same version everywhere.

**Comment by aeons** [comment]
I'm not that sharp on sbt, how do I reference the version from the enumeratum project then?

Or will that be handled from the main build.sbt?

**Comment by melrief** [comment]
You need to move the file [`core/version.sbt`](https://github.com/melrief/pureconfig/blob/58b315d6cbb88080edaf49f4dc0f2a154d4f85d2/core/version.sbt) to `version.sbt` at multi-project level and add `in ThisBuild` after `version`. In this way all the modules that don't define the version will have the version read from that file. You can see if it works via `sbt version`.
